### ISSUE TITLE
Finetuning Torch Vision Model Tutorial is lacking some information

### ISSUE THREAD

**Issue by ValerioB88** [pytorch/tutorials#1008]
As it emerged from this discussion https://discuss.pytorch.org/t/passing-to-the-optimizers-frozen-parameters/83358 with @ptrblck this tutorial https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html could benefit for some clarification about different way of freezing the parameters.

I see two possible versions:
1.  Present the simplest version to obtain feature extraction, which is to set `requires_grad = False `
for the classifier parameters, but still pass `net.parameters() `to the optimizer. As reported in the post answer, 
```
The parameters with `requires_grad = False` won’t accumulate a gradient during the backward pass and their .grad attribute will stay None by default (if no previous gradient was calculated).
The optimizer will skip all parameters with a None gradient
```

2. Present the more complex option (setting the `requires_grad = False`, accumulate the parameters to update and only pass those to the optimizer), but also present the (1) option and explain when we would prefer one or the other (it seems to me that the more complex option is less error prone as it makes sure that the optimizers only operate on those parameters -whereas the 'simpler' option is more flexible).

I tend to prefer solution 1.

**Comment by holly1238** [comment]
Closing as this tutorial no longer exists on the site/master branch
