### ISSUE TITLE
Hyperlinks not properly formatted in colab

### ISSUE THREAD

**Issue by aamster** [pytorch/tutorials#1011]
Hyperlinks are formatted as, for example
https://github.com/pytorch/tutorials/blob/master/beginner_source/nn_tutorial.py#L11
which displays exactly as is.

They should be formatted as `[link text](https://)` which will format it properly.

**Comment by QasimKhan5x** [comment]
does this have to be implemented for the entire codebase? I came up with a basic script that can do this:

    import os
    import re

    def replace_sequence_in_files(directory, file_extension, old_sequence, new_sequence):
        for root, dirs, files in os.walk(directory):
            for file in files:
                if any([file.endswith(ext) for ext in file_extension]):
                    file_path = os.path.join(root, file)
    
                    with open(file_path, "r+", encoding="utf-8") as f:
                        content = f.read()
                        replaced_content = re.sub(old_sequence, new_sequence, content)
                        f.seek(0)
                        f.write(replaced_content)
                        f.truncate()
                        if content != replaced_content:
                            print(file_path)
    
    
    # Usage example
    directory = "."
    file_extension = [".py", ".rst"]
    old_sequence = "`(.+) <(http.+)>`_+"
    new_sequence = r"[\1](\2)"
    
    replace_sequence_in_files(directory, file_extension, old_sequence, new_sequence)

**Comment by fabiogomez11c** [comment]
@svekars I don't understand quite well this issue, I ran `GALLERY_PATTERN="nn_tutorial.py" make html` to check but all the links were perfectly formatted, maybe I'm missing something. Summary: Couldn't replicate.

**Comment by aamster** [comment]
It has been a while, but if I recall the issue was that it looked like the intention was to display the proper text with a hyperlink on click, but the actual url was being displayed instead. Anyways that doesn't seem to be the case anymore. Closing the issue.
