### ISSUE TITLE
The formulas are not shown normally in the 《REINFORCEMENT LEARNING (DQN) TUTORIAL》

### ISSUE THREAD

**Issue by songyuc** [pytorch/tutorials#1012]
Hi guys,
I am a learner of Reinforcement Learning (RL), and I find that the formulas are not shown normally in the https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html#dqn-algorithm.
Could you please help fix this?

You help will be appreciated!

**Comment by holly1238** [comment]
This issue is fixed and merged in https://github.com/pytorch/tutorials/pull/1362
