### ISSUE TITLE
math text size is too small

### ISSUE THREAD

**Issue by PradeepSinghMakwana** [pytorch/tutorials#1022]
![BlitzMathTooSmall](https://user-images.githubusercontent.com/20859781/84378673-2c37fc00-ac02-11ea-9cc6-80764e5ea082.png)  
I cannot easily read what's written in the equations. The Math is rendering very small on Blitz page.  
[Here](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html). How can I help correct this?

**Comment by PradeepSinghMakwana** [comment]
Same issue here [Here](https://github.com/pytorch/tutorials/issues/1012#issue-630436145), although different wordings.

**Comment by PradeepSinghMakwana** [comment]
I think [this](https://github.com/pytorch/pytorch_sphinx_theme/pull/35#issue-238856383) is not doing anything.

**Comment by PradeepSinghMakwana** [comment]
My question is why are we using [pytorch_sphinx_theme](https://github.com/shiftlab/pytorch_sphinx_theme/blob/master/js/mathjax.js) instead of [pytorch_sphinx_theme-1](https://github.com/shiftlab/pytorch_sphinx_theme-1/blob/00489836407a32f4e877858e67f6cb4b8db4e09e/js/mathjax.js). I mean we have already made some changes [there](https://github.com/shiftlab/pytorch_sphinx_theme-1/blob/00489836407a32f4e877858e67f6cb4b8db4e09e/js/mathjax.js), should we repeat all these changes in this and throw away the previous one.

**Comment by PradeepSinghMakwana** [comment]
I have made a pull request [here](https://github.com/shiftlab/pytorch_sphinx_theme/pull/64#issue-433068103)

**Comment by PradeepSinghMakwana** [comment]
I tried to make a change somewhere else, that did not succeed. Let's pray to god, someone does the good thing.

**Comment by adam-dziedzic** [comment]
I have exactly the same issue with these tutorials, for example, here: https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html Is there any way to increase the math font size globally?

**Comment by holly1238** [comment]
This issue is fixed and merged in https://github.com/pytorch/tutorials/pull/1362
