### ISSUE TITLE
Key error in Mask R-CNN tutorial

### ISSUE THREAD

**Issue by schnobi1990** [pytorch/tutorials#1028]
Hello everyone,

there is a small error in the Mask R-CNN tutorial:
https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html

In _2 - Modifying the model to add a different backbone_ you can find the line:
```
roi_pooler = torchvision.ops.MultiScaleRoIAlign(featmap_names=[0],
                                                output_size=7,
                                                sampling_ratio=2)
```

This needs to be:
```
roi_pooler = torchvision.ops.MultiScaleRoIAlign(featmap_names=["0"],
                                                output_size=7,
                                                sampling_ratio=2)
```

Otherwise the key won't be found in forward method of the "MultiScaleRoIAlign" class, line 183.

Cheers

**Comment by holly1238** [comment]
This issue is fixed and merged in https://github.com/pytorch/tutorials/pull/1085
