### ISSUE TITLE
questions about "CHATBOT TUTORIAL", some meaningless words at the end of the genertated sentences.

### ISSUE THREAD

**Issue by jobsfan** [pytorch/tutorials#1029]
n_iteration set to 8000, the results as follow:

D:\ProgramData\Anaconda3\envs\pytorch\python.exe "some/3evaluate_use.py"
Building encoder and decoder ...
Models built and ready to go!
> 不明白你说啥麻烦您老说明白点
Building prefix dict from the default dictionary ...
Loading model from cache some\jieba.cache
Loading model cost 0.777 seconds.
Prefix dict has been built successfully.
Bot: 这 都 你 也 太笨 了 点 吧 吧 哦 呀 说 啊 ？
> 你在干嘛
Bot: 除了 聊天 还是 聊天 聊天 呀 群主 呀 群主 呀
> 你是傻逼吗？
Bot: 任何 人工智能 都 敌不过 阁下 这 款 天然 傻瓜 傻 逼 ， 还怕 当回 傻 逼
> 卧槽
Bot: 大哥 ， 买斤 素质 填补 一下 你 猥琐 的 大脑 ！ 没法 ！ 打 他 的 ！
> 哈哈哈哈
Bot: 别笑 了 ， 露出 一嘴 的 黄牙 。 亲爱 的 。 骂 你 。
> 我喜欢你
Bot: 你 到底 喜欢 我 什么 ， 我 改 还 不成 吗 ？ 行 啊 ！ 上 了
> 我想你
Bot: 一定 要 多 想 哦 ， 除了 wc 以外 的 时间 都 要 想 我 哦 ！
> 我们一起私奔吧
Bot: 你 吵 不过 我 的 ！ 呢 哟 哟 。 亲爱 的 。 今天
> 拜拜
Bot: 嗯 啊 ， 再见 ， 我会 想 你 的 。 亲爱 的 ！
> 你喜欢我吗
Bot: 很 喜欢 很 喜欢 啦 滴 事情 事情 事情 事情 事情 事情
> 你喜欢我吗？
Bot: 很 喜欢 很 喜欢 啦 滴 ！ 猪猪 ！ 打 ！ 打 ！ 打
> 你吃那么多
Bot: 是 啊 ， 好多 。 喜欢 。 喜欢 。 亲爱 的 。 。
> 你吃太多了
Bot: 是 啊 ， 好多 。 喜欢 。 亲爱 的 。 。 。 。
> 你长太胖了
Bot: 不要 緊 ， 有 我 ！ 看 ！ ！ 打 ！ 打 ！
> 你放屁
Bot: 你 才 放屁 呢 。 可能 大概 是 哥 。
> 你不是人
Bot: 是 啊 。 大方 3 。 可能 大概 是 屁股 ！ 打
> 你是真的傻
Bot: 你 才 傻 了 傻 逼 吖 。 亲爱 的
> 累不累
Bot: 累 啊 ， 累 得 够呛 的 说 呀 说 。 猥琐
> 约么？
Bot: 问 天问 地 ， 说 说 你 ， 说 说 我 ， 我 就 说 嘛
> 你太可爱了
Bot: 嘻嘻 ， 你 也 很 可爱 的 说 啊 。 亲爱 的
> 大长腿
Error: Encountered unknown word.
> 好漂亮
Bot: 对 啊 ， 对 啊 ， 我 爱 美女 ， 美女 爱 我 ！ 爱 你 ！
> 你出去
Bot: 我会 给 你 安全 么 3 。 棒 。
> 滚
Bot: 该 滚 的 是 网友 吧 的 说 ， 现在 是 在 表扬 你 一斤
> 

The words marked in the red square are meaningless words.

![1111](https://user-images.githubusercontent.com/3395025/84722935-0f5f4800-afb7-11ea-97db-c2b9bdfeec74.png)

In such situation, why this happened, and how to improve this?

The average loss from 9.6302 to 0.3282
![2222](https://user-images.githubusercontent.com/3395025/84722941-1423fc00-afb7-11ea-9945-a39011cb12c0.png)

......

![333](https://user-images.githubusercontent.com/3395025/84722944-18e8b000-afb7-11ea-9eb4-29f042cc157a.png)

 Any big guns can do me a favor, thank you!

**Comment by lewha0** [comment]
Basically, the decoder generates the next word by choosing the most likely one, until an end-of-sentence token is generated. In your case, the words seem to be meaningless were just more probable than to end the sentence at that time. Maybe if you use a larger dataset which includes the sentences end without meaningless part, then it would improve your results.

**Comment by jobsfan** [comment]
@lewha0 
Thank you so much for your kind reply!

In your opinion It is most likely that my corpus with low quality? I think so.

However my corpus are our company resource, It is not possible to get it bigger.
So I guess maybe it is a solution if I iterate more times, what do you think?

**Comment by carljparker** [comment]
This issue appears to be resolved. @jobsfan if you'd like to continue the conversation, you can re-open or use the forums.
