### ISSUE TITLE
A PR to fix typos failed build/deploy (#1001)

### ISSUE THREAD

**Issue by lewha0** [pytorch/tutorials#1033]
I corrected some typos in chatbot_tutorial.py and opened a pull request #1001 .
Only texts written in a comment of a .py file were modified, but I got build fail.
Is there any guideline to cope with such case?
I don't know why but some PR like #1017, which just corrects a typo, was successfully built.

**Comment by holly1238** [comment]
Not sure what happened in this case since the PR was created a while ago, but the build was re-ran, passed tests, and merged.
