### ISSUE TITLE
Simplify numpy function call in object detection tutorial

### ISSUE THREAD

**Issue by ashok-arjun** [pytorch/tutorials#1038]
In the second code block in the tutorial, the line `pos = np.where(masks[i])` has been used to get the indices of the non zero points in the image. But [numpy documentation for `np.where()`](https://numpy.org/doc/1.18/reference/generated/numpy.where.html) advises to use [`np.nonzero()`](https://numpy.org/doc/1.18/reference/generated/numpy.nonzero.html) when there is only one argument for `np.where()`, and it also makes the code more readable.

**Comment by moDallel** [comment]
Hello !
We are a group of students in second year in engineering school. We are currently interested in resolving this issue as a school project. Please let me know, if we can have your permision to contribute on this issue.

**Comment by JoseLuisC99** [comment]
I consider that #2372 resolves this issue.

**Comment by sekyondaMeta** [comment]
Closing this issue as it is resolved by PR #2372
