### ISSUE TITLE
I found a mistake in an official case

### ISSUE THREAD

**Issue by itmorn** [pytorch/tutorials#1052]
https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial
In this link, an RNN network is specified, and I think there is something wrong with its structure. This existing structure cannot collect hidden layer information for the last character. So I think the network should be modified to the structure shown below.
![image](https://user-images.githubusercontent.com/32835189/86512673-b442a780-be36-11ea-8698-ca2b135f87cf.png)
The modified network is shown below:
![image](https://user-images.githubusercontent.com/32835189/86512690-dccaa180-be36-11ea-8af2-14b53c7be9f3.png)

**Comment by BeniaminC** [comment]
\assigntome

**Comment by BeniaminC** [comment]
Duplicate issue: https://github.com/pytorch/tutorials/issues/193
