### ISSUE TITLE
Image not found in Neural Transfer with PyTorch webpage

### ISSUE THREAD

**Issue by tschoy** [pytorch/tutorials#108]
In webpage:

http://pytorch.org/tutorials/advanced/neural_style_tutorial.html

The links of this image got a 404 not found error:

http://pytorch.org/_static/img/neural-style/picasso.jpg
http://pytorch.org/_static/img/neural-style/dancing.jpg

**Comment by chsasank** [comment]
Thanks, I'll fix that. You can use images from here meanwhile: https://github.com/pytorch/tutorials/tree/master/_static/img/neural-style

**Comment by tschoy** [comment]
Thanks for reply. These days it's easy to just google search for that
image. :)

Neat tutorial by the way!

Alex

**Comment by lynic** [comment]
If you go through the code, it will tells you how to download the images https://github.com/pytorch/tutorials/blob/master/advanced_source/neural_style_tutorial.py#L180-L183
