### ISSUE TITLE
torchtext.data.Field parameters not correct in transformer_tutorial

### ISSUE THREAD

**Issue by manjitullal** [pytorch/tutorials#1095]
https://pytorch.org/tutorials/beginner/transformer_tutorial.html

in the above tutorial 

currently the parameters are 

TEXT = torchtext.data.Field(tokenize=get_tokenizer("basic_english"),
                            init_token='<sos>',
                            eos_token='<eos>',
                            lower=True)

i think it should be 

TEXT = torchtext.data.Field(tokenize="spacy",
                            init_token='<sos>',
                            eos_token='<eos>',
                            lower=True)

the current parameters give below error 

ValueError: Requested tokenizer basic_english, valid choices are a callable that takes a single string as input, "revtok" for the revtok reversible tokenizer, "subword" for the revtok caps-aware tokenizer, "spacy" for the SpaCy English tokenizer, or "moses" for the NLTK port of the Moses tokenization script.

**Comment by mariosasko** [comment]
I ran the first definition and it works perfectly fine. After checking the source code of the `get_tokenizer` function, it seems that the error you mention is not possible for the combination of parameters in the snippet. This error is raised when the first argument of `get_tokenizer` is not supported, but `basic_english` is a valid tokenizer. Make sure you didn't misspell "basic_english". Additionally, you can update `torchtext` to the newest version (in version 0.6.0, it works fine).
