### ISSUE TITLE
beta and prototype tutorials are listed first in C++ frontend

### ISSUE THREAD

**Issue by gchanan** [pytorch/tutorials#1103]
This is the current order I see on the sidebar:
```
(prototype) Introduction to Named Tensors in PyTorch
(beta) Channels Last Memory Format in PyTorch
Using the PyTorch C++ Frontend
Custom C++ and CUDA Extensions
Extending TorchScript with Custom C++ Operators
Extending TorchScript with Custom C++ Classes
Dynamic Parallelism in TorchScript
Autograd in C++ Frontend
Dispatcher in C++
```

we should reorder in a sensible way; moving the beta one second-to-last and the prototype-one last would be a good start.

**Comment by brianjo** [comment]
Noted @gchanan. I'll put this on my list. Thanks!

**Comment by holly1238** [comment]
Closing this as the left nav has been completely reworked in the past year. Please reopen if you believe that this is not resolved!
