### ISSUE TITLE
Optimize Tutorial Build with Docker Images

### ISSUE THREAD

**Issue by brianjo** [pytorch/tutorials#1108]
Tutorials currently runs the entire build from scratch multiple times for every PR merge. 
Persisting a docker image after the tutorial build will allow us to do incremental builds on tutorials. 
@seemethere and I met to discuss updating the build with this in mind and we think it's possible to persist the output of the build and do these incrementally.
We'll try to get this going over the next couple of weeks.

**Comment by malfet** [comment]
I wonder if we can re-use sccache for tutorial builds?

**Comment by brianjo** [comment]
Hey all, @v-jizhang is going to take a look at this. He's most recently worked on the Buck Circle CI builds. Thanks!

**Comment by v-jizhang** [comment]
@brianjo I'll take a look, thank you!

**Comment by v-jizhang** [comment]
I think we can utilize one of the CircleCI’s caching mechanisms [DLC, Docker Layer Caching.](https://circleci.com/docs/2.0/docker-layer-caching/) What we need to do is to change the current steps into docker building steps(in file Dockerfile) based on the existing docker image (tag 291). By turning on DLC in config.yml, CircleCI will cache the layers(steps) automatically for us.

**Comment by v-jizhang** [comment]
DLC has a 50G disk space limit, not enough for us. We have to save docker images somewhere else.
We can build 20 images and each image includes a list of tutorial files (the same as FILES_TO_RUN in build.sh) that built into it.
When a PR comes in, if

- There are new files or non-tutorial file changes, build everything from beginning and save the new images, 20 in total. This should not happen very often.
- Only tutorial file changes, rebuild these images that include the changed files and save the new images. For all other images, run step 5 (Copy generated files to S3, tag with commit ID) in build.sh only.

**Comment by holly1238** [comment]
This issue was addressed by https://github.com/pytorch/tutorials/pull/1184
