### ISSUE TITLE
Recipes should be more discoverable 

### ISSUE THREAD

**Issue by gottbrath** [pytorch/tutorials#1109]
Per our internal discussion on performance documentation   "the profiling tutorial doesn't have an entry in the tutorials list on the LHS." - Greg Chanan

We should look at overall discoverability of the recipes to make sure that it is as good or better than the long form tutorials now that we have a good number of them.

**Comment by holly1238** [comment]
I don't think this issue is relevant anymore now that we have a separate landing page for recipes (https://pytorch.org/tutorials/recipes/recipes_index.html), but please reopen if there's more work to be done on this!
