### ISSUE TITLE
How to Inference non-val images in Transfer Learning Tutorial

### ISSUE THREAD

**Issue by ScottMoffatLittle** [pytorch/tutorials#1110]
The transfer learning tutorial is great, however it leaves off after evaluating the accuracy of the model. My goal is to then use the model that has been created to inference other images, but have run into trouble getting the new data adhere to the correct format and shape. Do you have any insight on how I could do this?

**Comment by HemanthSai7** [comment]
@svekars Can I use an external image link to use an image in the PR? Please guide me on how to resolve the failed build.
