### ISSUE TITLE
Tutorial NN Potential Error

### ISSUE THREAD

**Issue by aaronWool** [pytorch/tutorials#1119]
With the NN structure image provided in the following page:
https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html
The convolutional layer kernel size should be 5 * 5 & The full connection layer F5 should be 16*5*5.

With the code provided, the NN structure should be:
input 32 * 32
C1 6@30 * 30 (kernel size 3*3)
S2 6@15 * 15
C3 16@13 * 13
S4  16@6 * 6
F5 120
F6 84
OUTPUT 10

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1257
