### ISSUE TITLE
Errors with outdated with creator and previous_function in tutorial

### ISSUE THREAD

**Issue by mackiem** [pytorch/tutorials#112]
There's an error with the release docker version of pytorch, and the tutorial. The problem is that the tutorial displayed here is not in sync. I assume what's pulled when building the docker image is the latest release version.

The fix is to the following replacements:
s/creator/grad_fn/g 
s/previous_function/next_function/g

```
Traceback (most recent call last):
  File "neural_networks_tutorial.py", line 184, in <module>
    print(loss.creator)  # MSELoss
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/autograd/variable.py", line 64, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'creator'
```

**Comment by chsasank** [comment]
Check out this issue and issues linked within: https://github.com/pytorch/tutorials/issues/98

tutorials webpage not tracking master is intentional. Please download tutorial python files from master branch of this repo to have updated versions.

**Comment by mackiem** [comment]
So, the docker build is pulling from master? Isn't that inconsistent then?

**Comment by mackiem** [comment]
I'm trying to understand the proper fix here. I built the dockerfile using the master. So, is that what caused the problem?

I think in any case the tutorial online should mention the fix at least. I had to poke around for a few mins to figure out the fixes. It may not be obvious to others.

**Comment by chsasank** [comment]
I agree that this does cause confusion. 

But earlier, tutorials used to track master and that caused even more confusion. Solution was to add a revert commit to a new branch and build from this branch.

I think solution to the whole confusion is just mention pytorch version somewhere.

**Comment by mackiem** [comment]
I guess this is a problem of APIs being changed rapidly (which is not a bad thing for a rapidly changing code base). The branch version should've added a Note with the fixed. But since it is already released, the only solution maybe to just hope people come across the issues created.
