### ISSUE TITLE
win_test_worker builds fail after 3+ hours for the last 20 days

### ISSUE THREAD

**Issue by malfet** [pytorch/tutorials#1141]
See https://app.circleci.com/pipelines/github/pytorch/tutorials/2301/workflows/29041f84-758e-42c9-8293-f15210821b40/jobs/39809 as an example
And see the whole timeline here: https://app.circleci.com/pipelines/github/pytorch/tutorials?branch=master

**Comment by brianjo** [comment]
I'm going to close this for now. Thanks for fixing @malfet
