### ISSUE TITLE
Detection tutorial MultiScaleRoIAlign featmap_names error

### ISSUE THREAD

**Issue by yonigottesman** [pytorch/tutorials#1170]
When using a backbone that returns a tensor an OrderedDict with key '0' is created (string not int).
So when creating a MultiScaleRoIAlign the featmap_names should be a string '0'.

fixed here https://github.com/pytorch/tutorials/pull/1169

**Comment by holly1238** [comment]
Closing this issue. This was fixed and merged in https://github.com/pytorch/tutorials/pull/1085.
