### ISSUE TITLE
errors in pycharm website tutorials:'Deep Learning with PyTorch: A 60 Minute Blitz'

### ISSUE THREAD

**Issue by ComingPeopleHW** [pytorch/tutorials#1186]
`self.conv1 = nn.Conv2d(1, 6, 3)`
`self.conv2 = nn.Conv2d(6, 16, 3)`
the code was used for create a LeNet in 'Deep Learning with PyTorch: A 60 Minute Blitz' tutorials
but the correct kernel size in nn.Conv2d should be 5*5.

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1257
