### ISSUE TITLE
errors in image of tutorials/_static/img/mnist.png

### ISSUE THREAD

**Issue by jinhopark8345** [pytorch/tutorials#1194]
Since the kernel size of the first and second conv net is 3x3, the feature map's demension should be 6@30x30 and 16@13x13

C1: feature maps 6@28x28 -> C1: feature maps 6@30x30
C2: feature maps 6@10x10 -> C2: feature maps 6@13x13

or just simply use conv net with 5x5 kernel size :)

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1257.
