### ISSUE TITLE
CUDA extension tutorial is not compatible with distributed data parallel

### ISSUE THREAD

**Issue by KiddoZhu** [pytorch/tutorials#1196]
In the [CUDA extension tutorial](https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_extension.rst#writing-a-mixed-ccuda-extension), there is no explicit specification of the device, and the launch of CUDA kernel is always on the 0 GPU.

This is not desired for data parallel, and even causes illegal memory access for distributed data parallel, with the negative effect detected only after a lot of calls. I found this problem very hard to debug for CUDA beginners, and therefore suggest an improvement of this tutorial.

I can give a pull request if needed.

**Comment by KiddoZhu** [comment]
Also mentioned in #1133

**Comment by elephaint** [comment]
I wanted to add that if you have different generations of GPUs, the fix proposed in #1133 does not work if you compile the CUDA extension according to the tutorial. To get the custom kernel to work on other devices other than device 0 from different GPU generations, additional compilation flags need to be set to instruct nvcc to compile for other architectures. For example, in my case I needed to compile for both RTX2080Ti (Turing, device 0) and GTX1080ti (Pascal, device 1 & 2). Hence, the adjustment required in the setup.py would look like:

```
setup(name='extension',
      ext_modules=[
	CUDAExtension(name='extension_cuda', 
		sources = ['extension.cpp', 'extension_kernel.cu'],
            extra_compile_args={'cxx':['-g'],
                  'nvcc':['-gencode=arch=compute_60,code=sm_60',
                        '-gencode=arch=compute_75,code=sm_75']}
            )
      ],
      cmdclass={'build_ext': BuildExtension})
```
where the [nVidia docs](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html) provide the required codes for all the GPU architectures.

**Comment by ClementPinard** [comment]
@elephaint, see https://github.com/pytorch/pytorch/pull/48891 , should be available on master very soon.

**Comment by stas00** [comment]
just rebuild with `TORCH_CUDA_ARCH_LIST="60 75+PTX"` no need to wait for master updates - this override has been available all along.
