### ISSUE TITLE
Problem in advanced NLP tutorial

### ISSUE THREAD

**Issue by fsonntag** [pytorch/tutorials#120]
@ZhixiuYe pointed out a problem in the Viterbi Decoder in the original repository:
https://github.com/rguthrie3/DeepLearningForNLPInPytorch/issues/8

Him and me proposed some possible fixes. What do you guys think about that?

**Comment by chsasank** [comment]
Hey @fsonntag, I see that original issue was fixed. It'd be nice if you can push that fix here too.
