### ISSUE TITLE
Yolov5 quantization : problem with FloatFunctional()

### ISSUE THREAD

**Issue by bingiflash** [pytorch/tutorials#1227]
I'm trying quantize [Yolov5 (object detection)](https://github.com/ultralytics/yolov5). And i'm following [this tutorial](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html) to do static quantization. As per tutorial I'm changing all torch.add s to torch.nn.quantized.FloatFunctional() like this.

`return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))` to 
`return torch.nn.quantized.FloatFunctional().add(x , self.cv2(self.cv1(x))) if self.add else self.cv2(self.cv1(x))`

when the model is calibrating it's working fine. But when it comes to evaluating the quantized model, I'm getting this error.
`RuntimeError: Could not run 'aten::add.Tensor' with arguments from the 'QuantizedCPU' backend. 'aten::add.Tensor' is only available for these backends: [CPU, CUDA, MkldnnCPU, SparseCPU, SparseCUDA, Met 'aten::add.Tensor' is only available for these backends: [CPU, CUDA, MkldnnCPU, SparseCPU, SparseCUDA, Meta, Named, Autograd, Profiler, Tracer].`

Now I changed FloatFunctional() to Qfunctional() hoping to get a result, then I got an error during the calibration stage.

Can someone help me? Thanks in advance.

cc @jerryzh168 @jianyuh

**Comment by svekars** [comment]
This was submitted some time ago and probably no longer relevant. If you have more questions, can you please post to https://dev-discuss.pytorch.org.
