### ISSUE TITLE
Link for Makefile lines in static quantization tutorial is incorrect

### ISSUE THREAD

**Issue by gchanan** [pytorch/tutorials#1228]
https://github.com/pytorch/tutorials/blame/12cecd11660a6c8dcfee5d03cdd23a9ae79fcded/advanced_source/static_quantization_tutorial.py#L334-L335

This doesn't point to the imagenet_1k instructions anymore.

**Comment by holly1238** [comment]
These links no longer exist in the current version of the tutorial.
