### ISSUE TITLE
Static quantization tutorial missing a step

### ISSUE THREAD

**Issue by rfejgin** [pytorch/tutorials#1235]
https://github.com/pytorch/tutorials/blob/7bd031519bf072b2b69725aaa4adb3fc76b1660a/advanced_source/static_quantization_tutorial.py#L514

If I understand correctly, one needs to also set
`torch.backends.quantized.engine = "fbgemm"`

I tried to quantize a model without the missing step and got strange errors about certain operations not being supported on the FBGEMM backend. They go away with this step added.

cc @jerryzh168 @jianyuh @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by svekars** [comment]
Can you please close one of the PRs for this issue?

**Comment by Samsonboadi** [comment]
Done

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.

**Comment by svekars** [comment]
You can still add to the .rst file but with the updated backend, like ``torch.backend.quantized.engine = 'x86'``

**Comment by krishnakalyan3** [comment]
@svekars this change has already been made to the rst
https://github.com/pytorch/tutorials/blob/main/advanced_source/static_quantization_tutorial.rst?plain=1#L462
