### ISSUE TITLE
Menu item name showing as  "SyntaxError"  under Audio side menu in Tutorials Main page

### ISSUE THREAD

**Issue by bhargavkathivarapu** [pytorch/tutorials#1236]
In  https://pytorch.org/tutorials/ there is issue under Audio side menu . 
The name of menu item is displayed as "SyntaxError" instead of original name "Speech Command Recognition with torchaudio"
The link for that menu item is working fine . It renders the menu item name correct only after clicking on "SyntaxError" link

cc : @vincentqb 

<img width="577" alt="Screenshot 2020-11-13 at 6 35 43 PM" src="https://user-images.githubusercontent.com/12258823/99075545-a9b3ce00-25df-11eb-945c-8d4a00586376.png">

**Comment by vincentqb** [comment]
cc @brianjo for this issue

**Comment by holly1238** [comment]
Closing this issue. I checked the current tutorial page and the Speech Command Recognition with torchaudio link is rendering without issue.

![image](https://user-images.githubusercontent.com/77758406/116151147-1952dc80-a699-11eb-873b-85c22117cb58.png)
