### ISSUE TITLE
"Audio I/O and Pre-Processing with torchaudio" tutorial seems to refer to itself

### ISSUE THREAD

**Issue by forest1988** [pytorch/tutorials#1242]
I'm a beginner of `torchaudio` and while reading the tutorial I found something strange.

In "Audio I/O and Pre-Processing with torchaudio" tutorial ( https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html ),
it says that "Please visit Audio I/O and Pre-Processing with torchaudio to learn more", and the link in the URL seems to point to this URL itself.
Is this the intended setting?

I'm sorry if I misunderstand the intention.

**Comment by holly1238** [comment]
I checked the current tutorial and this is no longer an issue (the link has been removed).

**Comment by forest1988** [comment]
Thank you for checking and confirming that this is no longer an issue.
