### ISSUE TITLE
Training with batch size > 1 for adverserial example generation

### ISSUE THREAD

**Issue by chinmay5** [pytorch/tutorials#1247]
The tutorial notebook on [Adverserial Training](https://github.com/pytorch/tutorials/blob/master/beginner_source/fgsm_tutorial.py) uses a batch size of 1. What code changes are needed if we want to train on a batch size of say 16. My understanding is, we only need to change the logic of 
       `final_pred = output.max(1, keepdim=True)[1] # get the index of the max log-probability`
       ` # Now we have batch size > 1`
       `final_pred.squeeze_()`
        `indexes = final_pred == target`
       `correct += torch.sum(indexes).item()`

Is there something else needed. With this code change, I get values that are very similar to the case of batch_size=1 although not the same values. Any help would be appreciated.

**Comment by svekars** [comment]
This filed quite some time ago, so I'm going to assume that the author find answer or this is no longer needed. If you have more questions, please post on https://dev-discuss.pytorch.org/ where you can get help much faster.
