### ISSUE TITLE
Reinforcement_q_learning Notebook Does Not work in Colab

### ISSUE THREAD

**Issue by Tylersuard** [pytorch/tutorials#1253]
Hello.  Please take down the "open in colab" link.  This notebook is not compatible with Colab, and gives the following error when I try to run it:

NoSuchDisplayException                    Traceback (most recent call last)

<ipython-input-6-5bb6791e791e> in <module>()
     37 env.reset()
     38 plt.figure()
---> 39 plt.imshow(get_screen().cpu().squeeze(0).permute(1, 2, 0).numpy(),
     40            interpolation='none')
     41 plt.title('Example extracted screen')

9 frames

/usr/local/lib/python3.6/dist-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
    121         self._display = xlib.XOpenDisplay(name)
    122         if not self._display:
--> 123             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
    124 
    125         screen_count = xlib.XScreenCount(self._display)

NoSuchDisplayException: Cannot connect to "None"

cc @vmoens @nairbv

**Comment by svekars** [comment]
I believe this tutorial was fixed and is working as expected. Closing.
