### ISSUE TITLE
Error : 'module' object is not callable ;  Code : images,labels = dataiter.next()

### ISSUE THREAD

**Issue by vishnubalaji** [pytorch/tutorials#1259]
Getting the callable error when I try to execute the images,labels = dataiter.next() on Google colab

**Comment by holly1238** [comment]
Hi! Can you provide more information about this error? What tutorial/line(s) of code?

**Comment by vishnubalaji** [comment]
Hello @holly1238 ! I opened this issue a year ago and completely lost track of it. I must have faced this issue when I tried to run the code corresponding to the chapter "Training a Classifier" under "Learning PyTorch". Anyways, I am pretty confident that this must have been an error from my side, so I am closing this issue for now.
