### ISSUE TITLE
MNIST digit dataset can't be found 

### ISSUE THREAD

**Issue by henrikh** [pytorch/tutorials#1262]
In https://github.com/pytorch/tutorials/blob/master/beginner_source/nn_tutorial.py there is a reference to a MNIST dataset http://deeplearning.net/data/mnist/mnist.pkl.gz , but this website seems to be down.

**Comment by brianjo** [comment]
Thanks Henrik. I've uploaded the set to the repo to get past the problem for now. The tutorials should be working again.
