### ISSUE TITLE
builtins.AssertionError: Unresolvable type None

### ISSUE THREAD

**Issue by flytair** [pytorch/tutorials#1269]
hi,
when i run static_quantization_tutorial.py, it assert error at:
https://github.com/pytorch/tutorials/blob/ce58d5904c04c4be10561447e41a153f573a3f93/advanced_source/static_quantization_tutorial.py#L522
the error message is:
  assert base is not None, "Unresolvable type {}".format(expr[:i])
  builtins.AssertionError: Unresolvable type None

cc @jerryzh168 @jianyuh @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by svekars** [comment]
The .py file was replaced with the .rst file in the repo: https://github.com/pytorch/tutorials/blob/main/advanced_source/static_quantization_tutorial.rst. Please fix the issue in the .rst file rather than in the .py file. Please test locally that your solution works before submitting.

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are working on this issue, assign it to yourself and send a PR ASAP.
