### ISSUE TITLE
Slight error in the pictorial description on tutorial page

### ISSUE THREAD

**Issue by Adrg01** [pytorch/tutorials#1275]
This might not be a serious issue but I just realized that the values in the image on the pytorch tutorial page https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html are wrong. 

A 32x32 image would translate to a 30x30 given a 3x3 filler with stride = 1. The values are right in the code but not in the image.

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1257
