### ISSUE TITLE
cannot import name 'extract_archive', when run seq-to-seq model in the google colab.

### ISSUE THREAD

**Issue by funny000** [pytorch/tutorials#1277]
Why run Seq to Seq model example in the pytorch use google colab exists the problem? how to solution it?
The model example following :

import io
import torch
from torchtext.utils import download_from_url, extract_archive
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

url = 'https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip'
test_filepath, valid_filepath, train_filepath = extract_archive(download_from_url(url))
tokenizer = get_tokenizer('basic_english')
vocab = build_vocab_from_iterator(map(tokenizer,
                                      iter(io.open(train_filepath,
                                                   encoding="utf8"))))

def data_process(raw_text_iter):
  data = [torch.tensor([vocab[token] for token in tokenizer(item)],
                       dtype=torch.long) for item in raw_text_iter]
  return torch.cat(tuple(filter(lambda t: t.numel() > 0, data)))

train_data = data_process(iter(io.open(train_filepath, encoding="utf8")))
val_data = data_process(iter(io.open(valid_filepath, encoding="utf8")))
test_data = data_process(iter(io.open(test_filepath, encoding="utf8")))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

**Comment by funny000** [comment]
the src in the here:
https://pytorch.org/tutorials/beginner/transformer_tutorial.html

**Comment by funny000** [comment]
the error in the here:
ImportError                               Traceback (most recent call last)
<ipython-input-19-3a4fe6725f0e> in <module>()
      1 import io
      2 import torch
----> 3 from torchtext.utils import download_from_url, extract_archive
      4 from torchtext.data.utils import get_tokenizer
      5 from torchtext.vocab import build_vocab_from_iterator

ImportError: cannot import name 'extract_archive'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by funny000** [comment]
In the google colab, I have pip install torchtext, and show dependencies already exists.

**Comment by Aman-4-Real** [comment]
I have met the same problem and I used `!pip install --upgrade torchtext` in Colab which solved the problem.
