### ISSUE TITLE
New Tutorial : Add more Reinforcement Learning Tutorials 

### ISSUE THREAD

**Issue by ayushtues** [pytorch/tutorials#1280]
@jlin27  @brianjo  

Currently, there exists only one Reinforcement Learning tutorial on the official PyTorch tutorials page, i.e. the DQN tutorial. Considering the popularity of using PyTorch for RL, me and @hemilpanchiwala wanted to contribute to adding some more RL tutorials to the page. We are planning to start with adding some policy-gradient based approach like TRPO/DDPG and are willing to add more "standard" RL algorithms as well while keeping in mind to be as diverse as possible. 

cc @vmoens @nairbv

**Comment by vmoens** [comment]
This is a great idea!
We've provided a [PPO example](https://github.com/pytorch/tutorials/pull/2156) using [torchrl](https://github.com/pytorch/rl), so maybe TRPO would be a good idea.
Other possibilities are IQL or decision transformers, for which I see much interest for in the community.

**Comment by svekars** [comment]
Closing this issue, since we have published the PPO tutorial already.
