### ISSUE TITLE
Font size too small for tutorial equations 

### ISSUE THREAD

**Issue by quickgrid** [pytorch/tutorials#1282]
I am using chrome on windows 10. I have also checked on a cross browser testing site with Firefox and Chrome on windows 7. They both show similar small fonts shown like the first screenshot.

Font scale does not match the preview shown on this commit, https://github.com/pytorch/pytorch_sphinx_theme/pull/35 and the given preview link, https://5c1420f1f7907c558e51f188--shiftlab-pytorch-tutorials.netlify.app/beginner/blitz/autograd_tutorial.html#gradients.

### Screenshot

![Untitled](https://user-images.githubusercontent.com/1857293/102489271-71e4ee00-4097-11eb-9286-ffae87c9d7e8.png)

### My temporary solution

Currently I am using `font-size: 2em` or `font-size: 200%` on `.MathJax` class for each page load to make it readable.

![Untitled2](https://user-images.githubusercontent.com/1857293/102489282-76a9a200-4097-11eb-8dd5-7dcdbf0f61c7.png)

**Comment by holly1238** [comment]
We replaced MathJax with KaTeX in https://github.com/pytorch/tutorials/pull/1362 so the small font shouldn't be an issue anymore.
