### ISSUE TITLE
Inaccuracy in reference to creation of "random" input and output data

### ISSUE THREAD

**Issue by asfarley** [pytorch/tutorials#1296]
This page has a line with the comment: "Create random input and output data":

[https://pytorch.org/tutorials/beginner/pytorch_with_examples.html](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html)

```
# Create random input and output data
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)
```

It looks to me like the training input and output are not random at all.

**Comment by holly1238** [comment]
This is an older tutorial, our latest beginner content (Learn the Basics) can be found here: https://pytorch.org/tutorials/beginner/basics/intro.html
