### ISSUE TITLE
60 min start

### ISSUE THREAD

**Issue by LinpengPan** [pytorch/tutorials#1297]
![image](https://user-images.githubusercontent.com/55887622/103168128-8c735000-486b-11eb-988b-051b6d82748f.png)
![image](https://user-images.githubusercontent.com/55887622/103168137-972de500-486b-11eb-8d0a-be36089fb3f5.png)
The code doesn't match the network. This may mislead others.

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1257
