### ISSUE TITLE
Runtime Error: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor

### ISSUE THREAD

**Issue by bill2bill** [pytorch/tutorials#1300]
I've been following the chatbot tutorial (https://pytorch.org/tutorials/beginner/chatbot_tutorial.html#run-model) and discovered the code does not run out of the box for me. 

After training the model and inputting custom test data for the bot to respond I get the error:

`RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor`

I found a similar issue with a fix on the Pytorch Github issues, https://github.com/pytorch/pytorch/issues/43227

Their solution was to use the .cpu() on the length argument.

On line 683, of https://github.com/pytorch/tutorials/blob/master/beginner_source/chatbot_tutorial.py, I applied the .cpu() method to the variable input_sequence and that resolved my issue.

**Comment by chaojihuihui** [comment]
well

**Comment by krkv** [comment]
Ran into the same issue

**Comment by holly1238** [comment]
Closing this issue. This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1535
