### ISSUE TITLE
Incorrect network illustration

### ISSUE THREAD

**Issue by chenfucn** [pytorch/tutorials#1301]
beginner_source/blitz/neural_networks_tutorial.py

The picture showing an example conv net is inconsistent with the example network in the code below. Specifically, a 32x32 image after a 3x3 conv filter with no padding should output a 30x30 channel, not a 28x28 one.  After 2x2 max pool -> 15x15, another 3x3 conv -> 13x13,  2x2 max pool ->  6x6

**Comment by jimmy1411** [comment]
Only change required here is updating the kernel size of the conv layers from 3 to 5

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1257.
