### ISSUE TITLE
NLP FROM SCRATCH: TRANSLATION WITH A SEQUENCE TO SEQUENCE NETWORK AND ATTENTION

### ISSUE THREAD

**Issue by aloska** [pytorch/tutorials#1304]
Hi
I'm exgausted... how to save and load model in future?

**Comment by pskadasi** [comment]
please check this: https://discuss.pytorch.org/t/how-to-save-a-lstm-seq2seq-network-encoder-and-decoder-from-example-in-tutorials-section/56679/3
