### ISSUE TITLE
Inconsistent text and image in "Channels Last" tutorial

### ISSUE THREAD

**Issue by cipri-tom** [pytorch/tutorials#1355]
Hello,

I was looking at the [memory format tutorial](https://pytorch.org/tutorials/intermediate/memory_format_tutorial.html) and the text says the top two represent:
> two 2x2 images with 3 color channels

But to me, it seems that the images are 4x4 . Am I missing something ?

**Comment by holly1238** [comment]
Hi! You are correct, the images are 4x4. The tutorial text was fixed to reflect this in https://github.com/pytorch/tutorials/pull/1630.
