### ISSUE TITLE
The link to eagar mode static quantization tutorial is dead

### ISSUE THREAD

**Issue by masahi** [pytorch/tutorials#1365]
In https://pytorch.org/tutorials/prototype/fx_graph_mode_ptq_static.html, there are many references to https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html, but this link points to the tutorial home

@jerryzh168 

cc @svekars @carljparker

**Comment by jerryzh168** [comment]
Oh, https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html taken down because of some legal issues related to image net, I'll add that later

**Comment by masahi** [comment]
Also it seems https://s3.amazonaws.com/pytorch-tutorial-assets/imagenet_1k.zip is dead.

**Comment by svekars** [comment]
Seems like all links are working. Closing.
