### ISSUE TITLE
Train ResNet from scratch

### ISSUE THREAD

**Issue by timothyvanco** [pytorch/tutorials#1374]
Hi, thanks for tutorial for Transfer Learning with ResNet (https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html).
I would like to ask, if I want to train ResNet from scratch with my own dataset (could also be ants and bees as you used), is it enough to use your code in the tutorial (link mention above) and change this line from Pretrained = True, to false? Then the ResNet will train from scratch?

`model_ft = models.resnet18(pretrained=True) -> model_ft = models.resnet18(pretrained=False)`

**Comment by brianjo** [comment]
@chsasank Sasank, maybe you could comment on this? Thanks!

**Comment by chsasank** [comment]
Yes. that should work.
