### ISSUE TITLE
Updating readme.md

### ISSUE THREAD

**Issue by bhav09** [pytorch/tutorials#1411]
Hello Maintainers,

I am really happy to see such an enriching repo of Pytorch, all the contributors have done an un-explicable job! I am willing to contribute to it too. I have realised a few changes in readme can make the markdown even more appealing. 

The changes I want to propose:
1. Adding a contents section to markdown which would take the readers on a walk on all the topics.
2. Adding a section that would help navigate some really basic yet important tutorials of Pytorch. 

The reason I am proposing this to you is, despite being a really wonderful curation of Pytorch, the repo still can be overwhelming to a beginner who seeks knowledge. To make it easier for them, I wish to contribute to the above-mentioned areas. 

Please assign the issue to me. Thank you :)

**Comment by bhav09** [comment]
@brianjo sir, can you please assign this issue to me.

**Comment by bhav09** [comment]
@brianjo sir, can you please assign this issue to me.

**Comment by bhav09** [comment]
Thanks for assigning me, @holly1238 :)

**Comment by svekars** [comment]
We have recently update the README.md and CONTRIBUTING.md with should help new contributors to get started with PyTorch faster. Also, feel free to check out intro tutorials on our website: https://pytorch.org/tutorials/beginner/basics/intro.html. I hope this helps. Closing as this seems to be addressed.
