### ISSUE TITLE
Neural Style: Clamping image during optimization causes exploding gradient

### ISSUE THREAD

**Issue by cpdurham** [pytorch/tutorials#143]
Hey, I was playing with the Neural Style tutorial code and noticed that the losses would explode around iteration 750 on the default images. When I moved the image clamp out of the optimization, this exploding loss went away. I moved the clamp to imshow and ran for 3000 iterations with a nicely decreasing monotonic loss, but it finished with some (very) subtle visual artifacts. Just an fyi.

I can't for the life of me figure out how Justin Johnson's [code](https://github.com/jcjohnson/neural-style) handles the image range issue, thinking it might possibly have something to do with subtracting the imagenet mean image.

**Comment by pancho111203** [comment]
Did you find a solution? I'm having the same problem.

**Comment by chrrrisw** [comment]
Although it doesn't fix the exploding gradient entirely, better results are gained by using the layers from the original paper:

``` python
content_layers_default = ["conv_10"]
style_layers_default = ["conv_1", "conv_3", "conv_5", "conv_9", "conv_13"]
```
