### ISSUE TITLE
example code problem: 

### ISSUE THREAD

**Issue by EngrStudent** [pytorch/tutorials#1442]
In this code:    
https://github.com/pytorch/tutorials/blob/master/recipes_source/recipes/saving_and_loading_models_for_inference.py

lines 83, 84, 86, 87 all try to use "F.relu" which is undefined. 

I think you need the following in your imports:    
import torch.nn.functional as F

**Comment by krishnan-tech** [comment]
I think, we can use `nn.ReLU` instead of `F.relu`.

**Comment by brianjo** [comment]
Thanks for the fix Krishnan!
