### ISSUE TITLE
Profiling Tutorial still talks about old autograd profiler rather than torch.profile.profiler

### ISSUE THREAD

**Issue by HDCharles** [pytorch/tutorials#1451]
It seems like this (also the recipe) should be updated if the autograd profiler is considered legacy as mentioned [here](https://pytorch.org/docs/stable/profiler.html)

note: if you google search pytorch profiler, the first few results all point to autograd without any mention that its legacy or where to find the current recommended profiler.

**Comment by gdankel** [comment]
Has been addressed AFAIKT. Closing.
