### ISSUE TITLE
Broken link in tutorial 

### ISSUE THREAD

**Issue by krenerd** [pytorch/tutorials#1454]
In the[ Pytorch QUICKSTART tutorial](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) the link in the (full list here) button which is supposed to point the dataset catalog is broken. 

Current link: https://pytorch.org/docs/stable/torchvision/datasets.html
Correct link: https://pytorch.org/vision/stable/datasets.html

**Comment by sno6** [comment]
Fixed in https://github.com/pytorch/tutorials/pull/1466
