### ISSUE TITLE
Third part link for the text domain tutorials

### ISSUE THREAD

**Issue by zhangguanheng66** [pytorch/tutorials#1460]
The following three tutorials link the author's name (see "Author: Sean Robertson") to a third-party repo, which is not maintained anymore. Should we just remove those names in the tutorials?

https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html
https://pytorch.org/tutorials/intermediate/char_rnn_generation_tutorial.html
https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html

cc @svekars @carljparker @brianjo @cpuhrsch

**Comment by brianjo** [comment]
Yes thanks. I'll take care of it.

**Comment by svekars** [comment]
Needs to be updated to Author's profile: https://github.com/spro rather than the repo as it's pointing at the moment.
