### ISSUE TITLE
RuntimeError: [enforce fail at operator.cc:47] blob != nullptr. op Conv: Encountered a non-existing input blob: 1

### ISSUE THREAD

**Issue by DuinoDu** [pytorch/tutorials#149]
I'm running [super_resolution_with_caffe2.py](https://github.com/pytorch/tutorials/blob/master/advanced_source/super_resolution_with_caffe2.py), but met this error. I found that 
```
W = {graph.input[-1]: x.data.numpy()}
```
in [L148](https://github.com/pytorch/tutorials/blob/master/advanced_source/super_resolution_with_caffe2.py#L148) caused the error. In this network, there are 4 convolution layers, so it needs 8 params inputs(4 * 2(w, b)), plus an input of the network. So it need 9 inputs. In caffe2_pb file, I found that data input blob is "1". So I change this line to 
```
W = {graph.input[0]: x.data.numpy()}
```
It works well.
I wonder if that is ok. Thanks!

**Comment by soumith** [comment]
cc: @houseroad

**Comment by houseroad** [comment]
@DuinoDu ONNX just introduced some changes which breaks pytorch onnx exporter. I think your error may caused by these changes. We are fixing the exporter, and will get it working soon. If you want to quickly try ONNX, our docker image is another option. https://hub.docker.com/r/onnx/onnx-docker/tags/

**Comment by DuinoDu** [comment]
@houseroad I can run this tutorial and use ONNX already. Much thanks to those guys developing ONNX, a really useful tool~

**Comment by daniel-j-h** [comment]
@houseroad I'm still running into this problem with latest the PyTorch release (0.4.1) and the latest onnx release (1.2.2). Just want to let you know that this is still an issue.
