### ISSUE TITLE
Some code-blocks are missing because of reST syntax error

### ISSUE THREAD

**Issue by 9bow** [pytorch/tutorials#1496]
Hi,

While tidy up reStructuredText syntax for [translating tutorials into Korean](https://github.com/9bow/PyTorch-tutorials-kr), I found some `code-block`s are missing because of reST syntax error.

For example, [Extending dispatcher for a new backend in C++](https://pytorch.org/tutorials/advanced/extend_dispatcher.html) tutorial, [there's a code block](https://github.com/pytorch/tutorials/blame/master/advanced_source/extend_dispatcher.rst#L55) after [To create a Tensor on `PrivateUse1` backend, you need to set dispatch key in `TensorImpl` constructor.] sentence.

There're also other unintended hidden code-blocks. 

Here's a list I found:

| Tutorial | Source |
| -------- | ------- |
| [Extending dispatcher for a new backend in C++](https://pytorch.org/tutorials/advanced/extend_dispatcher.html)  |  [code-block after](https://github.com/pytorch/tutorials/blame/master/advanced_source/extend_dispatcher.rst#L55) `To create a Tensor on PrivateUse1 backend, you need to set dispatch key in TensorImpl constructor.` |
| [Making Native Android Application that uses PyTorch prebuilt libraries](https://pytorch.org/tutorials/recipes/android_native_app_with_custom_op.html) | [code-block after](https://github.com/pytorch/tutorials/blame/master/recipes_source/android_native_app_with_custom_op.rst#L707) `You should see logs with tag ‘PyTorchNativeApp’ that prints x, y, and the result of the model forward, which we print with log function in NativeApp/app/src/main/cpp/pytorch_nativeapp.cpp.` |
| [(prototype) FX Graph Mode Post Training Static Quantization](https://pytorch.org/tutorials/prototype/fx_graph_mode_ptq_static.html) | [code-block after](https://github.com/pytorch/tutorials/blame/master/prototype_source/fx_graph_mode_ptq_static.rst#L13) `The FX Graph Mode API looks like the following:` |
| [Hyperparameter tuning with Ray Tune](https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html) | [code-block after](https://github.com/pytorch/tutorials/blob/master/beginner_source/hyperparameter_tuning_tutorial.py#L434) `If you run the code, an example output could look like this:` |
| [Dynamic Parallelism in TorchScript](https://pytorch.org/tutorials/advanced/torch-script-parallelism.html) | [code-block after](https://github.com/pytorch/tutorials/blame/master/advanced_source/torch-script-parallelism.rst#L209) `Let’s use the profiler along with the Chrome trace export functionality to visualize the performance of our parallelized model:` | 
| [Extending TorchScript with Custom C++ Operators](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html) | [code-block after](https://github.com/pytorch/tutorials/blame/master/advanced_source/torch_script_custom_ops.rst#L608) `At this point, we should be able to build the application:`, [code-block after](https://github.com/pytorch/tutorials/blame/master/advanced_source/torch_script_custom_ops.rst#L648) `And run it without passing a model just yet:`, AND [code-block after](https://github.com/pytorch/tutorials/blame/master/advanced_source/torch_script_custom_ops.rst#L675) `If we then pass this serialized model to our C++ application, we can run it straight away:` |

I'd like to fix those tutorials and pull request about this.

**Comment by 9bow** [comment]
Below are sample screenshots to check changes on '[Extending TorchScript with Custom C++ Operators](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html)' tutorial: 

**AS-IS**
![image](https://user-images.githubusercontent.com/9343724/116787765-11ec6280-aae1-11eb-92bf-86a096af8e77.png)

**TO-BE**
![image](https://user-images.githubusercontent.com/9343724/116787743-dce01000-aae0-11eb-8c52-b1d63162a53d.png)
![image](https://user-images.githubusercontent.com/9343724/116787747-e49fb480-aae0-11eb-8a1f-945bd6d9fdef.png)

**Comment by holly1238** [comment]
Closing this PR. https://github.com/pytorch/tutorials/pull/1497 has been merged to fix the issue.
