### ISSUE TITLE
typo on Flask tutorial

### ISSUE THREAD

**Issue by 9bow** [pytorch/tutorials#1498]
There's a typo on [Deploying PyTorch in Python via a REST API with Flask](https://pytorch.org/tutorials/intermediate/flask_rest_api_tutorial.html) tutorial.

On `Dependencies` section, [torchvision version matching](https://github.com/pytorch/tutorials/blob/master/intermediate_source/flask_rest_api_tutorial.py#L49) should use `==` instead of `-`

This typo is found by @0xBono on the Korean tutorial translation repo (https://github.com/9bow/PyTorch-tutorials-kr/issues/198).

**Comment by holly1238** [comment]
Closing this issue. This was fixed in https://github.com/pytorch/tutorials/pull/1499
