### ISSUE TITLE
There is any fine tune tutorials?

### ISSUE THREAD

**Issue by Teaonly** [pytorch/tutorials#15]
Fine tune is very easy in Torch and Caffe, but I can't find how do fine tune in pytorch. Is there any fine tune examples or tutorials?

**Comment by apaszke** [comment]
You can find a note on that [in the autograd docs](http://pytorch.org/docs/notes/autograd.html) (read up to the volatile section). We'll be adding a proper tutorial soon.

**Comment by chsasank** [comment]
I've written transfer learning tutorial.

You'll find it here: http://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html

**Comment by Ashutosh1995** [comment]
Can finetuning be done on vgg 16 using pytorch

**Comment by chsasank** [comment]
You should be able to. Just modify the last fc layer.

**Comment by vra** [comment]
Hi @chsasank,
Do I need to add a `forward` function when adding extra layers to a network?

**Comment by chsasank** [comment]
Yes, you might need to modify the forward depending on the module.

**Comment by vra** [comment]
Hi @chsasank ,
Thanks for your quick response. When I read the tutorial at <http://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html>, In `ConvNet as fixed feature extractor` section, I found two lines:
```python
num_ftrs = model_conv.fc.in_features
model_conv.fc = nn.Linear(num_ftrs, 2)
```
a `fc` layer is added to the model but I did find modified forward function, I am confused. Could you please give me some hints on this? Thanks in advance.

**Comment by chsasank** [comment]
That's because layer has been 'modified'. New forward code will look
exactly like the old one because the modified fc layer takes same inputs as
before. So no need to change anything.

But for example, if you wanted conv layers or 2 fc layers instead of one fc
after resnet you will have to change forward code, probably by subclassing.

**Comment by vra** [comment]
OK I see, Thanks for your clear explanation, it's really helpful
