### ISSUE TITLE
Missing import torch in Transforms in Getting Started

### ISSUE THREAD

**Issue by a-ma-n** [pytorch/tutorials#1548]
There is a missing 
import torch in the Transforms module of Getting Started

<img width="1440" alt="Screenshot 2021-06-04 at 9 37 50 PM" src="https://user-images.githubusercontent.com/71551419/120881661-568f8000-c5f0-11eb-81a3-a6016bedce27.png">

Link:https://pytorch.org/tutorials/beginner/basics/transforms_tutorial.html

I can help fix this if permitted.

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1584
