### ISSUE TITLE
The command in "(PROTOTYPE) CONVERT MOBILENETV2 TO NNAPI" is invalid

### ISSUE THREAD

**Issue by ybai001** [pytorch/tutorials#1579]
For this tutorials (https://pytorch.org/tutorials/prototype/nnapi_mobilenetv2.html), the command in "Environment" section
`pip install --upgrade --pre --find-links https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html torch==1.8.0.dev20201106+cpu torchvision==0.9.0.dev20201107+cpu` is invalid.

Seems that this version is not in "https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html" any more. Could you update to another available version? Thanks.

ybai@ubuntu:~/CGRU_NRS$ pip install --upgrade --pre --find-links https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html torch==1.8.0.dev20201106+cpu torchvision==0.9.0.dev20201107+cpu
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
ERROR: Could not find a version that satisfies the requirement torch==1.8.0.dev20201106+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0.dev20210415+cpu, 1.9.0.dev20210416+cpu, 1.9.0.dev20210417+cpu, 1.9.0.dev20210419+cpu, 1.9.0.dev20210421+cpu, 1.9.0.dev20210422+cpu, 1.9.0.dev20210423+cpu, 1.9.0.dev20210424+cpu, 1.9.0.dev20210425+cpu, 1.9.0.dev20210426+cpu, 1.9.0.dev20210427+cpu, 1.9.0.dev20210428+cpu, 1.9.0.dev20210429+cpu, 1.9.0.dev20210430+cpu, 1.9.0.dev20210501+cpu, 1.9.0.dev20210502+cpu, 1.9.0.dev20210503+cpu, 1.9.0.dev20210504+cpu, 1.9.0.dev20210505+cpu, 1.9.0.dev20210506+cpu, 1.9.0.dev20210507+cpu, 1.9.0.dev20210508+cpu, 1.9.0.dev20210509+cpu, 1.9.0.dev20210510+cpu, 1.9.0.dev20210511+cpu, 1.9.0.dev20210512+cpu, 1.9.0.dev20210513+cpu, 1.9.0.dev20210514+cpu, 1.9.0.dev20210515+cpu, 1.9.0.dev20210516+cpu, 1.9.0.dev20210517+cpu, 1.9.0.dev20210518+cpu, 1.9.0.dev20210519+cpu, 1.9.0.dev20210520+cpu, 1.9.0.dev20210521+cpu, 1.9.0.dev20210522+cpu, 1.9.0.dev20210523+cpu, 1.9.0.dev20210524+cpu, 1.9.0.dev20210525+cpu, 1.9.0.dev20210526+cpu, 1.9.0.dev20210527+cpu, 1.9.0.dev20210528+cpu, 1.9.0.dev20210529+cpu, 1.9.0.dev20210530+cpu, 1.9.0.dev20210531+cpu, 1.9.0.dev20210601+cpu, 1.9.0.dev20210602+cpu, 1.9.0.dev20210603+cpu, 1.9.0.dev20210604+cpu, 1.10.0.dev20210605+cpu, 1.10.0.dev20210606+cpu, 1.10.0.dev20210607+cpu, 1.10.0.dev20210608+cpu, 1.10.0.dev20210609+cpu, 1.10.0.dev20210610+cpu, 1.10.0.dev20210611+cpu, 1.10.0.dev20210612+cpu, 1.10.0.dev20210613+cpu, 1.10.0.dev20210614+cpu, 1.10.0.dev20210615+cpu)
ERROR: No matching distribution found for torch==1.8.0.dev20201106+cpu

**Comment by spzala** [comment]
I was triaging this issue as part of the Docathon 2023, and it seems like the fix has already been applied. The `Environment` section as mentioned in the issue only shows `pip install torch==1.10.0 torchvision==0.11.1` We may want to close this issue cc @svekars @ybai001 Thanks!

**Comment by spzala** [comment]
Here is PR that provided the fix in the past - https://github.com/pytorch/tutorials/pull/1716

**Comment by sekyondaMeta** [comment]
Closing issue due to fix having been previously applied.
