### ISSUE TITLE
Update Flask and torchvision version on Flask tutorial

### ISSUE THREAD

**Issue by aditkumar72** [pytorch/tutorials#1604]
Current version of Flask and torchvision used is `1.0.3` and `0.3.0` respectively whereas the new version of Flask is `2.0.1` and of torchvision is `0.10.0`

**Comment by aditkumar72** [comment]
Can I work on this issue?

**Comment by holly1238** [comment]
This was updated in https://github.com/pytorch/tutorials/pull/1622. Thanks for the PR!!
