### ISSUE TITLE
Blank image in Mario-RL tutorial

### ISSUE THREAD

**Issue by MaxVanDijck** [pytorch/tutorials#1607]
There is a large whitespace due to a blank image in the mario-rl tutorial

![image](https://user-images.githubusercontent.com/50382570/125374976-4da68100-e3dc-11eb-8618-518d28f49988.png)

This image should be removed or replaced with the intended image.

cc @vmoens @nairbv @svekars @carljparker

**Comment by svekars** [comment]
still an issue. Link to tutorial: https://pytorch.org/tutorials/intermediate/mario_rl_tutorial.html?highlight=mario%20rl
