### ISSUE TITLE
rename translation_transformer tutorial to build with gallery

### ISSUE THREAD

**Issue by 9bow** [pytorch/tutorials#1612]
[beginner/translation_transformer](https://github.com/pytorch/tutorials/blob/master/beginner_source/translation_transformer.py) tutorial(#1564) is awesome but by [default setting in conf.py](https://github.com/pytorch/tutorials/blob/master/conf.py#L71) it does not build gallery.

how about renaming this tutorial from `translation_transformer.py` to `translation_transformer_tutorials.py` to build gallery?

**Comment by 9bow** [comment]
I renamed the tutorial file and it built the gallery successfully as follows:

![image](https://user-images.githubusercontent.com/9343724/126056122-1694cd8a-0cb3-4bc7-9669-616179af0518.png)

Is there any reason to keep this tutorial unbuilt? 
If not, I'll PR to fix this issue.

Please let me know. :)

**Comment by parmeet** [comment]
> I renamed the tutorial file and it built the gallery successfully as follows:
> 
> ![image](https://user-images.githubusercontent.com/9343724/126056122-1694cd8a-0cb3-4bc7-9669-616179af0518.png)
> 
> Is there any reason to keep this tutorial unbuilt?
> If not, I'll PR to fix this issue.
> 
> Please let me know. :)

Thanks for the catch @9bow . Please feel free to raise the PR.

**Comment by 9bow** [comment]
Thank you for the quick reply, @parmeet 
I'll make the PR soon. :)
