### ISSUE TITLE
Assign tags to docker images used to build tutorials

### ISSUE THREAD

**Issue by malfet** [pytorch/tutorials#1627]
So that they wouldn't get recycled, for example see https://app.circleci.com/pipelines/github/pytorch/tutorials/4825/workflows/7c4948de-3ff1-4f46-ad88-fa99aaa599d7/jobs/93556

**Comment by malfet** [comment]
https://github.com/pytorch/tutorials/pull/1626 temporarily (for at least next 30+ days) solves the issue

**Comment by seemethere** [comment]
Wouldn't it be better to just have tutorials build their own specific docker images?

**Comment by malfet** [comment]
Kind of a meta question: should any other projects depend on PyTorch docker images?

**Comment by seemethere** [comment]
> Kind of a meta question: should any other projects depend on PyTorch docker images?

I feel like the answer should be no, unless it's our nightly docker image

**Comment by malfet** [comment]
This is still the thing, see https://github.com/pytorch/tutorials/blob/0fd10e6c53346344c6c543f8f38b61c64d5aecb2/.circleci/config.yml#L125

**Comment by malfet** [comment]
Another idea: why not use pytorch images from[ docker hub](https://hub.docker.com/layers/pytorch/pytorch/pytorch/latest/images/sha256-9904a7e081eaca29e3ee46afac87f2879676dd3bf7b5e9b8450454d84e074ef0?context=explore)? (As they already have latest pytorch pre-installed)

**Comment by clee2000** [comment]
ended up going with the idea of "query for git hash" b/c there were issues w/ docker hub about jenkins
