### ISSUE TITLE
Visualizing the results from trained model

### ISSUE THREAD

**Issue by jspsiy** [pytorch/tutorials#1660]
I wanted to know how to test any images on the pre-trained model from this tutorial : https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html#putting-everything-together  

1) So given i maybe just have an image, how do i feed it to the model?
2) How exactly did you arrive to these results? (image shown below)
![image](https://user-images.githubusercontent.com/65582456/131035518-a9666522-c96b-4785-a291-cab0b2335810.png)

**Comment by silky1708** [comment]
You could do 
```
import PIL
# transform for the test image -> converts PIL image to a torch tensor
transforms = get_transform(train=False)
# load test image(assume 'image.png') using PIL
test_img = PIL.Image.open('image.png')
# convert image to tensor
img_tensor = transforms(test_img)
# inference
model.eval()
predictions = model(img_tensor)

```

**Comment by svekars** [comment]
It looks like the question was answered so closing for now. Feel free to reopen if needed
