### ISSUE TITLE
seq2seq with character encoding

### ISSUE THREAD

**Issue by manish-shukla01** [pytorch/tutorials#1662]
hi, i am hoping to build a seq2seq model with attention with character level encoding. idea is to build a model which can predict a correct name by handling all sort of spelling mistakes (qwerty keyboard error, double typing, omitting word etc.) . my test data will few example of mistyped words mapping to correct word. i am hoping i can mostly follow this https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html and just change the input and output tensors to contain the character tensors..similar to a tutorial which predicts country by looking at last name. ( i think first one in nlp series)..does this approach make sense? is there any other thing i need to consider or better model to consider.

cc @pytorch/team-text-core @Nayef211

**Comment by svekars** [comment]
Since it's been quite long since this question was posted, it's probably no longer relevant. Closing but feel free to reopen if this is still an issue.
