### ISSUE TITLE
UserWarning during Datasets & DataLoaders Tutorial

### ISSUE THREAD

**Issue by Jelle-Bijlsma** [pytorch/tutorials#1692]
Hi,

I am following the 'Introduction to PyTorch' tutorial. During [Datasets & DataLoaders](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html) I copied the following:

```import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)
```

Which led me to the following warning:

```/home/jelle/PycharmProjects/pytoch_learning/venv/lib/python3.9/site-packages/torchvision/datasets/mnist.py:498:
 UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means
  you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the
  array to protect its data or make it writeable before converting it to a tensor. This type of warning will be 
  suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
  ```

It seems this issue has been solved before? 
[47160](https://github.com/pytorch/pytorch/issues/47160)

I am using

- Python 3.9
- torch 1.9.1
- torchvision 0.10.1
- numpy 1.21.2
- Pycharm 2021.2
- Ubuntu 21.4

I installed using a virtual environment and the guide on https://pytorch.org/get-started/locally/
`pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html`

This warning was also given during the 'quickstart' tutorial. The warning seems to have no further effect on the tutorial.
Why is the warning not mentioned in the tutorial?

cc @suraj813

**Comment by Maddy12** [comment]
I am also getting an error when running:

`video = np.frombuffer(out, np.uint8).reshape([-1, self.size, self.size, 3])
        video = th.from_numpy(video)`

**Comment by medhini** [comment]
+1 

`video = th.from_numpy(video.copy())` fixes this issue but there shouldn't be a need to do this in the first place since from_numpy already creates a copy.

**Comment by ver2king** [comment]
Regarding this issue, 
I was unable to reproduce the issue using Conda Python 3.7 and Windows 10. How shall I proceed to "fix" the tutorial?

**Comment by svekars** [comment]
Thank you for reporting this. I think the original issue mentions Ubuntu as the OS. Any chance you can check on Ubuntu? Also, I'm confused by your PR. Why are you modifying `.gitignore` and other unrelated to the issue files?

**Comment by ver2king** [comment]
@svekars ,
I am proceeding to try for Ubuntu. For both Conda & pip in Windows, the code shall raise no issue. And I was unaware of the changes in the .gitignore 
In case those unexpected changes are not necessary, may you discard those changes then?

**Comment by ver2king** [comment]
@svekars,
Sorry for the confusion. I will submit another PR, then.

**Comment by NicolasHug** [comment]
@svekars I think the original issue was fixed upstream in torchvision already in https://github.com/pytorch/vision/pull/4598

There's no warning anymore from the code above (on any OS). I think the issue can be safely closed.

**Comment by svekars** [comment]
Thanks @ver2king for looking into this, we will grant half credit for this issue.

**Comment by ver2king** [comment]
@svekars Appreciate your grant. Tbh, I don't think this issue may need any serious fix.
