### ISSUE TITLE
FINETUNING TORCHVISION MODELS "View on GitHub" 404's

### ISSUE THREAD

**Issue by logankilpatrick** [pytorch/tutorials#1694]
cc @svekars @carljparker

**Comment by logankilpatrick** [comment]
Hey folks, on this page: https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html#finetuning-torchvision-models when I click: "View on GitHub" it 404's. I was trying to see the source file so I could open a different issue / PR to add an example for the pre-trained mobilenet and others.

**Comment by logankilpatrick** [comment]
Where is this file located so I can make that PR and how the "View on GitHub" link be fixed?

**Comment by nsbits** [comment]
> Where is this file located so I can make that PR and how the "View on GitHub" link be fixed?

its still not there. still 404 error

**Comment by svekars** [comment]
This tutorial has been reworked and moved [here](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html). Closing this issue.

**Comment by NeoKish** [comment]
@svekars I am not sure if there is any link to be corrected since the link mentioned (https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html#finetuning-torchvision-models ) doesn't exist and also it was for beginner source. The one mentioned in your comment is from intermediate one. Please if you could help on what needs to be done here.

**Comment by tcNickolas** [comment]
I think the fix (adding the redirect from the old tutorial to the new one) is the same as for #2097, and it should be up once the website deploys the updated version.

**Comment by romerocesar** [comment]
afaict this should be resolved right? https://github.com/pytorch/tutorials/pull/2378

**Comment by sekyondaMeta** [comment]
@svekars closing this issue as it looks like the redirect does not have this issue.
