### ISSUE TITLE
Is it possible to perform partial conversion of a pytorch model to ONNX?

### ISSUE THREAD

**Issue by ShiLevy** [pytorch/tutorials#1747]
I have the following VAE model in pytorch that I would like to convert to ONNX (and eventually to TensorFlow):
https://github.com/jlalvis/VAE_SGD/blob/master/VAE/autoencoder_in.py

I am only interested in the decoding part of the model. Is it possible to convert only the decoder to ONNX?

Thanks in advance :)

cc @BowenBao

**Comment by svekars** [comment]
@albanD maybe you know?

**Comment by albanD** [comment]
Hey!
You should be able to export any model you want with the exporter yes. Just pass in only the subset you're interested in.
For further questions, I would suggest you use the forum as more people will be able to help you there: https://discuss.pytorch.org/
