### ISSUE TITLE
The .train(False) or .eval() does not turn off the gradient computing

### ISSUE THREAD

**Issue by sonack** [pytorch/tutorials#1756]
https://github.com/pytorch/tutorials/blob/796013c10cde2cc8afb2e6f55acc26f12ca7ff2f/beginner_source/introyt/tensorboardyt_tutorial.py#L210
and
https://github.com/pytorch/tutorials/blob/796013c10cde2cc8afb2e6f55acc26f12ca7ff2f/beginner_source/introyt/tensorboardyt_tutorial.py#L216

The comments is wrong maybe?

cc @suraj813 @aaronenyeshi @chaekit @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen @robieta

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are working on this issue, assign it to yourself and send a PR ASAP.
