### ISSUE TITLE
Misleading call of 'iter' in the 'WrappedDataLoader'

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch/tutorials#1757]
https://github.com/pytorch/tutorials/blob/796013c10cde2cc8afb2e6f55acc26f12ca7ff2f/beginner_source/nn_tutorial.py#L776
There is no need to call `iter` in this line and that is misleading. Internally, by calling `iter` an `_BaseDataLoaderIter` instance is returned. Then in the `for` loop, again `iter` is called by the interpreter and the [same instance](https://github.com/pytorch/pytorch/blob/3202028ed1ca24c91dc7192ef69b305690db7abc/torch/utils/data/dataloader.py#L504) is returned. So there is no need to that call.

cc @suraj813

**Comment by HemanthSai7** [comment]
I have made the necessary changes as mentioned in the issues. I need some with the PR. Should I create a new branch and then create a PR or just do it directly in the main?

**Comment by HemanthSai7** [comment]
Whom do I tag in the PR?
