### ISSUE TITLE
[Help Wanted] Why take the log function and then apply exp?

### ISSUE THREAD

**Issue by Superhzf** [pytorch/tutorials#1778]
In [line of code](https://github.com/pytorch/tutorials/blob/master/beginner_source/transformer_tutorial.py#L113), you calculate positional encoding for Transformers by taking the log first and then apply the exponential function.

Would you please elaborate on why you do this instead of directly doing the calculation?

I'm aware that log transformation can make multiplication become addition, but it seems that this is not the case here.

cc @suraj813

**Comment by svekars** [comment]
@albanD can you respond to this?

**Comment by albanD** [comment]
Which log/exp are you talking about exactly?
If you mean this line https://github.com/pytorch/tutorials/blob/33492c7e8cc1da1de7d03f065b049c02dfc863d7/beginner_source/transformer_tutorial.py#L115 then I think this is just to make it easier when you multiply with the arange that has to be in the log space.

**Comment by QasimKhan5x** [comment]
Can we use -4.0 instead of `-math.log(10000.0)`? A comment above could say that the -4.0 is coming from `-math.log(10000.0)`

**Comment by YoushaaMurhij** [comment]
\assigntome

**Comment by HuangZurong** [comment]
@Superhzf explained in the blog https://medium.com/@hunter-j-phillips/positional-encoding-7a93db4109e6
