### ISSUE TITLE
[tutorials] 'ids_tensor' function is not exist in tutorial of 'DYNAMIC QUANTIZATION ON BERT'

### ISSUE THREAD

**Issue by jaehyeongAN** [pytorch/tutorials#1780]
In this [tutorials](https://pytorch.org/tutorials/intermediate/dynamic_quantization_bert_tutorial.html#serialize-the-quantized-model), `ids_tesnor` function is not exist. So following code needs to be added.
```python
import random 
global_rng = random.Random()

def ids_tensor(shape, vocab_size, rng=None, name=None):
    #  Creates a random int32 tensor of the shape within the vocab size
    if rng is None:
        rng = global_rng

    total_dims = 1
    for dim in shape:
        total_dims *= dim

    values = []
    for _ in range(total_dims):
        values.append(rng.randint(0, vocab_size - 1))

    return torch.tensor(data=values, dtype=torch.long, device='cpu').view(shape).contiguous()
```
The code referred to this [link](https://pytorch.org/tutorials/prototype/graph_mode_dynamic_bert_tutorial.html#quantizing-bert-model).

cc @jerryzh168 @z-a-f @vkuzo

**Comment by sekyondaMeta** [comment]
Closing this per merged PR
