### ISSUE TITLE
tutorials/advanced_source/super_resolution_with_onnxruntime.py is maybe outdated?

### ISSUE THREAD

**Issue by MaKaNu** [pytorch/tutorials#1781]
I am working at the moment trough the [tutorial](https://github.com/pytorch/tutorials/blob/master/advanced_source/super_resolution_with_onnxruntime.py) and realized, that the entry notes are not up-to-date. 

- line 19 says, onnx is available/compatible between 3.5 to 3.7:
    - I tested installation in a venv with 3.9 without problems
- line 21-22 says, says that the main/master branch is needed:
   - I tested the standard imports from line 26 to 32 and all imports worked without a problem.

I am running a ubuntu 20.04 with torch stable 1.10.1 installed via pip for cuda 10.2.

I did not finished the tutorial yet and will append further informations while continuing.

EDIT:
I can confirm: works without any issues

**Comment by kit1980** [comment]
Closing as fixed by https://github.com/pytorch/tutorials/pull/2370
