### ISSUE TITLE
Average loss in transfer learning tutorial calculated incorrectly

### ISSUE THREAD

**Issue by nelson-liu** [pytorch/tutorials#179]
Hi! Correct me if I'm wrong, but it seems like the average loss for the epoch is calculated incorrectly the transfer learning tutorial.

The criterions used are initialized with `size_average=True` (the default). In addition, the code computes `dataset_sizes` for `train` and `val` sets, which represent the # of samples in each set. After each batch, we accumulate the output of the criterion in a variable called `total_loss`, and then divide by the appropriate `dataset_sizes` value for the phase we're in. However, this `total_loss` is not actually the total loss for each example, but the total loss for each batch.

Since the criterion as currently instantiated is returning the *average loss over the examples in the batch*, we should divide that by `num_batches` in order to get a proper value for the average loss over the epoch. 

Alternatively, to account for the fact that batches can be different sizes, it'd probably be best to make the criterion return the *summed loss over the examples in the batch*, then dividing by the # of samples in the dataset like we're currently doing.

Let me know if I'm missing something here, or if this is indeed a bug --- happy to submit a PR to fix if necessary.

Thanks for the tutorial -- was very informative!

cc: @chsasank

**Comment by chsasank** [comment]
Sorry for really late reply. Was busy with something else.

Yep, you're right. That's indeed a bug. It'll be great if you can fix it. Thanks!
