### ISSUE TITLE
Old tutorials with broken layouts

### ISSUE THREAD

**Issue by mthrok** [pytorch/tutorials#1797]
https://github.com/pytorch/tutorials/pull/1265 moved `two_layer_net` tutorials 

I noticed that the old tutorials are still accessible and layout is broken.
They are the top results from Google search.
They should redirect to the new ones.

https://pytorch.org/tutorials/beginner/examples_nn/two_layer_net_nn.html
https://pytorch.org/tutorials/beginner/examples_nn/two_layer_net_module.html
https://pytorch.org/tutorials/beginner/examples_nn/two_layer_net_optim.html
https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_autograd.html
https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html
https://pytorch.org/tutorials/beginner/examples_autograd/tf_two_layer_net.html

cc @pytorch/team-audio-core

**Comment by svekars** [comment]
Marking as resolved
