### ISSUE TITLE
Missing 'img/teapot.jpg', 'img/trilobite.jpg' for `MODEL UNDERSTANDING WITH CAPTUM` tutorial.

### ISSUE THREAD

**Issue by MonkandMonkey** [pytorch/tutorials#1839]
Running this tutorial: https://pytorch.org/tutorials/beginner/introyt/captumyt.html
Could not found 'img/teapot.jpg', 'img/trilobite.jpg' under _static folder.

Could anyone help to provide?
Thanks!

**Comment by brianjo** [comment]
Hi @MonkandMonkey, that tutorial has a download associated with it that contains the file you need. https://pytorch-tutorial-assets.s3.amazonaws.com/youtube-series/video7.zip. Does that help?

**Comment by svekars** [comment]
Marking as resolved. Feel free to reopen if you have more questions.
