### ISSUE TITLE
ASR Inference tutorial not working

### ISSUE THREAD

**Issue by abhi-glitchhg** [pytorch/tutorials#1840]
[colab  notebook](https://colab.research.google.com/github/pytorch/audio/blob/gh-pages/main/_downloads/ade1a3c3b444796d2a34839c7ea75426/asr_inference_with_ctc_decoder_tutorial.ipynb#scrollTo=sJkOlyNIFMKj)

[Tutorial webpage](https://pytorch.org/audio/main/tutorials/asr_inference_with_ctc_decoder_tutorial.html) 

It seems like there is an issue with the tutorial here and needs to be updated. 
Error says - `ModuleNotFoundError: No module named ‘torchaudio.prototype`

It was brought to my notice by [this](https://discuss.pytorch.org/u/new_here/summary) user on PyTorch discussions.

**Comment by JonathanSum** [comment]
Related:
https://discuss.pytorch.org/t/lot-of-people-have-this-issue-porotype-still-does-not-load-after-installing-the-nightly-build/148595

**Comment by hwangjeff** [comment]
Thanks for flagging. This is due to Colab's using the release build, which doesn't include `torchaudio.prototype`, by default. https://github.com/pytorch/audio/pull/2325 updates the tutorial to clarify this and provide instructions for resolution.
