### ISSUE TITLE
Saving and Loading models tutorial needs revision

### ISSUE THREAD

**Issue by iandanforth-alation** [pytorch/tutorials#1846]
# Issues

1.  The tutorial model, if used, would raise errors due to missing `F`
2. The tutorial references an optimizer but never uses it.

## Issue 1 - Imports don't match usage

Imports

https://github.com/pytorch/tutorials/blob/master/recipes_source/recipes/saving_and_loading_models_for_inference.py#L59-L61

Used reference not previously imported (`F`)

https://github.com/pytorch/tutorials/blob/master/recipes_source/recipes/saving_and_loading_models_for_inference.py#L83

## Issue 2 - Created but unused optimizer

https://github.com/pytorch/tutorials/blob/master/recipes_source/recipes/saving_and_loading_models_for_inference.py#L95-L102

It is unclear why this section appears in the tutorial as it is unused and does not get saved or reloaded.

cc @suraj813

**Comment by dineshladi** [comment]
Hi, I am working on fixing this issue

**Comment by dineshladi** [comment]
@msaroufim, I have fixed the issue and raised a PR for the same at #1904.  Please have a look once

**Comment by svekars** [comment]
Closing as described here: https://github.com/pytorch/tutorials/pull/1904
