### ISSUE TITLE
MNIST tutorial error (wrong input size)

### ISSUE THREAD

**Issue by wunderox** [pytorch/tutorials#1849]
There seems to be an issue with the MNIST tutorial located here:
https://github.com/pytorch/tutorials/blob/master/beginner_source/blitz/neural_networks_tutorial.py

The issue is that the MNIST dataset is both displayed graphically and assumed to be 32x32, when in fact it's 28x28 (this was both verified on the website hosting the MNIST dataset here: `http://yann.lecun.com/exdb/mnist/` and in practice when downloading the MNIST dataset using the pytorch MNIST dataset handler).

This means that the network is unable to actually work when implemented as described in the code because of the following line:
`self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension ` where in fact it shouldn't be `16 * 5 * 5` but rather `16 * 4 * 4` (or the input image can be resized from 28x28 to 32x32 but that seems unnecessary).

cc @suraj813

**Comment by suraj813** [comment]
The MNIST dataset is indeed 28x28, but this tutorial is not specific to MNIST. MNIST is only referred to as an example to demonstrate that you will need to resize your inputs to 32x32 (regardless of the dataset being used).
