### ISSUE TITLE
Typo in data tutorial

### ISSUE THREAD

**Issue by dubey-anshuman** [pytorch/tutorials#1882]
The tutorial refers to "annotations_file" as the file which contains labels, except in one spot (see the following image)
 where it refers to the same file as "labels.csv"

![data_tutorial1](https://user-images.githubusercontent.com/19958712/162414042-18988703-a1df-4b66-8fb5-1ed148638b9f.png)
![data_tutorial2](https://user-images.githubusercontent.com/19958712/162414070-a22a2840-272f-4a1e-b888-43bccc13097a.png)

cc @svekars

**Comment by xiurobert** [comment]
Could you open a PR to fix this?

**Comment by suraj813** [comment]
There is no discrepancy here. `annotations_file` refers to the argument or variable used in the Dataset. `labels.csv` is the value that argument takes when initializing the Dataset.

`ds = CustomImageDataset(annotations_file="labels.csv", img_dir="my_images/")`

cc @svekars

**Comment by svekars** [comment]
Thanks, @suraj813! Closing this.
