### ISSUE TITLE
"Loading data notebook" has old/incorrect cell

### ISSUE THREAD

**Issue by telpirion** [pytorch/tutorials#1889]
Running the notebook from [this documentation page](https://pytorch.org/tutorials/recipes/recipes/loading_data_recipe.html), I get the following errors:

- Undefined keyword argument `transform`
- Undefined keyword argument `target_transform`
- Undefined variable `root`

Looking at the [reference documentation](https://pytorch.org/audio/stable/datasets.html), it doesn't look like the `transform` and `target_transform` keywords are supported (anymore).

Additional: the reference documentation states that the default value for `download` is `False`. I needed to explicitly pass `True` for `download` or else the cell wouldn't run.

Environment: Google Colab

**Comment by dineshladi** [comment]
Hi, I will be working on fixing this issue.

**Comment by dineshladi** [comment]
@msaroufim I have fixed the issue and raised a PR for the same at https://github.com/pytorch/tutorials/pull/1903

**Comment by dineshladi** [comment]
@telpirion, we fixed the issue as part of #1903 PR. Are we good to close this issue?
