### ISSUE TITLE
Tutorial about torch.distributions ?

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/tutorials#189]

**Comment by Kaixhin** [comment]
@pemami4911 do you think you'd be able to contribute an advanced tutorial based on REINFORCE/Concrete/REBAR?

**Comment by pemami4911** [comment]
Hm so this notebook has parts which can probably be rewritten and simplified with torch.distributions https://github.com/pemami4911/REBAR-pytorch/blob/master/rebar_toy.ipynb. I'm still working on the more interesting experiments from their paper, like density estimation on MNIST with REBAR. Once I finish that (unclear how soon, given that the semester has picked up and paper deadlines) I would be willing to contribute it as a tutorial!
