### ISSUE TITLE
pytorch_tutorial - wrong output at last code 

### ISSUE THREAD

**Issue by m-dp** [pytorch/tutorials#190]
Greetings, 
I also opened a topic on [discuss.pytorch.org](https://discuss.pytorch.org/t/error-on-tutorials-page-pytorch-tutorial-wrong-output-at-last-code/11335/1). 
There is an error at [/tutorials/beginner/nlp/pytorch_tutorial.html](http://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html): 
the code at the bottom, that including 

    [...]
    print(var_z.grad_fn)
    [...]
    # ... does new_var_z have information to backprop to x and y?
    # NO!
    print(new_var_z.grad_fn)

is stated to have output "None \n None"

It should be instead

    <torch.autograd.function.AddBackward object at 0x7f758cd01234>
    None

I checked here in the sources, but that error is not in this code - which does not contain the public markup part with the error.

**Comment by feilix** [comment]
I think the code may have some bugs, it should be update like this:
```
var_x = autograd.Variable(x, **requires_grad=True**)
var_y = autograd.Variable(y, **requires_grad=True**)
var_z = var_x + var_y
print(var_z.grad_fn)
```
Then the output would be right to output the "AddBackward object".

**Comment by chsasank** [comment]
Thanks, that's probably because requires_grad by default is False. Fixing it. Sorry for late reply.
