### ISSUE TITLE
Docs: tensorboard profiler tutorial doesn't render properly

### ISSUE THREAD

**Issue by ldorigo** [pytorch/tutorials#1901]
https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html , which should correspond to 
https://github.com/pytorch/tutorials/blob/b6e9f3ad67f0a76f6cad9ac4e9bd4cc2db56947e/intermediate_source/tensorboard_profiler_tutorial.py , is not rendering properly - snippets of code are not visible.

**Comment by svekars** [comment]
@gaoteng-git can you please take a look?

**Comment by svekars** [comment]
Can replace `::`  with `.. code-block::` to fix the issue.

**Comment by kiersten-stokes** [comment]
\assigntome
