### ISSUE TITLE
Error in seq2seq tutorial

### ISSUE THREAD

**Issue by cedricdeboom** [pytorch/tutorials#192]
I believe there is an error in the seq2seq tutorial. In the forward pass of the encoder, the returned hidden state is used to initialize the hidden state of the next GRU layer:

https://github.com/pytorch/tutorials/blob/7b35173c3f65d000c238e8199ac638a5ce6d40dd/intermediate_source/seq2seq_translation_tutorial.py#L347-L352

This is incorrect. The returned hidden state is the final hidden state of the processed sequence (i.e. at t=sequence_length), and is generally used to transfer hidden states between sequences. It should, however, **not** be used to initialize the hidden state of the upper layer.

**Comment by chsasank** [comment]
please checkout #195.
