### ISSUE TITLE
build_vocab_from_iterator does not work in notebook

### ISSUE THREAD

**Issue by afonso-sousa** [pytorch/tutorials#1938]
Hi. I was trying to run [this notebook](https://pytorch.org/tutorials/beginner/translation_transformer.html), but the following line times out:
```
vocab_transform[ln] = build_vocab_from_iterator(yield_tokens(train_iter, ln),
                                                    min_freq=1,
                                                    specials=special_symbols,
                                                    special_first=True)
```
Specifically, it raises a TimeoutError: [Errno 110] Connection timed out, and the last line of the trace is:
Exception: Could not get the file at http://www.quest.dcs.shef.ac.uk/wmt16_files_mmt/training.tar.gz. [RequestException] None.

What can be done to circumvent this issue? Thanks in advance for any help you can provide.

cc @pytorch/team-text-core @Nayef211 @suraj813

**Comment by Nayef211** [comment]
@afonso-sousa can you check if you're still experiencing this issue? Previously, the server that was hosting the dataset was down for some time. See https://github.com/pytorch/text/issues/1756 for more details.

**Comment by afonso-sousa** [comment]
Its working now. Thank you.
