### ISSUE TITLE
Would like the tutorial notebooks in the pytorch github 

### ISSUE THREAD

**Issue by TrackDR** [pytorch/tutorials#1951]
### 🚀 The feature, motivation and pitch

It would be nice to have the jupyter notebooks along with the original .py files in https://github.com/pytorch/tutorials

### Alternatives

I started to do something like this here: https://github.com/TrackDR/deeplearning/tree/master/pytorch_tutorials

**Comment by svekars** [comment]
Thanks for the proposal. We already generate notebooks and make them available on the website. For example: https://pytorch.org/tutorials/intermediate/fx_conv_bn_fuser.html (Click **Download Notebook**).

**Comment by svekars** [comment]
Closing this for now as it looks like there is an answer already. Feel free to reopen if needed.
