### ISSUE TITLE
Question: how to run individual tutorial?

### ISSUE THREAD

**Issue by evan0greenup** [pytorch/tutorials#1960]
I don't make to `make doc`, I just want to run a specific individual tutorial.

Is it safe to directly run it as script?

**Comment by svekars** [comment]
You can use https://github.com/pytorch/tutorials/blob/master/conf.py#L81 'GALLERY_PATTERN' parameter to exclude all tutorials but one. Here is more info: https://github.com/d4l3k/tutorials/blob/master/conf.py#L17.
