### ISSUE TITLE
Check that tutorials are executing on build

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#1965]
We want to know if a tutorial is executing while we are building it. For each tutorial, sphinx-gallery prints **Total running time** ([Example](https://pytorch.org/tutorials/beginner/transformer_tutorial.html) at the bottom of the page). The total running time of 0.00 might mean that the tutorial is failing. If this is the case, we want to be able to catch this while we run [build.sh](https://github.com/pytorch/tutorials/blob/master/.jenkins/build.sh#L65) and put that output to a text file for further investigation. 

@malfet @b0noI @atalman

**Comment by malfet** [comment]
Probably related https://github.com/pytorch/tutorials/issues/2001 <- updating to newer sphinx-gallery exposes runtime errors

**Comment by clee2000** [comment]
closing, as https://github.com/pytorch/tutorials/pull/2031 is merged

opened an issue https://github.com/pytorch/tutorials/issues/2033 for reducing the length of the NOT_RUN list
