### ISSUE TITLE
Tensor to numpy Array

### ISSUE THREAD

**Issue by xu-song** [pytorch/tutorials#197]
.numpy() is used in [pytorch tutorial](http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#numpy-bridge).
The code is as follows:

```python
a = torch.ones(5)
b = a.numpy()
```

why not adopt the most common method in tutorial:

```python
a = torch.ones(5)
b = np.asarray(a)   # it works in pytorch tensor
# or 
c = np.array(a)
```
I think the above method is more popular.

**Comment by chsasank** [comment]
AFAIK, right now,`torch.Tensor.numpy` is the recommended way for converting to numpy arrays.

**Comment by xu-song** [comment]
@chsasank thanks.

**Comment by chsasank** [comment]
I'm not super sure, but they should be using same backend functions.

**Comment by xu-song** [comment]
If they use same backend functions , I prefer the numpy-like syntax.

**Comment by soumith** [comment]
the optimized version is `.numpy()`. The `asarray` is much slower and iterats over the PyTorch tensor using python iterators.
