### ISSUE TITLE
Operations Syntax

### ISSUE THREAD

**Issue by xu-song** [pytorch/tutorials#199]
## Q 1

 for two pytorch tensor x  y
```python

# syntax 1
result = x + y

# syntax 2
result = torch.add(x, y)

```

Are they equal? 
Obviously, `syntax 1` is more friendly. But why `syntax 2` and **syntax 3** are frequently used in this tutorial?

## Q 2

```python
# syntax 3
result = torch.Tensor(5, 3)  # the output shape is required or not?
torch.add(x, y, out=result)
```

In what situation is the output shape needed?
For example, the input_shape is needed in tensorflow, output_shape can be calculated automatically from the input tensor.

**Comment by chsasank** [comment]
Q1: Yep, they are equal. Checkout https://github.com/pytorch/pytorch/blob/master/torch/tensor.py#L256. `torch.add` is used only in few places to illustrate basic functions. 

Q2: out is not for output shape, but rather location to store output. It's almost same as `out` in [`np.add`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.add.html).

**Comment by xu-song** [comment]
thanks
the output shape is not required?
```python
result = torch.Tensor(5, 3)  # the output shape is required or not?
torch.add(x, y, out=result)
```

**Comment by chsasank** [comment]
Yep, the size of `result` should be correctly matched to the result of torch.add.

**Comment by xu-song** [comment]
https://discuss.pytorch.org/, a nice forum.  thanks
