### ISSUE TITLE
Error when running reinforcement_q_learning.ipynb on colab

### ISSUE THREAD

**Issue by EmanuelNk** [pytorch/tutorials#1990]
I am trying to run the colab notebook attached to the reinforcement q learning example.
I keep getting following error:

pytorch.org -> Tutorials -> Reinforcement Learning -> Reinforcement Learning (DQN) Tutorial -> Run in Google Colab -> menu Runtime -> menu item Run All.
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-20-f1e8f42adf6c>](https://localhost:8080/#) in <module>()
     37 env.reset()
     38 plt.figure()
---> 39 plt.imshow(get_screen().cpu().squeeze(0).permute(1, 2, 0).numpy(),
     40            interpolation='none')
     41 plt.title('Example extracted screen')

3 frames
[<ipython-input-20-f1e8f42adf6c>](https://localhost:8080/#) in get_screen()
     12     # Returned screen requested by gym is 400x600x3, but is sometimes larger
     13     # such as 800x1200x3. Transpose it into torch order (CHW).
---> 14     screen = env.render(mode='rgb_array').transpose((2, 0, 1))
     15     # Cart is in the lower half, so strip off the top and bottom of the screen
     16     _, screen_height, screen_width = screen.shape

[/usr/local/lib/python3.7/dist-packages/gym/envs/classic_control/cartpole.py](https://localhost:8080/#) in render(self, mode)
    172 
    173         if self.viewer is None:
--> 174             from gym.envs.classic_control import rendering
    175             self.viewer = rendering.Viewer(screen_width, screen_height)
    176             l, r, t, b = -cartwidth / 2, cartwidth / 2, cartheight / 2, -cartheight / 2

[/usr/local/lib/python3.7/dist-packages/gym/envs/classic_control/rendering.py](https://localhost:8080/#) in <module>()
     23 
     24 try:
---> 25     from pyglet.gl import *
     26 except ImportError as e:
     27     raise ImportError('''

[/usr/local/lib/python3.7/dist-packages/pyglet/gl/__init__.py](https://localhost:8080/#) in <module>()
    233 elif compat_platform == 'darwin':
    234     from .cocoa import CocoaConfig as Config
--> 235 del base  # noqa: F821
    236 
    237 

NameError: name 'base' is not defined`

I tried following the steps suggested  here: https://github.com/pytorch/tutorials/issues/915
but it did not seem to be working.
I tried running the notebook both on CPU and GPU

cc @vmoens @nairbv

**Comment by tkmtnt7000** [comment]
I've execute this example without errors  by referring to https://stackoverflow.com/questions/53472940/nameerror-name-base-is-not-defined-openai-gym and adding the following code.
```bash
!apt install xvfb x11-utils -y
!pip install pyvirtualdisplay
!pip install piglet
!pip install gym[box2d]==0.17.* pyvirtualdisplay==0.2.* PyOpenGL==3.1.* PyOpenGL-accelerate==3.1.*

from pyvirtualdisplay import Display
display = Display(visible=False, size=(1400, 900))
display.start()
```

**Comment by svekars** [comment]
Hi. I was not able to reproduce this issue in the Colab. We have recently updated this tutorial to use `gymnasium` which seems to resolve the issue. Feel free to reopen if you see any other issues.
