### ISSUE TITLE
Problem with the torchtext library text classification example

### ISSUE THREAD

**Issue by EssamWisam** [pytorch/tutorials#1993]
The first section of the [tutorial](https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html) suggests
`
import torch
from torchtext.datasets import AG_NEWS
train_iter = iter(AG_NEWS(split='train'))
`

which does not work yielding
`TypeError: _setup_datasets() got an unexpected keyword argument 'split'`

I might highlight as well that the string doc for AG_NEWS mentions
`train_dataset, test_dataset = torchtext.datasets.AG_NEWS(ngrams=3)`

cc @pytorch/team-text-core @Nayef211

**Comment by marxwolf** [comment]
I also have this problem. Could anyone help?

**Comment by svekars** [comment]
@Nayef211 can you help?

**Comment by Nayef211** [comment]
@EssamWisam @marxwolf I just tried running the Colab notebook and unfortunately I couldn't repro the issue you guys are facing.

> I might highlight as well that the string doc for AG_NEWS mentions
`train_dataset, test_dataset = torchtext.datasets.AG_NEWS(ngrams=3)`

When a specific `split` isn't provided for a dataset, all splits of the dataset are returned, hence the suggestion from the docstrings of the AG_NEWS dataset. Lmk if that makes sense.

**Comment by svekars** [comment]
We need to add a note that it has to be run with the GPU runtime enabled.

**Comment by QasimKhan5x** [comment]
@svekars I was able to run the tutorial on Google Colab with GPU enabled. However, I wasn't able to run `train_iter = iter(AG_NEWS(split='train'))` without the `portalocker>=2.0.0` package. After installing it and restarting the notebook, all the code ran successfully.

**Comment by noqqaqq** [comment]
@svekars: Where the GPU runtime requirement you mentioned is coming from? I tried running it on collab with or without GPU as well as with default and cpu-only torch packages, and it worked fine in all cases as long as portalocker was installed.
