### ISSUE TITLE
Minor error in Math

### ISSUE THREAD

**Issue by mullachv** [pytorch/tutorials#20]
Minor correction in the math in 'Deep Learning with PyTorch.ipynb':
[https://github.com/pytorch/tutorials/blob/master/Deep%20Learning%20with%20PyTorch.ipynb](url)

You should have got a matrix of 4.5. Let's call the out Variable "$o$".
We have that $o = \frac{1}{4}\sum_i z_i$, $z_i = 3/4(x_i+2)^2$
(Missing 1/4)

**Comment by escorciav** [comment]
Is it?
They are defining $z_i=3y_i^2=3(x_i+2)^2$. The 1/4 should appear in $o$ not in $z_i$.

**Comment by mullachv** [comment]
Yes, you are correct. The issue is one of legibility, I think.
The comma after the first equation does not appear to separate it from the second part. 
Perhaps putting them on separate lines would make that clear.

___
Vikram Mullachery

**Comment by JunhongXu** [comment]
What should be the gradient of the output w.r.t matrix z? Would it be all 1/4? But when I run z.grad after out.backward(), I got all 0's. How can I compute the gradient of z?
