### ISSUE TITLE
Add a caution comment for installing OpenCV in Raspberry Pi

### ISSUE THREAD

**Issue by YunjinJo** [pytorch/tutorials#2010]
https://github.com/pytorch/tutorials/blob/86aca7dc14f3189320c0d6d59ec8cf539049093c/intermediate_source/realtime_rpi.rst#L70-L72  
If installing OpenCV in Raspberry Pi using the command ```pip install opencv-contrib-python```, it takes about 2 hours. And nothing shows in the terminal until installation finishes. People who follow this tutorial could misconceive their Raspberry Pi stop working.  
I think it would be better if a caution comment in the code block.

**Comment by svekars** [comment]
Resolved with  #2011
