### ISSUE TITLE
`hyperparameter_tuning_tutorial` started failing in CI

### ISSUE THREAD

**Issue by malfet** [pytorch/tutorials#2018]
It doesn't seem to be any change in the tutorial code, but rather some external factor (package update perhaps? Or data change)

cc @ZainRizvi

**Comment by malfet** [comment]
Link to a failed run: https://app.circleci.com/pipelines/github/pytorch/tutorials/6367/workflows/01b23770-677e-4cfd-81e1-aef6f7ccb128/jobs/125037
Link to a successful run (notice that it finishes in half the time): https://app.circleci.com/pipelines/github/pytorch/tutorials/6360/workflows/4d974e41-5e01-42da-bb4d-24c7f8410e2e/jobs/124868

**Comment by malfet** [comment]
And between successful and failing run the `ray` version has been updated from 1.13.0 to 2.0.0

**Comment by svekars** [comment]
@malfet do you want to work on this or should I find an owner?

**Comment by malfet** [comment]
Has been fixed by pinning ray version, see https://github.com/pytorch/tutorials/commit/e1ea05e56a3bf763e7d4413d5551b2f53291b2e3
