### ISSUE TITLE
fx_numeric_suite_tutorial.py failing against 1.13

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2088]
[fx_numeric_suite_tutorial.py](https://github.com/pytorch/tutorials/blob/master/prototype_source/fx_numeric_suite_tutorial.py) is failing against 1.13 binaries with the following error:

Oct 18 22:17:18 Unexpected failing examples:
Oct 18 22:17:18 /var/lib/jenkins/workspace/prototype_source/fx_numeric_suite_tutorial.py failed leaving traceback:
Oct 18 22:17:18 Traceback (most recent call last):
Oct 18 22:17:18   File "/var/lib/jenkins/workspace/prototype_source/fx_numeric_suite_tutorial.py", line 88, in <module>
Oct 18 22:17:18     copy.deepcopy(mobilenetv2_float), qconfig_dict)
Oct 18 22:17:18 TypeError: prepare_fx() missing 1 required positional argument: 'example_inputs'

Full log is [here](https://app.circleci.com/pipelines/github/pytorch/tutorials/6765/workflows/9bd3dd9b-ed84-4569-a48a-30cab17ae5b1/jobs/132382).

@vkuzo can you please investigate?
cc: @malfet 

cc @jerryzh168 @z-a-f @vkuzo

**Comment by jerryzh168** [comment]
yeah this is expected, please see https://github.com/pytorch/pytorch/pull/77608 for BC-breaking note

**Comment by vkuzo** [comment]
https://github.com/pytorch/tutorials/pull/2089 fixes this
