### ISSUE TITLE
rpc_param_server_tutorial error

### ISSUE THREAD

**Issue by chunyu-li** [pytorch/tutorials#2095]
The [link](https://github.com/pytorch/tutorials/blob/master/intermediate_source/rpc_param_server_tutorial.rst) of the tutorial

When I run 1 master node and 1 trainer node, everything is going well. However, when I run 1 master node and multiple (>=2) trainer nodes, this runtime error halts the program:

> RuntimeError: Error on Node 0: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [64, 32, 3, 3]] is at version 11; expected version 10 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by YUANCHUANYING** [comment]
> The [link](https://github.com/pytorch/tutorials/blob/master/intermediate_source/rpc_param_server_tutorial.rst) of the tutorial
> 
> When I run 1 master node and 1 trainer node, everything is going well. However, when I run 1 master node and multiple (>=2) trainer nodes, this runtime error halts the program:
> 
> > RuntimeError: Error on Node 0: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [64, 32, 3, 3]] is at version 11; expected version 10 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

excuse me, have you figured it out? i met the same question just when i used more than 1 trainer node.I would appreciate it if you could reply to me,Thanks very much!

**Comment by chunyu-li** [comment]
I have solved this problem long time ago. It's because the API `torch.distributed.rpc` does not support distributed data parallel essentially. If you want to run multiple trainer nodes simultaneously, you should look at [this tutorial](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) instead. I hope my answer can help you.

**Comment by YUANCHUANYING** [comment]
>Thanks very much.I have figured it out by changing the logic in this code, and i feel sorry for replying to you so late

**Comment by Yuvraj0157** [comment]
> > Thanks very much.I have figured it out by changing the logic in this code, and i feel sorry for replying to you so late

@YUANCHUANYING How?
