### ISSUE TITLE
Incorrect dimension in Figure: LeNet-5

### ISSUE THREAD

**Issue by jemesome** [pytorch/tutorials#2104]
In Figure LeNet-5 on this [page](https://pytorch.org/tutorials/beginner/introyt/introyt1_tutorial.html), there seems to be typo in the dimensionality of the outputs of each layer.

With an input of 32 x 32 x 1 and 6 filter of size 3 x 3, the resulting dimension after the first convolution should be 6@30 x 30. After the first subsampling(maxpool of size 2), the dimension should become 6@15 x 15. 

The second convolution with 16 filters of size 3x3 should result in 16@ 13x13, after the subsampling, the dimension should be 16@6x6

cc @suraj813

**Comment by jemesome** [comment]
i just realize, the author might meant the first layer of the convnet to be torch.nn.Conv2d(1, 6, 5). If that's the case, than the image is right, but the typo in the filter size in the code that follows needs to be corrected. The code that follow the picture has a filter of size 3x3 (i.e torch.nn.Conv2d(1, 6, 3)), which leads me to think the image is incorrect.

**Comment by suraj813** [comment]
@jemesome You're right, the image is from the classic 1998 paper - so the error is in the code! Your proposed solution is also correct. Would you like to open a PR making this change at https://github.com/pytorch/tutorials/blob/master/beginner_source/introyt/introyt1_tutorial.py? Your contribution will be appreciated in helping improve our tutorial!

**Comment by jemesome** [comment]
@suraj813 never done this before. What branch should I create the PR from? tutorial_refresh branch? or should I create my own fork  first?
i'm following this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request), but let me know if I have a better resource for me to follow . Be gentle, a noob here :)

**Comment by suraj813** [comment]
Thank you for your enthusiasm, we love noobs here! It's best practice to create your fork and raise a PR from there. The guide you have linked is a pretty good one.
