### ISSUE TITLE
training fail 

### ISSUE THREAD

**Issue by alicera** [pytorch/tutorials#2105]
image https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/index.html?from=groupmessage

I train my model with ngc docker.
Sometime I train the network (like yolov7 ) , it will let linux disconect and reboot . 
How can I debug it to find cause root?

**Comment by svekars** [comment]
Can you please ask this question in the TensorRT repo: https://github.com/pytorch/TensorRT
