### ISSUE TITLE
text_to_speech_with_torchaudio.py is disabled

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2108]
The [text_to_speech_with_torchaudio.py](https://github.com/pytorch/tutorials/blob/master/intermediate_source/text_to_speech_with_torchaudio.py) tutorial is disabled because it was causing the following issue: https://app.circleci.com/pipelines/github/pytorch/tutorials/6893/workflows/fbd131a4-0409-4e52-ae3c-c5943556a18e/jobs/134911

Please submit a PR to resolve this issue and we'll be happy to enable it.

cc @pytorch/team-audio-core @mthrok

**Comment by mthrok** [comment]
@carolineechen Let's start the redirection work with this one.

**Comment by mthrok** [comment]
@svekars It looks like you folks have removed the tutorial from the index. That's unexpected, but in that case, I think we are okay with just deleting the said tutorial.

<img width="698" alt="Screen Shot 2022-11-01 at 4 17 30 PM" src="https://user-images.githubusercontent.com/855818/199179719-292db428-512f-4af9-8fc2-4ab18ac6eb15.png">

**Comment by carolineechen** [comment]
> @carolineechen Let's start the redirection work with this one.

waiting to hear back regarding redirection plan/implementation, hopefully will be resolved soon and seems ok to leave off pytorch tutorials for now, as the version in torchaudio is still there and functional.

**Comment by svekars** [comment]
This has been resolved and completed
