### ISSUE TITLE
perhaps there is a misprint at line 40

### ISSUE THREAD

**Issue by weiguo-li** [pytorch/tutorials#2111]
instead of # self-attention layers in ``nn.TransformerEncoder`` are only allowed to attend,
# self-attention layers in ``nn.TransformerDecoder`` are only allowed to attend.....
Decoder rather than Encoder

cc @svekars @carljparker

**Comment by BaliDataMan** [comment]
@weiguo-li Can you please add link of the file here?

**Comment by frasertajima** [comment]
\assigntome

**Comment by kit1980** [comment]
Closing as fixed by https://github.com/pytorch/tutorials/pull/2363
