### ISSUE TITLE
Distributed training using torchrun is 4 times slow on 4 GPUs

### ISSUE THREAD

**Issue by shamsbasir** [pytorch/tutorials#2114]
Hi, 

I am using your code for distributed training but it is 4 times slow. I use a large model and almost 10k number of points to make sure communication is not the bottleneck. But somehow I still get 4 times slower execution time. I was wondering if you could point me to what could possibly be the problem?

Thanks

cc @mrshenli @osalpekar @H-Huang @kwen2501

**Comment by svekars** [comment]
Hi @shamsbasir. Are you following instructions in a specific tutorial? Can you please add a link to the tutorial that is not working.

cc: @suraj813

**Comment by shamsbasir** [comment]
Hi @svekars, 
Yeah I am following the tutorial by @suraj813 . It is working but there is no speed up and it is several times slower than a serial code.

**Comment by suraj813** [comment]
Hi @shamsbasir, its difficult to say without more information about the code you're running, and how you're benchmarking speed.

Can you share a minimal working example where you are encountering the slowdown?

**Comment by shamsbasir** [comment]
I am using the code in this [link](https://github.com/pytorch/examples/blob/main/distributed/ddp-tutorial-series/multigpu_torchrun.py) and I only change my model 
`    model     = torch.nn.Sequential(
                torch.nn.Linear(20,20),
                torch.nn.ReLU(),
                torch.nn.Linear(20,20),
                torch.nn.ReLU(),
                torch.nn.Linear(20,20),
                torch.nn.ReLU(),
                torch.nn.Linear(20,1)
    )`
and just time a single epoch in the train function 

`    def train(self, max_epochs: int):
        
        for epoch in range(self.epochs_run, max_epochs+1):
            
            start_train = time.time()
            
            self._run_epoch(epoch)
            
            end_train = time.time()
            
            seconds_train = (end_train - start_train)*1000.0
            
            print(f"[GPU{self.gpu_id}]Total elapsed Train time in 1 epoch {seconds_train:.3f} ms")
            
            if self.gpu_id == 0 and epoch % self.save_every == 0:
                
                self._save_snapshot(epoch)`

**Comment by suraj813** [comment]
You might be getting this issue because you're measuring execution time without synchronizing cuda calls ([more info](https://discuss.pytorch.org/t/how-to-measure-execution-time-in-pytorch/111458)).

Try running with `torch.cuda.synchronize`?
```
def train(self, max_epochs: int):
    for epoch in range(self.epochs_run, max_epochs+1):
        torch.cuda.synchronize()
        start_train = time.time()
        self._run_epoch(epoch)
        torch.cuda.synchronize()
        end_train = time.time()
        
        seconds_train = (end_train - start_train)*1000.0
        print(f"[GPU{self.gpu_id}]Total elapsed Train time in 1 epoch {seconds_train:.3f} ms")
        if self.gpu_id == 0 and epoch % self.save_every == 0:
            self._save_snapshot(epoch)
```

**Comment by svekars** [comment]
@shamsbasir did the suggestion provided by Suraj solve your issue?

**Comment by svekars** [comment]
Looks like this is resolved so closing. If you have more questions, please post on https://dev-discuss.pytorch.org/
