### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by the-jasonl** [pytorch/tutorials#2123]
When running https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html I get this error in the last cell:

`RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

Versions:
```
gym==0.26.2
torch==1.13.0
torchaudio==0.13.0
torchvision==0.14.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
box2d-py==2.3.8
pygame==2.1.2
```

cc @vmoens @nairbv

**Comment by svekars** [comment]
Not able to reproduce with the latest updates to the tutorial: 

![Screenshot 2023-03-30 at 2 10 31 PM (2)](https://user-images.githubusercontent.com/5317992/228965455-0f21534f-3bf9-478e-b49b-06eca2dc9b3d.png)
