### ISSUE TITLE
missing parameter in WikiText2

### ISSUE THREAD

**Issue by joepareti54** [pytorch/tutorials#2143]
train_iter = WikiText2(split='train')  

TypeError: __init__() missing 2 required positional arguments: 'path' and 'text_field'

cc @pytorch/team-text-core @Nayef211

**Comment by svekars** [comment]
Can you please specify which tutorial is this. Thank you!

**Comment by svekars** [comment]
Closing for now as we have not heard from the author in a while. Feel free to reopen and provide additional information.

**Comment by knslee07** [comment]
I have the same issue from 
https://pytorch.org/tutorials/beginner/transformer_tutorial.html
