### ISSUE TITLE
The code snippets in How to create custom C extension has something wrong IMHO.

### ISSUE THREAD

**Issue by sonack** [pytorch/tutorials#216]
In the official tutorial about [how to create custom C extension](http://pytorch.org/tutorials/advanced/c_extension.html) page, I think there are still minor problems. First, in the src/my_lib.c file, here is the code snippets,
```
int my_lib_add_backward(THFloatTensor *grad_output, THFloatTensor *grad_input)
{
    THFloatTensor_resizeAs(grad_input, grad_output);
    THFloatTensor_fill(grad_input, 1);
    return 1;
}
```
the statement `THFloatTensor_fill(grad_input, 1)` in the function `my_lib_add_backward` isn't correct enough in my opinion, because I think in the backward function, given the gradient w.r.t the output, you should return that gradient w.r.t the input, so grad_input should be the same as grad_output rather than filled with 1 only, 

What's more, in the step2, at the backward method of Function MyAddFunction, there should return 2 grad_input, because there are 2 inputs in the corresponding forward method. Below is the related class definition.

```
class MyAddFunction(Function):
    def forward(self, input1, input2):
        output = torch.FloatTensor()
        my_lib.my_lib_add_forward(input1, input2, output)
        return output

    def backward(self, grad_output):
        grad_input = torch.FloatTensor()
        my_lib.my_lib_add_backward(grad_output, grad_input)
        return grad_input
```

Hoping for explanation or modification in order not to confuse the newbies who reads this page.

**Comment by chsasank** [comment]
Closing issue because C tutorial is superseded by CPP tutorial.
