### ISSUE TITLE
Area calculation in TorchVision Object Detection Finetuning Tutorial

### ISSUE THREAD

**Issue by Himanshunitrr** [pytorch/tutorials#2173]
I see that at https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html, 

` area = (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0])` but shouldn't it be something like  `area = ((boxes[:, 3] - boxes[:, 1]) + 1) * ((boxes[:, 2] - boxes[:, 0]) + 1) ` for calculating areas? If I am wrong, can someone explain me why is it so. Thanks in advance !

cc @datumbox @nairbv

**Comment by NicolasHug** [comment]
Thanks for the report @Himanshunitrr 

In torchvision, we compute the area without the `+1` offset: 

https://github.com/pytorch/vision/blob/5dd95944c609ac399743fa843ddb7b83780512b3/torchvision/ops/boxes.py#L219-L235


You can find more context in this thread: https://github.com/pytorch/vision/pull/826#issuecomment-481714113

I don't think we'll change the computation to add the `+1` now, so I think we can close this issue (and the PR)

CC @svekars I don't have the permission to close :)

**Comment by NicolasHug** [comment]
@svekars this is the PR related to https://github.com/pytorch/tutorials/issues/2173 - I still can't close them :)
