### ISSUE TITLE
Do not use deepcopy to copy nn.modules (including entire models)

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/tutorials#2177]
copy.deepcopy is not defined for nn.module() and does not reliably copy an nn.module hierrchy, such as a model or partial model.  Our tutorials should using `copy.deepcopy()` as this will induce our users to make incorrect use of the primitive.  

Please update https://pytorch.org/tutorials/beginner/transformer_tutorial.html and other tutorials to avoid the use.  Recommended way for snapshotting is to use torch.save() for trained models. to create multiple clones of an untrained model, create multiple copies from first principles from the model architectural parameters.

cc @pytorch/team-text-core @Nayef211

**Comment by mikekgfb** [comment]
cc: @mthrok

**Comment by Nayef211** [comment]
Thanks for creating this issue @mikekgfb. Will submit a PR with the fixes soon.

**Comment by Nayef211** [comment]
@svekars I don't think this issue should be closed. The PR I sent out fixed the issue for https://pytorch.org/tutorials/beginner/transformer_tutorial.html. But there are several [other places](https://github.com/search?q=repo%3Apytorch%2Ftutorials%20copy.deepcopy(&type=code) where it's still being used.

**Comment by svekars** [comment]
Can the owners of the tutorials please take a look and submit corrections? If some of these tutorials describe an obsolete feature, please submit a PR to remove them:

* [fx_numeric_suite_tutorial](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/prototype_source/fx_numeric_suite_tutorial.py#L89) - @vkuzo 
* [fx_graph_mode_ptq_static](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/prototype_source/fx_graph_mode_ptq_static.rst#L218) - @jerryzh168 
* [fx_conv_bn_fuser](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/intermediate_source/fx_conv_bn_fuser.py#L107) - @Chillee 
* [transfer_learning_tutorial](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/beginner_source/transfer_learning_tutorial.py#L149) - @z-a-f 
* [quantized_transfer_learning_tutorial](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/intermediate_source/quantized_transfer_learning_tutorial.rst#L193) - @z-a-f 
* [fx_graph_mode_ptq_dynamic](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/prototype_source/fx_graph_mode_ptq_dynamic.py#L243) - @jerryzh168 
* [mario_rl](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/intermediate_source/mario_rl_tutorial.py#L437) - @suraj813 @hw26

**Comment by vkuzo** [comment]
For quantization, we were assuming that `copy.deepcopy` is defined on `nn.Module`.  Is it really not defined - are we sure that it's not just a bug that it's not working in some cases?

**Comment by qihqi** [comment]
Q: `copy.deepcopy is not defined for nn.module() and does not reliably copy an nn.module hierrchy` -- I believe in truthiness of this statement. However, why is the CTA "stop using deepcopy" and not "let's fix deepcopy for nn.Module"? Like is there a fundamental reason the latter is impossible or undesired, or it's really, "until deepcopy start working properly don't use it"?

**Comment by chedatomasz** [comment]
Are you sure deepcopy is not supposed to be defined for nn.modules? https://github.com/pytorch/pytorch/blob/master/torch/optim/swa_utils.py appears to be using deepcopy.

**Comment by carljparker** [comment]
I'm closing this issue because [sekyondaMeta](https://github.com/sekyondaMeta) has opened up targeted issues to fix the specific tutorials that need updating.

#2335 | #2334 | #2333 | #2332 | #2331 | #2330

**Comment by bot66** [comment]
Thanks for the information.
