### ISSUE TITLE
DQN Tutorial get_screen() constants

### ISSUE THREAD

**Issue by watsonkm** [pytorch/tutorials#219]
The `get_screen()` function has hard-coded constants for extracting an image region from the CartPole-v0 gym, but from what I can tell, all the dimensions have changed. Doubling the dimensions on lines 244, 257, and 258 managed to fix this.

```python
screen_width = 1200
...
...
...
    screen = screen[:, 320:640]
    view_width = 640
```

I'm relatively new to making open source contributions and the PyTorch community -- would it be best to make a pull request at this point?

**Comment by chsasank** [comment]
Yeah, A PR would be great!

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/389
