### ISSUE TITLE
Link to ImageFolder page is broken

### ISSUE THREAD

**Issue by Philip1435** [pytorch/tutorials#2198]
https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html
![image](https://user-images.githubusercontent.com/91941761/217545175-3b92f2a1-067c-4ca2-813c-afafe0b20f0f.png)

cc @svekars @carljparker

**Comment by svekars** [comment]
It looks like this tutorial was removed quite some time ago: https://github.com/pytorch/tutorials/commit/69eec4ce47fdd82951c270ac30cc37b51a9ab08c. I will make sure to remove links pointing to this tutorial. Thanks for bringing this up.
