### ISSUE TITLE
During downsampling, bicubic interpolation produces WORSE results than ffmpeg. How can I fix this issue?

### ISSUE THREAD

**Issue by tahsirmunna** [pytorch/tutorials#2205]
I have used "`bicubic`" interpolation with `(antialias=True)`. I checked the output downsampled image and found that It crates some artifacts on the image. See the image **[here](https://drive.google.com/file/d/1x1knhzyGpyqfkEjqi8tCxD4Ka_lhpfE5/view?usp=sharing)**,

Here is my code for downsampling:

```
from torch.nn.functional import interpolate
img = Image.open("image_location")
#4x down-sampled
ds_img = interpolate(transforms.ToTensor()(img).unsqueeze(0),scale_factor=.25,mode = "bicubic", antialias=True) 
down_img=transforms.ToPILImage()(ds_img.squeeze().cpu())
```

Thank you

**Comment by svekars** [comment]
Can you please add a link to the tutorial you have followed and describe your environment? Thank you!

**Comment by tahsirmunna** [comment]
### I have solved the problem by using 
ds_img = interpolate(transforms.ToTensor()(img).unsqueeze(0),scale_factor=.25,mode = "bicubic", antialias=True)**.clamp(min=0, max=1)**

Thank you
