### ISSUE TITLE
epub format support

### ISSUE THREAD

**Issue by zmlcc** [pytorch/tutorials#221]
Is it possible to provide an epub format of the tutorials  officially ?
I have tried to build by `make epub`,  
but it took too much time and I never finishd it.

**Comment by chsasank** [comment]
That's because most of the tutorials are run again to product code outputs you see in the website. If you don't care about the outputs, you can build them yourself by adding the following to Makefile.

epub-noplot:
	$(SPHINXBUILD) -D plot_gallery=0 -b epub $(SPHINXOPTS) "$(SOURCEDIR)" "$(BUILDDIR)/epub"
	@echo
	@echo "Build finished. The EPUB pages are in $(BUILDDIR)/epub."

**Comment by chsasank** [comment]
Can't host on readthedocs because build requires GPUs. I think sphinx-gallery might also have issues with epub.
