### ISSUE TITLE
Compiled ran slower than eager in the docs

### ISSUE THREAD

**Issue by ashwhall** [pytorch/tutorials#2257]
I was just reading through the torch.compile tutorial, and the section which shows the speedup between eager and compiled on a randomly-traind resnet18 actually [indicates a _slowdown_](https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html#:~:text=eager%20eval%20time%200%3A%200.008994048118591308).

```
eager eval time 0: 0.008994048118591308
eager eval time 1: 0.00896777629852295
eager eval time 2: 0.008933440208435058
eager eval time 3: 0.008922944068908692
eager eval time 4: 0.008949343681335448
eager eval time 5: 0.008947456359863281
eager eval time 6: 0.008946208000183106
eager eval time 7: 0.008931327819824218
eager eval time 8: 0.008970208168029785
eager eval time 9: 0.008936736106872558
~~~~~~~~~~
compile eval time 0: 0.009366047859191895
compile eval time 1: 0.009324607849121093
compile eval time 2: 0.009273247718811035
compile eval time 3: 0.009259200096130371
compile eval time 4: 0.00924950408935547
compile eval time 5: 0.009242624282836913
compile eval time 6: 0.009258912086486817
compile eval time 7: 0.009315679550170899
compile eval time 8: 0.00925648021697998
compile eval time 9: 0.008013312339782714
~~~~~~~~~~
(eval) eager median: 0.008946832180023193, compile median: 0.009259056091308594, speedup: 0.9662790776720228x
~~~~~~~~~~
```

Not sure if there is something non-deterministic at play here, such that regenerating docs might fix it.
Tthought I'd raise it nonetheless, as it's a bit suspicious!

Relevant code: https://github.com/pytorch/tutorials/blob/e05cd19a8a51265e5ff516857d193a17e4b365b3/intermediate_source/torch_compile_tutorial.py#L177

**EDIT**: It looks like it's been fixed now, which suggests non-determinism.

**Comment by svekars** [comment]
@williamwen42 do you have any thoughts?

**Comment by williamwen42** [comment]
Speedup is now consistently shown after switching example model.
