### ISSUE TITLE
[BUG] - No Object Detection in the "Object Detection Finetuning" Tutorial

### ISSUE THREAD

**Issue by zhanwenchen** [pytorch/tutorials#2270]
### Add Link

https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html#defining-your-model

### Describe the bug

Ironically, the only official PyTorch Object Detection tutorial doesn't do object detection - only instance segmentation.

### Describe your environment

N/A

cc @datumbox @nairbv @fmassa @NicolasHug @YosuaMichael

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.

**Comment by NicolasHug** [comment]
@vfdev-5 has been updating this tutorial and I think we can close this issue now: the tutorial mentions both detection and instance segmentation now
