### ISSUE TITLE
RNN Tutorials don't work on Windows

### ISSUE THREAD

**Issue by CodesInChaos** [pytorch/tutorials#229]
The tutorials [Classifying Names with a Character-Level RNN](http://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html) and [Generating Names with a Character-Level RNN](http://pytorch.org/tutorials/intermediate/char_rnn_generation_tutorial.html) don't work on Windows.

They attempt to extract the category from the filename using

    category = filename.split('/')[-1].split('.')[0]

which works on Linux where these look like `'data/names/Arabic.txt'` but not on Windows where they look like `'data/names\\Arabic.txt'`.

I suggest changing the code to

    category = os.path.splitext(os.path.basename(filename))[0]

(and `import os` of course)

no git installed on this machine, so no PR for now

**Comment by chsasank** [comment]
Thanks for the report. Can you raise a PR with this change?
