### ISSUE TITLE
💡 [REQUEST] - add neccessary backticks

### ISSUE THREAD

**Issue by 9bow** [pytorch/tutorials#2309]
### 🚀 Descirbe the improvement or the new tutorial

Following on from #2308, here's what ㅑ thought needed to be `backtick`-ed.
(This was added for consistency in the documentation.)

For example, in the [beginner/transformer_tutorial](https://github.com/pytorch/tutorials/blob/main/beginner_source/transformer_tutorial.py), the shape part of the code comment is wrapped in \`\`, but [on line 199](https://github.com/pytorch/tutorials/blob/main/beginner_source/transformer_tutorial.py#L199), which is missing. (shape [N] ==> shape ``[N]``)

I've summarized the two issues I found below.

Please review below and let me know.

Thanks.

### Existing tutorials on this topic

* [N] on https://github.com/pytorch/tutorials/blob/main/beginner_source/transformer_tutorial.py#L199
* weights on https://github.com/pytorch/tutorials/blob/main/beginner_source/basics/saveloadrun_tutorial.py#L36

cc @svekars @carljparker

**Comment by svekars** [comment]
Agree, will stamp a PR on this.

**Comment by 9bow** [comment]
Closed as PR is merged 😃
