### ISSUE TITLE
💡 [REQUEST] - Fix word - from option to operator

### ISSUE THREAD

**Issue by 9bow** [pytorch/tutorials#2310]
### 🚀 Descirbe the improvement or the new tutorial

Hello, @svekars .
On [line 136 of the beginner/basics/tensorqs_tutorial](https://github.com/pytorch/tutorials/blob/main/beginner_source/basics/tensorqs_tutorial.py#LL136C3-L136C3), the word 'op' was replaced by 'option' as #2242 by @lamek .

But I think ``torch.cat`` is another `operator` to join tensors, rather than `option`.

It's a small thing, but I'd appreciate your consideration.

### Existing tutorials on this topic

* option on https://github.com/pytorch/tutorials/blob/main/beginner_source/basics/tensorqs_tutorial.py#LL136C3-L136C3

cc @svekars @carljparker

**Comment by svekars** [comment]
Happy to stamp a PR that fixes this.
