### ISSUE TITLE
💡 [REQUEST] - make kernel size to 5x5

### ISSUE THREAD

**Issue by 9bow** [pytorch/tutorials#2311]
### 🚀 Descirbe the improvement or the new tutorial

As mentioned in #1257, maintainers decided to use a 5x5 kernel instead of a 3x3 kernel in the default example.

However, there is still remnant of it in [intermediate/pruning_tutorial](https://github.com/pytorch/tutorials/blob/9efe789bfc3763ec359b60f12b5e6dda4e6d5db0/intermediate_source/pruning_tutorial.py#L48-L49).

(Actually, make it worse, it remains inconsistent with the code on the line immediately below it)

Please take a look and let me know.

### Existing tutorials on this topic

* https://github.com/pytorch/tutorials/blob/9efe789bfc3763ec359b60f12b5e6dda4e6d5db0/intermediate_source/pruning_tutorial.py#L48-L49

cc @albanD @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by HemanthSai7** [comment]
Is the issue still open??

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.
