### ISSUE TITLE
TorchVision Instance Segmentation Finetuning Tutorial - No module named 'torch._six'

### ISSUE THREAD

**Issue by weronikawiera** [pytorch/tutorials#2326]
### 🚀 Descirbe the improvement or the new tutorial

The torch._six module was deprecated and removed from PyTorch starting from version 1.7.0. The code is not working because of that. How can I adjust it to make it work?

**Comment by weronikawiera** [comment]
I downloaded a newer version of the TorchVision repo and it is working fine now: `git checkout v0.12.0`.

**Comment by svekars** [comment]
Great. Thanks for reporting this.

**Comment by aymuos15** [comment]
I still have this error. 

I tried upgrading the version through `pip install --upgrade torchvision`, but the error still persists.

I am on colab. Any help?
