### ISSUE TITLE
Err in 'PyTorch: Tensors' running on GPU

### ISSUE THREAD

**Issue by planewave** [pytorch/tutorials#233]
`# dtype = torch.device("cuda:0") # Uncomment this to run on GPU`
it is supposed to be 
`# device = torch.device("cuda:0") # Uncomment this to run on GPU`
same issue in  PyTorch: Tensors and autograd

So `x = torch.randn(N, D_in, device=device, dtype=dtype)` is the new recommended style to create tensors?

**Comment by jxcodetw** [comment]
Where did you see this line of code in the tutorial?
Can you post some links?

**Comment by planewave** [comment]
they are here:
https://pytorch.org/tutorials/beginner/examples_tensor/two_layer_net_tensor.html
https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_autograd.html

**Comment by gloriouskilka** [comment]
@jxcodetw Noticed it here https://pytorch.org/tutorials/beginner/pytorch_with_examples.html
