### ISSUE TITLE
Update tutorial to avoid use of copy.deepcopy()- FX Graph Mode

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2330]
Update the  [FX Graph Mode Post Training Static Quantization tutorial](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/prototype_source/fx_graph_mode_ptq_static.rst#L218) to avoid the use of copy.deepcopy().
Tutorial link: https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/prototype_source/fx_graph_mode_ptq_static.rst#L218

See issue #2177 for more information

**Comment by QasimKhan5x** [comment]
\assigntome

**Comment by QasimKhan5x** [comment]
\assigntome
