### ISSUE TITLE
Update tutorial to avoid use of copy.deepcopy()- Computer Vision Transfer Learning Tutorial

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2332]
Update the  [Transfer Learning for Computer Vision Tutorial](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/beginner_source/transfer_learning_tutorial.py#L149) to avoid the use of copy.deepcopy().
Tutorial link: https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/beginner_source/transfer_learning_tutorial.py#L149

See issue #2177  for more information

**Comment by mikebrow** [comment]
\assigntome
