### ISSUE TITLE
Update tutorial to avoid use of copy.deepcopy()- Quantized Transfer Learning for Computer Vision

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2333]
Update the  [Quantized Learning for Computer Vision Tutorial](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/intermediate_source/quantized_transfer_learning_tutorial.rst#L193) to avoid the use of copy.deepcopy().

Tutorial link: https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/intermediate_source/quantized_transfer_learning_tutorial.rst#L193

See issue #2177  for more information

cc @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.

**Comment by svekars** [comment]
this looks like was marked for the docathon by mistake
