### ISSUE TITLE
Update tutorial to avoid use of copy.deepcopy()-Train a Mario-playing RL Agent

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2335]
Update the  [Mario Playing RL Agent code](https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/intermediate_source/mario_rl_tutorial.py#L437) to avoid the use of copy.deepcopy().

Tutorial link: https://github.com/pytorch/tutorials/blob/6ae56a1a2639308550a69c5006e879d331f05b6d/intermediate_source/mario_rl_tutorial.py#L437

See issue #2177  for more information

cc @albanD @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by HemanthSai7** [comment]
I would like to work on this issue if not completed.

**Comment by nickKyr** [comment]
go for it!

**Comment by HemanthSai7** [comment]
@svekars Can I create a PR even though it isn't assigned to me? I have made the changes avoiding deepcopy.

**Comment by svekars** [comment]
@HemanthSai7 - sorry we missed your message - if you still want to send the PR, go for it - no need to assign.
