### ISSUE TITLE
[BUG] - Tutorials should use modern syntax/coding style - torch.rand

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2338]
### Add Link

Multiple links - see below.

### Describe the bug

For example: You should use `torch.rand(device='cuda')` instead of `torch.rand(device=torch.device('cuda'))`

Instances of this issue:
* [amp_recipe.py](https://github.com/pytorch/tutorials/blob/main/recipes_source/recipes/amp_recipe.py#L82)
* [polynomial_autograd.py](https://github.com/pytorch/tutorials/blob/main/beginner_source/examples_autograd/polynomial_autograd.py#L21) change to `device = "cuda" if torch.cuda.is_available() else "cpu"`on [L21](https://github.com/pytorch/tutorials/blob/main/beginner_source/examples_autograd/polynomial_autograd.py#L21)
* [dcgan_faces_tutorial.py](https://github.com/pytorch/tutorials/blob/main/beginner_source/dcgan_faces_tutorial.py#L261)
* [tuning_guide.py](https://github.com/pytorch/tutorials/blob/main/recipes_source/recipes/tuning_guide.py#LL360C1-L361C1)
* [nestedtensor.py](https://github.com/pytorch/tutorials/blob/main/prototype_source/nestedtensor.py#L27)
* [cpp_extension.py](https://github.com/pytorch/tutorials/blob/main/advanced_source/cpp_extension.rst#performance-on-gpu-devices)
* [polynomial_tensor.py](https://github.com/pytorch/tutorials/blob/main/beginner_source/examples_tensor/polynomial_tensor.py#L32)
* [neural_style_tutorial.py](https://github.com/pytorch/tutorials/blob/main/advanced_source/neural_style_tutorial.py#L74)

### Describe your environment

* PyTorch 2.0

**Comment by malfet** [comment]
Another good idea: promote use of [torch.set_default_device](https://pytorch.org/docs/stable/generated/torch.set_default_device.html) in tutorials, instead of global `device` variable, which seems to be a common pattern.

**Comment by svekars** [comment]
@onurtore are you planing to work on this issue or should we reassign?

**Comment by onurtore** [comment]
> @onurtore are you planing to work on this issue or should we reassign? 

Hello,
I am working on it.
