### ISSUE TITLE
💡 [REQUEST] - Write a Tutorial for Using, Debugging, Performance Profiling torch.compile with Inductor CPU backend

### ISSUE THREAD

**Issue by jgong5** [pytorch/tutorials#2348]
### 🚀 Descirbe the improvement or the new tutorial

PyTorch 2.0 introduced the flagship compilation API, `torch.compile`, which offers a significant speedup over eager mode execution through graph-level optimization powered by the default TorchInductor backend. While this new feature has generated excitement within the PyTorch community, there is a lack of comprehensive tutorials that delve into the intricacies of `torch.compile`. The existing tutorials primarily focus on basic usage while missing the essential aspects such as exploring the underlying generated code, debugging potential issues, and conducting performance profiling. Therefore, this proposal aims to address this gap by creating an in-depth tutorial specifically designed for the Inductor CPU backend.

### Existing tutorials on this topic

https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html

### Additional context

We aim to complete the document as part of PyTorch Docathon 2023. cc @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ZailiWang @ZhaoqiongZ @leslie-fang-intel @Xia-Weiwen @sekahler2 @CaoE @zhuhaozhe @Valentine233 @EikanWang

**Comment by sanchitintel** [comment]
Hi @Valentine233, may I proof-read your PR? It'd help me gain in-depth knowledge of the Inductor CPU backend, and I would be able to provide feedback as someone with little knowledge of Inductor, which seems to be the intended target audience. 
If possible, please tag me on your PR once it's ready. Thanks!

**Comment by Valentine233** [comment]
> Hi @Valentine233, may I proof-read your PR? It'd help me gain in-depth knowledge of the Inductor CPU backend, and I would be able to provide feedback as someone with little knowledge of Inductor, which seems to be the intended target audience. If possible, please tag me on your PR once it's ready. Thanks!

Of course! I would include you as a PR reviewer as soon as it is ready.
