### ISSUE TITLE
💡 [REQUEST] - Port TorchRL `Recurrent DQN` tutorial from pytorch.org/rl to pytorch.org/tutorials

### ISSUE THREAD

**Issue by vmoens** [pytorch/tutorials#2349]
### 🚀 Descirbe the improvement or the new tutorial

For historical reasons, TorchRL privately hosts a bunch of tutorials.
We'd like to bring the most significant ones to pytorch tutorials for more visibility.

Here is the [tutorial](https://github.com/pytorch/rl/blob/main/tutorials/sphinx-tutorials/dqn_with_rnn.py).
In RL, we often add a RNN to a model to account for past observations when executing a policy. This of it as this: if your policy just sees a single image when playing a computer game, it will have little context about what is really happening there. If you keep a memory of past events, your performance will drastically improve. 
This is useful not only in the context of Partially Observable MDPs but more broadly than that.

Storing recurrent values can be tricky, and torchrl brings its own solution to this problem. This tutorial explains this.

Steps:
1. Port the tutorial from the RL repo to the tutorials repo.
2. Fix any formatting issues or typos.
3. Make sure the tutorial follows the tutorial template ([template_tutorial.py](https://github.com/pytorch/tutorials/blob/main/beginner_source/template_tutorial.py))
4. Preserve the original author

### Additional context

The tutorial should not require extra dependencies beyond those already present in requirements.txt.

cc @nairbv @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.
