### ISSUE TITLE
💡 [REQUEST] - Port TorchRL "Coding a DDPG loss" from pytorch.org/rl to pytorch.org/tutorials

### ISSUE THREAD

**Issue by vmoens** [pytorch/tutorials#2351]
### 🚀 Descirbe the improvement or the new tutorial

For historical reasons, TorchRL privately hosts a bunch of tutorials.
We'd like to bring the most significant ones to pytorch tutorials for more visibility.

Here is the [tutorial](https://github.com/pytorch/rl/blob/main/tutorials/sphinx-tutorials/coding_ddpg.py).
TorchRL splits down what is commonly referred to as Agents in other frameworks into various pieces that echo what can be found in other domains: data collection, datasets, transforms and losses. A dedicated class named LossModule covers this last functionality. We have a tutorial that instructs users on how to build and use such classes, you can help us port it to pytorch tutorials!

Steps:

1. Port the tutorial from the RL repo to the tutorials repo.
2. Fix any formatting issues or typos.
3. Make sure the tutorial follows the tutorial template ([template_tutorial.py](https://github.com/pytorch/tutorials/blob/main/beginner_source/template_tutorial.py))
4. Preserve the original author

### Additional context

The tutorial should not require extra dependencies beyond those already present in requirements.txt

cc @nairbv

**Comment by svekars** [comment]
@nairbv Can you please this issue to yourself as describe in https://github.com/pytorch/tutorials/issues/2350
