### ISSUE TITLE
💡 [REQUEST] - Port TorchRL `Pendulum` tutorial from pytorch.org/rl to pytorch.org/tutorials

### ISSUE THREAD

**Issue by vmoens** [pytorch/tutorials#2352]
### 🚀 Descirbe the improvement or the new tutorial

For historical reasons, TorchRL privately hosts a bunch of tutorials.
We'd like to bring the most significant ones to pytorch tutorials for more visibility.

Here is the [tutorial](https://github.com/pytorch/rl/blob/main/tutorials/sphinx-tutorials/pendulum.py).

Environments (or simulators) are a core part of many RL algorithms. The OpenAI Gym API has had a great success in the past years and paved the way for RL researchers to quickly test ideas with an easy-to-use tool.
As a PyTorch-first library, torchrl aims at being (1) oblivious to the simulator (gym or other), (2) rely on pytorch for anything we can in the simulation process, (3) a good integration within the library and (4) a coverage of many different types of environments (simulators, real-life hardware, model-based, RLHF etc). For these reasons, TorchRL propose its own class of environments. We have a dedicated tutorial that covers their design and usage: you can help us port it where it belongs!

Steps:

1. Port the tutorial from the RL repo to the tutorials repo.
2. Fix any formatting issues or typos.
3. Make sure the tutorial follows the tutorial template ([template_tutorial.py](https://github.com/pytorch/tutorials/blob/main/beginner_source/template_tutorial.py))
4. Preserve the original author

### Additional context

The tutorial should not require extra dependencies beyond those already present in requirements.txt

cc @nairbv @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ZailiWang @ZhaoqiongZ @leslie-fang-intel @Xia-Weiwen @sekahler2 @CaoE @zhuhaozhe @Valentine233

**Comment by svekars** [comment]
This issue has been unassigned due to inactivity. If you are still planning to work on this, you can still send a PR referencing this issue.
