### ISSUE TITLE
The example link is wrong in FSDP adavnced tutorial

### ISSUE THREAD

**Issue by chudegao** [pytorch/tutorials#2447]
### Add Link

https://pytorch.org/tutorials/intermediate/FSDP_adavnced_tutorial.html

### Describe the bug

The '[Pytorch Examples](https://github.com/HamidShojanazeri/examples/tree/FSDP_example/FSDP/).'  and  [summarization_dataset](https://github.com/HamidShojanazeri/examples/blob/FSDP_example/FSDP/summarization_dataset.py). refer to invalid URL(URL is updated recently).

### Describe your environment

N/A as It's a doc issue

cc @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by ptrblck** [comment]
Wrong links also reported [here](https://discuss.pytorch.org/t/advanced-model-training-with-fully-sharded-data-parallel-fsdp-not-working/189838), as it seems @HamidShojanazeri's repo might not be compatible with `2.0.1+` anymore. The user reports https://github.com/pytorch/examples/tree/main/distributed/FSDP would work. 

CC @svekars
