### ISSUE TITLE
probleam with Transfering a model from PyTorch to Caffe2 and Mobile using ONNX

### ISSUE THREAD

**Issue by dandengAI** [pytorch/tutorials#245]
I find when I excute the caffe2 section, I will always get  the following problem

×
Kernel Restarting
The kernel appears to have died. It will restart automatically.

**Comment by jspisak** [comment]
See the update here: https://github.com/pytorch/tutorials/issues/404

tl;dr is that this tutorial is getting overhauled, ONNX export is getting major improvements and we have an onnx-free workflow for mobile coming..
