### ISSUE TITLE
[BUG] - Outdated information in the Distributed RPC tutorial

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2480]
### Add Link

https://pytorch.org/tutorials/recipes/distributed_rpc_profiling
and
https://pytorch.org/tutorials/prototype/distributed_rpc_profiling

### Describe the bug

These tutorials might include outdated information. Should be either updated or deprecated. Also the tutorial is published in two places. One should be a redirect.
cc: @mrshenli @subramen 

### Describe your environment

PyTorch 2.0

cc @mrshenli @osalpekar @H-Huang @kwen2501 @wconstab

**Comment by wconstab** [comment]
@rohan-varma can you clarify if this issue is still needed or should be closed out?

**Comment by rohan-varma** [comment]
Yes, the profiler that RPC was enabled for was the old legacy / autograd profiler, and we no longer support this feature.
