### ISSUE TITLE
Cannot download dataset when using the kaggle kernel

### ISSUE THREAD

**Issue by rajath95** [pytorch/tutorials#249]
While executing the following code:

`trainset=torchvision.datasets.CIFAR10(root='./data',train=True,download=True,transform=transform)`

I get the following error message:

````

/opt/conda/lib/python3.6/urllib/request.py in http_open(self, req)
   1344 
   1345     def http_open(self, req):
-> 1346         return self.do_open(http.client.HTTPConnection, req)
   1347 
   1348     http_request = AbstractHTTPHandler.do_request_

/opt/conda/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1318                           encode_chunked=req.has_header('Transfer-encoding'))
   1319             except OSError as err: # timeout error
-> 1320                 raise URLError(err)
   1321             r = h.getresponse()
   1322         except:

URLError: <urlopen error [Errno -2] Name or service not known>`
```

**Comment by vfdev-5** [comment]
This is correct behaviour in kaggle kernels as they restrict network connection. You should use their dataset interface to work with CIFAR10 dataset.

**Comment by Gauraviiitian** [comment]
Just **switch on the Internet** from the right panel on Kaggle and hurray! happy coding!

**Comment by littlekid** [comment]
@Gauraviiitian how does one "switch on he internet" from the right panel? I don't see this option?
