### ISSUE TITLE
[BUG] - Link to first tutorial missing 

### ISSUE THREAD

**Issue by isthatdebbiej** [pytorch/tutorials#2498]
### Add Link

intermediate_source/char_rnn_generation_tutorial.py

### Describe the bug

 In the first tutorial </intermediate/char_rnn_classification_tutorial> we used a RNN to classify names into their language of origin. This time we’ll turn around and generate names from languages.

### Describe your environment

Windows

cc @svekars @carljparker

**Comment by svekars** [comment]
<img width="846" alt="Screenshot 2023-06-30 at 8 12 21 AM" src="https://github.com/pytorch/tutorials/assets/5317992/3b7f848c-c1fc-4461-81bd-a1c33e70fd4d">
Thanks for spotting this issue. We'll gladly accept a PR fixing this issue =)
