### ISSUE TITLE
More documented examples and code inside the PyTorch Tutorials

### ISSUE THREAD

**Issue by shyamalschandra** [pytorch/tutorials#252]
I would like to have the following inside the pytorch tutorials:

1. Multiple examples of possible boilerplate code using Jupyter.
2. Snippet of source code implement the function (if available) for perusal instead of a terse, ambiguous description of the function.
3. More Jupyter or REPL examples with the PyTorch zoo of models so users can generalize.

**Comment by karandwivedi42** [comment]
I can take this up, but I am unclear on what you exactly mean.

> Multiple examples of possible boilerplate code using Jupyter.

Boilerplate code for training convnets on mnist/cifar type datasets?

> Snippet of source code implement the function (if available) for perusal instead of a terse, ambiguous description of the function.

For the pytorch docs or the tutorials?

> More Jupyter or REPL examples with the PyTorch zoo of models so users can generalize.

Something like https://github.com/pytorch/examples/ but in jupyter?

**Comment by shyamalschandra** [comment]
@karandwivedi42: What is the timeline and schedule for the completion of the documentation if your confusion is resolved?  My personal email address is shyamalc@gmail.com.  Could you please clarify what is unclear?  Do you need step-by-step requirements?

**Comment by soumith** [comment]
hey shyamal,
- what do you mean by "multiple examples of possible boilerplate code"?
- in what part (as you were doing the tutorial) did you feel like you wanted the "Snippet of source code implement the function". Can you give an example?
- we have plenty of examples here: https://github.com/pytorch/examples/ , what do you see missing?

**Comment by shyamalschandra** [comment]
Hi @soumith,

Could you please start with commenting every line of the "working" examples? (e.g. https://github.com/pytorch/examples/blob/master/dcgan/main.py)

Furthermore, could you attach paper references to papers with clear examples of the exact functionality of that method so one can drill-down to the details?

Let's start there.  If you or someone else can do this to make the examples clearer and more linear, that would be a great help!

**Comment by shyamalschandra** [comment]
Is pytorch a community project or a marketing tool?  Did you understand that?

**Comment by soumith** [comment]
Thanks for your comments.

> Furthermore, could you attach paper references to papers with clear examples of the exact functionality of that method so one can drill-down to the details?

We have paper references in the README of every example except for SNLI example. We can fix SNLI example.

> Could you please start with commenting every line of the "working" examples? (e.g. https://github.com/pytorch/examples/blob/master/dcgan/main.py)

This is a subjective choice, but we feel it's better for examples to be concise and self-explanatory. commenting every line makes it verbose to the point that they look like tutorials.
The tutorials are meant to be at the level of verbosity that you seem to want.

[your deleted comment]

> "Is pytorch a community project or a marketing tool? Did you understand that?"

Please dont bring your snarkiness here, we dont appreciate it. Folks like @karandwivedi42 work hard as community members to make PyTorch the best it can be and they dont need it. I remember your entitled behavoir and threats on the [torch7 forums](https://groups.google.com/forum/#!searchin/torch7/shyamal%7Csort:date/torch7/gjohKLrDlWo/M2vcggmnCAAJ) and [torch7 issues](https://github.com/torch/torch7/issues/732#issuecomment-237995352), and it looks like your attitude hasn't changed much.
