### ISSUE TITLE
Autograd - M factor missing in Matrix Vector Multiplication?

### ISSUE THREAD

**Issue by sudz123** [pytorch/tutorials#2554]
In [this](https://github.com/pytorch/tutorials/blob/main/beginner_source/blitz/autograd_tutorial.py) tutorial, once the vector v is multiplied by the Jacobian, shouldn't there be an additional factor of M in the results? 

cc @albanD

**Comment by svekars** [comment]
Thanks for your question @sudz123  and sorry for the late response. Can you please ask on https://dev-discuss.pytorch.org/
