### ISSUE TITLE
💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by haoyunliang** [pytorch/tutorials#2569]
### 🚀 Descirbe the improvement or the new tutorial

This tutorial “A GENTLE INTRODUCTION TO TORCH.AUTOGRAD”, the gradients of the error w.r.t. parameters, Q w.r.t a, I think the result should be a 2x2 matrix but not a 2-d vector, according to the matrix calculus.

cc @albanD

**Comment by albanD** [comment]
Hi,

There are a couple shortcuts from a pure mathematical formulation there to keep things simple.
But the root is that the backward does not compute the jacobian (which would be 2x2) but a vector-jacobian product (which is of size 2).

**Comment by malfet** [comment]
Love the title of the issue...

**Comment by svekars** [comment]
@haoyunliang hopefully, this answers your question. If you have more questions, could you please post on https://dev-discuss.pytorch.org/. Thank you!
