### ISSUE TITLE
Confirm if batch training in seq2seq tutorial?

### ISSUE THREAD

**Issue by ecilay** [pytorch/tutorials#259]
for the tutorial _pytorch->tutorials/intermediate_source/seq2seq_translation_tutorial.py_: [https://github.com/pytorch/tutorials/blob/master/intermediate_source/seq2seq_translation_tutorial.py](url)

According to lines 636-646, It seems like it is training with one sentence at a time, instead of batch training. Am I understanding it right?

**Comment by hamelsmu** [comment]
Yes it is actually training one word at a time!

**Comment by maayanorner** [comment]
@hamelsmu  I know it's an old issue - but what about that repo? https://github.com/AuCson/PyTorch-Batch-Attention-Seq2seq (yes, I did try to implement a version using batches and ended up here :) )

**Comment by hamelsmu** [comment]
I don't remember anymore this issue is ancient and whatever I said back then is probably wrong or outdated now 🙇
