### ISSUE TITLE
Training on GPU in deep learning notebook - inputs/labels need cuda()

### ISSUE THREAD

**Issue by gojira** [pytorch/tutorials#26]
In working through the deep learning notebook, it's not obvious at first how to get the learning working once you put the net on the GPU.

After some trial and error, this worked 

        inputs, labels = Variable(inputs).cuda(), Variable(labels).cuda()

I could make a PR with this addition if desired

**Comment by soumith** [comment]
The correct line is:

```
 inputs, labels = Variable(inputs.cuda()), Variable(labels.cuda())
```

A PR is welcome :)
thank you

**Comment by gojira** [comment]
OK, sent a PR

**Comment by zym1010** [comment]
actually, only having `inputs, labels = Variable(inputs).cuda(), Variable(labels).cuda()` is not enough.  There are so many places needing this. Without `.cuda()` here and there, the ipython kernel simply crashes. I feel this to be pretty frustrating.
