### ISSUE TITLE
[BUG] broken links in tuning_guide.html

### ISSUE THREAD

**Issue by stas00** [pytorch/tutorials#2629]
### Add Link

https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html

### Describe the bug

1 broken link in 2 places:
```
More detailed descriptions can be found `here <https://software.intel.com/content/www/us/en/develop/articles/how-to-get-better-performance-on-pytorchcaffe2-with-intel-acceleration.html>`_.

Detailed information can be found `here <https://software.intel.com/content/www/us/en/develop/articles/how-to-get-better-performance-on-pytorchcaffe2-with-intel-acceleration.html>`_.
```

in https://github.com/pytorch/tutorials/blob/main/recipes_source/recipes/tuning_guide.py

I couldn't find the original. 

When linking to company websites like Intel's it might be a good idea to first save the page in https://web.archive.org/ and link there as wikipedia does. It's almost guaranteed a newly hired designer is going to 404 many links at least once a year.

Thank you.

cc @svekars @carljparker @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ZailiWang @ZhaoqiongZ @leslie-fang-intel @Xia-Weiwen @sekahler2 @CaoE @zhuhaozhe @Valentine233 @sekyondaMeta @NicolasHug @kit1980 @subramen

**Comment by svekars** [comment]
Suggesting to just delete these broken links unless the original resource is found.

**Comment by mingfeima** [comment]
@jingxu10 could you please take care of this issue ?

**Comment by markstur** [comment]
/assigntome

If @jingxu10 isn't doing this I'd take it (I'm looking for my first easy docathon fix)

**Comment by jingxu10** [comment]
Updated the URL at https://github.com/pytorch/tutorials/pull/2657
