### ISSUE TITLE
[BUG] - MarioRL Resize Bug

### ISSUE THREAD

**Issue by alperenunlu** [pytorch/tutorials#2650]
### Add Link

[mario_rl_tutorial.py](https://github.com/pytorch/tutorials/blob/main/intermediate_source/mario_rl_tutorial.py)

### Describe the bug

On MarioRL Tutorial resize function gives warning in newer versions.

```bash
python intermediate_source/mario_rl_tutorial.py
```

> UserWarning: The default value of the antialias parameter of all the resizing transforms > (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to > be consistent across the PIL and Tensor backends. To suppress this warning, directly pass > antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).

### Describe your environment

Platform: macOS
CUDA: no
PyTorch version: 2.1.0

cc @vmoens @nairbv @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by alperenunlu** [comment]
@svekars

**Comment by svekars** [comment]
@vmoens  any thoughts?

**Comment by vmoens** [comment]
As the warning says, the use of `Resize` should have the flag `antialias=True`. That should not impact the performance of the learning algorithm
