### ISSUE TITLE
[BUG] - MarioRL Not Logging Last Episode

### ISSUE THREAD

**Issue by alperenunlu** [pytorch/tutorials#2651]
### Add Link

[mario_rl_tutorial.py](https://github.com/pytorch/tutorials/blob/main/intermediate_source/mario_rl_tutorial.py)

### Describe the bug

On MarioRL tutorial it's not logging the last episode.

Example:
`episodes=40`

It's logging

* `episode 0`
* `episode 20`

Then finishes without logging the last episode which is `episode 39`

### Describe your environment

Platform: macOS
CUDA: no
PyTorch version: 2.1.0

cc @vmoens @nairbv @sekyondaMeta @svekars @carljparker @NicolasHug @kit1980 @subramen

**Comment by alperenunlu** [comment]
@svekars

**Comment by vmoens** [comment]
We could simply add one more episode in the loop and we’d get the # 40, Wdyt?

**Comment by alperenunlu** [comment]
Yes we could, but still the last episode will run for nothing.

**Comment by alperenunlu** [comment]
@vmoens
