### ISSUE TITLE
Why multiply sqrt(d_model) before TransformerEncoderLayer?

### ISSUE THREAD

**Issue by yuzhenmao** [pytorch/tutorials#2655]
Hi,

Thank you so much for the tutorial! I notice that in https://github.com/pytorch/tutorials/blob/main/beginner_source/transformer_tutorial.py#L92, you multiply sqrt(d_model) before TransformerEncoderLayer. May I ask why we need to do this?

Thanks!

**Comment by svekars** [comment]
@yuzhenmao I suggest you post on https://dev-discuss.pytorch.org/.
