### ISSUE TITLE
💡 [REQUEST] - A Tutorial on Whole Slide Image Classification using PyTorch and TIAToolbox

### ISSUE THREAD

**Issue by Abdol** [pytorch/tutorials#2669]
### 🚀 Descirbe the improvement or the new tutorial

Whole Slide Images are the digital data format from which pathologists and computational pathology researchers investigate cancer growth. To due their enormous image resolutions and and file size (in the order of several gigabytes), conventional image processing methods do not work effectively. This is why we propose writing this tutorial: to (a) explain how to load WSIs using TIAToolbox, which helps process such slides with speed and efficiency using its pyramid stack structure, and (b) show how you can use `torchvision` models can to analyse WSIs. We believe this tutorial will be useful to the PyTorch community, especially who is interested in using PyTorch models tackle cancer tissue research.

### Existing tutorials on this topic

The tutorial will be adapted from our [WSI classification example](https://tia-toolbox.readthedocs.io/en/latest/_notebooks/jnb/05-patch-prediction.html). 

### Additional context

**Category: Image and Video**

Written by Tissue Image Analytics Centre (TIA) and invited by @carljparker as part of the PyTorch Docathon H2 2023.
cc @datumbox @nairbv @fmassa @NicolasHug @YosuaMichael @sekyondaMeta @svekars @carljparker @kit1980 @subramen @measty @behnazelhaminia @DavidBAEpstein @shaneahmed @msaroufim

**Comment by niyatikarthik** [comment]
assign to me

**Comment by NicolasHug** [comment]
@niyatikarthik I'm afraid there's already a PR opened for this in https://github.com/pytorch/tutorials/pull/2675
