### ISSUE TITLE
[BUG] - Failed to import Checkpoint for hyperparameter tuning tutorial

### ISSUE THREAD

**Issue by undecidedapollo** [pytorch/tutorials#2679]
### Add Link

https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html

### Describe the bug

The example in the tutorial and raw Github file fail to run. The tutorial imports Checkpoint from ray.air when the Class is defined inside ray.train.

Documentation: https://docs.ray.io/en/latest/train/api/doc/ray.train.Checkpoint.html#ray.train.Checkpoint

Which throws the following error:

```
ImportError: cannot import name 'Checkpoint' from 'ray.air'
```

### Describe your environment

* Platform: MacOS Ventura 13.4.1, M2
* CUDA: No, MPS
* PyTorch version: 2.1.0

**Comment by undecidedapollo** [comment]
This may be complicated as the API seems to have changed a bit since the tutorial was put together:

```
AttributeError: The new `ray.train.Checkpoint` class does not support `from_dict()`. Instead, only directories are supported.

Example to store a dictionary in a checkpoint:

import os, tempfile
import ray.cloudpickle as pickle
from ray import train
from ray.train import Checkpoint

with tempfile.TemporaryDirectory() as checkpoint_dir:
  with open(os.path.join(checkpoint_dir, 'data.pkl'), 'wb') as fp:
    pickle.dump({'data': 'value'}, fp)

  checkpoint = Checkpoint.from_directory(checkpoint_dir)
  train.report(..., checkpoint=checkpoint)

Example to load a dictionary from a checkpoint:

if train.get_checkpoint():
  with train.get_checkpoint().as_directory() as checkpoint_dir:
    with open(os.path.join(checkpoint_dir, 'data.pkl'), 'rb') as fp:
      data = pickle.load(fp)
```

**Comment by atskae** [comment]
I started looking into this issue, I think I was able to fix the load/store Checkpoint problem with [the suggestion you posted](https://github.com/pytorch/tutorials/issues/2679#issuecomment-1810906970), currently running into:

<img width="774" alt="Screenshot 2024-02-26 at 10 24 14 AM" src="https://github.com/pytorch/tutorials/assets/35437563/278386c1-df9d-4a06-85e6-ca3fe3c39503">

Will investigate further.
