### ISSUE TITLE
[BUG] - Normalization not working 

### ISSUE THREAD

**Issue by tommasomarzi** [pytorch/tutorials#2681]
### Add Link

https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html

### Describe the bug

In the "Training a classifier" tutorial there's a problem with tranforms. More precisely, when we load the CIFAR10 dataset:
```python
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
```
the data are not normalized according to transform, since the values of `trainset` are still in the range [0,255].

Furthermore, if instead I normalize it separately:
```python
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True)
norm_trainset = transform(trainset)
```
It raises the following error:
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-0bfd4c890109>](https://localhost:8080/#) in <cell line: 1>()
----> 1 transform(trainset)

2 frames
[/usr/local/lib/python3.10/dist-packages/torchvision/transforms/transforms.py](https://localhost:8080/#) in __call__(self, img)
     93     def __call__(self, img):
     94         for t in self.transforms:
---> 95             img = t(img)
     96         return img
     97 

[/usr/local/lib/python3.10/dist-packages/torchvision/transforms/transforms.py](https://localhost:8080/#) in __call__(self, pic)
    135             Tensor: Converted image.
    136         """
--> 137         return F.to_tensor(pic)
    138 
    139     def __repr__(self) -> str:

[/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional.py](https://localhost:8080/#) in to_tensor(pic)
    138         _log_api_usage_once(to_tensor)
    139     if not (F_pil._is_pil_image(pic) or _is_numpy(pic)):
--> 140         raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")
    141 
    142     if _is_numpy(pic) and not _is_numpy_image(pic):

TypeError: pic should be PIL Image or ndarray. Got <class 'torchvision.datasets.cifar.CIFAR10'>
```

### Describe your environment

* Platform: Google Colab
* Cuda: 11.8
* Pytorch version: 2.1.0

**Comment by tommasomarzi** [comment]
I noticed that I was wrong in the first point, i.e. the dataset is correctly normalized (I printed `trainset.data` instead of the transformed values of `trainset`).
On the other hand, I still don't understand why the lines:
```python
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True)
norm_trainset = transform(trainset)
```
raise error.

**Comment by garyyaoresearch** [comment]
transform is a function/function-like object that works on individual images (data samples for none-image datasets). 

`trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)`
passes the the transform to the dataset object such that the dataset object calls transform on any image being grabbed.  As per  TORCHVISION.DATASETS.CIFAR. Although it might be fun and useful to create a custom transform class that works on entire datasets as a preprocess. 
```

def __getitem__(self, index: int) -> Tuple[Any, Any]:
        """
        Args:
            index (int): Index

        Returns:
            tuple: (image, target) where target is index of the target class.
        """
        img, target = self.data[index], self.targets[index]

        # doing this so that it is consistent with all other datasets
        # to return a PIL Image
        img = Image.fromarray(img)

        if self.transform is not None:
            img = self.transform(img)

        if self.target_transform is not None:
            target = self.target_transform(target)

        return img, target
```

**Comment by tommasomarzi** [comment]
Ok, got it, thanks for the clear explanation! If I call `transform()` as follows:
```python
norm_data= transform(trainset.data[0])
norm_data= transform(trainset[0][0])
```
I obtain the expected results.
In fact, it might be useful to add a custom method that works as you propose.

Thank you again!
