### ISSUE TITLE
Links in the document cannot be redirected

### ISSUE THREAD

**Issue by TD-wzw** [pytorch/tutorials#2692]
### 📚 The doc issue

https://pytorch.org/tutorials/prototype/fx_graph_mode_quant_guide.html

Under heading “Refactor your code to make it symbolically traceable”
More information about symbolic tracing support can be found in: (TODO: link)

cc @svekars @carljparker

**Comment by jerryzh168** [comment]
here is the link: https://pytorch.org/docs/stable/fx.html#limitations-of-symbolic-tracing @TD-wzw please feel free to submit a PR if you have time
