### ISSUE TITLE
optimizer.zero_grad call in wrong place in quickstart tutorial

### ISSUE THREAD

**Issue by Flagy** [pytorch/tutorials#2693]
In the quickstart tutorial linked here:
https://github.com/pytorch/tutorials/blob/main/beginner_source/basics/quickstart_tutorial.py

the call to optimizer.zero_grad function is not done in the right place, it should be put as first line in the training loop as explained in the optimization tutorial: https://pytorch.org/tutorials/beginner/basics/optimization_tutorial.html

The results of the network without applying this change are poor and not coherent with the goal of the tutorial.

**Comment by garyyaoresearch** [comment]
> @garyyaoresearch you are right, actually in both tutorials the call to zero_grad is right after the call to step. However I've seen many times that zero_grad is actually called before the bacward and step. Also the accepted answer in the pytorch discussion [here](https://discuss.pytorch.org/t/what-step-backward-and-zero-grad-do/33301/7) appears to suggest the order as zero_grad, backward and then step in the training loop.
> 
> But the real problem for me was that the performances of the model are very poor on the MNIST_fashion dataset on the [quickstart_tutorial](https://github.com/pytorch/tutorials/blob/main/beginner_source/basics/quickstart_tutorial.py) and they improve when the zero_grad is put before.
> 
> Let me know if you found the same issue on the performances of the model on the indicated tutorial.

Would it possible to show us result logs for comparison? Is it possible that when making the change, you didn't restart the notebook or reinitialize the model?

**Comment by albanD** [comment]
As discussed in https://github.com/pytorch/tutorials/pull/2800 I think we do want to keep the current order to ensure minimal memory use which is a generally important concern these days while it will preserve the same numerical result for these use cases.
