### ISSUE TITLE
Tutorials page Not responding in Chrome browser

### ISSUE THREAD

**Issue by ekanna** [pytorch/tutorials#270]
Hi

https://pytorch.org/tutorials/

This page not responding in Chrome latest browser on MacOS

**Comment by goodlux** [comment]
Hi @ekanna -

Not having any issues with Chrome / MacOS on this side...is the site unresponsive still for you?

**Comment by ekanna** [comment]
Still unresponsive! 
MacOS 10.13.3 and Chrome 67

In safari, it is working fine.

**Comment by ekanna** [comment]
Now it is working fine in chrome!
