### ISSUE TITLE
[BUG] - maskedtensor_sparsity.py tutorial is disabled

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2708]
### Add Link

https://github.com/pytorch/tutorials/blob/main/prototype_source/maskedtensor_sparsity.py

### Describe the bug

The [prototype_source/maskedtensor_sparsity.py](https://github.com/pytorch/tutorials/blob/main/prototype_source/maskedtensor_sparsity.py) tutorial was disabled because it was causing the following [issue](https://github.com/pytorch/tutorials/actions/runs/7146829803/job/19465304303?pr=2702#step:8:9312) against the 2.2 RC binaries

Please submit a PR to resolve this issue and enable in the `.jenkins/validate_tutorials_built.py` script.

### Describe your environment

PyTorch: 2.2

cc @albanD

**Comment by albanD** [comment]
cc @cpuhrsch

**Comment by cpuhrsch** [comment]
That's not good. This means that `is_sparse` now is a property and not a method anymore.

@amjames @pearu Please check this. You can find RC candidates on our discussion forum https://dev-discuss.pytorch.org/t/pytorch-2-2-release-branch-cut-for-pytorch-core-is-completed/1716

If this is true, then we need to open a high priority issue for this regression and land a fix in the branch before release.

**Comment by cpuhrsch** [comment]
Ugh ok I found the issue https://github.com/pytorch/pytorch/pull/110725 and I even accepted it. cc @janeyx99 .

Alright, not sure if we want to revert this or not for this release.

**Comment by cpuhrsch** [comment]
@amjames @pearu please ignore. This is unrelated to sparsity.

**Comment by cpuhrsch** [comment]
@albanD @svekars - Fix is here https://github.com/pytorch/tutorials/pull/2712

**Comment by cpuhrsch** [comment]
Based on the description in https://github.com/pytorch/pytorch/pull/110725  @janeyx99 the change actually causes MaskedTensor to be *more* consistent. So we don't want to revert this. I misread the situation. Serves me right for working late.
