### ISSUE TITLE
[BUG] - Disabling advanced/usb_semisup_learn

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2711]
### Add Link

https://pytorch.org/tutorials/advanced/usb_semisup_learn.html

### Describe the bug

In the current shape, the tutorial takes 143 minutes to build which increases the time of the whole tutorial build by 2 hours. 
To enable this tutorial, we need to reduce the execution time to a reasonable number - most of the tutorials take less than 30 minutes to build. This can be achieved by reducing the number of training iterations to a reasonable number or optimizing other parts of the code.

After that, the tutorial can be enabled in the `.jenkins/validate_tutorials_built.py` script

There is also an image that is not rendering correctly:
<img width="924" alt="Screenshot 2023-12-11 at 12 49 44 PM" src="https://github.com/pytorch/tutorials/assets/5317992/0471f4ae-4802-49ba-bff7-3c7d082459fb">

### Describe your environment

N/A

**Comment by atskae** [comment]
> There is also an image that is not rendering correctly:

@Hhhhhhao @svekars What was the intended image in the tutorial?

**Comment by Hhhhhhao** [comment]
> > There is also an image that is not rendering correctly:
> 
> @Hhhhhhao @svekars What was the intended image in the tutorial?

The image should be this one: https://github.com/microsoft/Semi-supervised-learning/blob/main/figures/code.png
I don't know why it is not rendered. 

To reduce the training iterations, we can reduce this number: https://github.com/pytorch/tutorials/blob/082c8b1bddb48b75f59860db3679d8c439238f10/advanced_source/usb_semisup_learn.py#L95

**Comment by Hhhhhhao** [comment]
> > The image should be this one: https://github.com/microsoft/Semi-supervised-learning/blob/main/figures/code.png
> 
> Would it be ok if I link the image to that URL directly in the notebook?
> 
> > To reduce the training iterations, we can reduce this number:
> 
> I will try reducing that value and see what is reasonable.

Yeah. Using the link directly would be fine. 
I guess changing the iteration numbers to 1000 would be fine?

**Comment by atskae** [comment]
> I guess changing the iteration numbers to 1000 would be fine?

I tried 500 earlier and it ran for 3 minutes with an accuracy of 87% for both FreeMatch and SoftMatch. Trying 1000 now.

**Comment by Hhhhhhao** [comment]
> > I guess changing the iteration numbers to 1000 would be fine?
> 
> I tried 500 earlier and it ran for 3 minutes with an accuracy of 87% for both FreeMatch and SoftMatch. Trying 1000 now.

if that's the case I think 500 would be good.

**Comment by atskae** [comment]
Interesting, I just ran with 1000 iterations for FreeMatch (ran for 8 minutes) and the accuracy went slightly down to 86%.
