### ISSUE TITLE
confusion in Tutorials >  Quantization Recipe

### ISSUE THREAD

**Issue by XA23i** [pytorch/tutorials#2725]
In 3. Post Training Static Quantization
" This method converts both the weights and the activations to 8-bit integers beforehand so there won’t be on-the-fly conversion on the activations during the inference, as the dynamic quantization does, **hence improving the performance significantly.**"

but I think the performance of Post Training Static Quantization is weaker than Post Training dynamic quantization since dynamic quantization can calibrate for each input.

cc @jerryzh168 @z-a-f @vkuzo

**Comment by jmarintur** [comment]
Hi @svekars and @XA23i, what about this?

" This method converts both the weights and the activations to 8-bit integers beforehand so there won’t be on-the-fly conversion on the activations during the inference, as the dynamic quantization does. **While post-training static quantization can significantly enhance inference speed and reduce model size, this method may degrade the original model's performance.**"

**Comment by svekars** [comment]
@jerryzh168 any thoughts?

**Comment by XA23i** [comment]
yes, I think it makes  @sense.
