### ISSUE TITLE
Notebooks (ipynb) are not created properly during build process.

### ISSUE THREAD

**Issue by goodlux** [pytorch/tutorials#274]
Our current workflow for writing tutorials is as follows:

1. An author writes a tutorial as .ipynb file, then converts to .py file. The resulting file is here: https://github.com/pytorch/tutorials/blob/master/advanced_source/neural_style_tutorial.py
2. The during documentation build, sphinx-gallery then creates two additional files: 

(A)  an .rst which is then converted to HTML, which shows up 
 https://pytorch.org/tutorials/advanced/neural_style_tutorial.html
(B) an .ipynb file, which is broken. You can download the broken .ipynb file by clicking the link at the bottom of the page:

![screen shot 2018-07-24 at 11 14 52 am](https://user-images.githubusercontent.com/31841/43158473-9a09d2c2-8f34-11e8-913f-0a8a4b9d4d3e.png)

examples of broken content:

![screen shot 2018-07-24 at 11 15 55 am](https://user-images.githubusercontent.com/31841/43158534-bed2e54e-8f34-11e8-9a30-82911dd556d2.png)

![screen shot 2018-07-24 at 11 16 02 am](https://user-images.githubusercontent.com/31841/43158545-c4248b56-8f34-11e8-8e82-66bc6dc5a3d1.png)

This issue affects almost every tutorial. 

The issue is caused by using sphinx-gallery to do the conversions:

https://github.com/sphinx-gallery/sphinx-gallery/issues/245

A fix may be to use pandoc instead. The new process should be:

1. An author writes a tutorial as Jupyter Notebook (.ipynb)
2. The author adds this to the GitHub repo. 
3. A pandoc script then produces .rst and .py file. 

The authors should not have to worry about doing conversions and any process should support the markdown used by Jupyter notebooks. 

A possible fix was created here, but was rejected by sphinx-gallery team:

 https://github.com/sphinx-gallery/sphinx-gallery/pull/220

**Comment by choldgraf** [comment]
Just a note that I'm giving this another shot here:

https://github.com/sphinx-gallery/sphinx-gallery/pull/423

with a helper function + docs in sphinx-gallery, as opposed to being a core part of the build process. If you've got thoughts there whether it'd be useful, implemented correctly, etc, then please chime in! If it ultimately gets rejected, I'll probably just spin it off into it's own tiny package, which I'd welcome contributions on so we can tighten up the `.ipynb`->`.py` conversion!
