### ISSUE TITLE
pipeline_tutorial failing due to dead torchtext link

### ISSUE THREAD

**Issue by clee2000** [pytorch/tutorials#2773]
Line 55 of https://github.com/pytorch/tutorials/blob/082c8b1bddb48b75f59860db3679d8c439238f10/intermediate_source/pipeline_tutorial.py is using torchtext to download a dataset that can’t be accessed right now (maybe got taken down, I’m looking for an alternative link but torchtext is no longer maintained)

Can this tutorial be rewritten to use a different dataset?  Can the entire tutorial be deprecated?

Ex: https://github.com/pytorch/tutorials/actions/runs/7992713944/job/21826864521
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-2-v1.zip`

cc @kwen2501 @H-Huang @wconstab

**Comment by kwen2501** [comment]
I'd vote for deprecating the entire tutorial as nobody maintains the software or the tutorial now

**Comment by karelvaculik** [comment]
I've got the same error with Transformer tutorial (https://pytorch.org/tutorials/beginner/transformer_tutorial.html).

**Comment by svekars** [comment]
Will send a PR to deprecate. Thanks!
