### ISSUE TITLE
C++ tutoral vs. automatic backwards

### ISSUE THREAD

**Issue by t-vi** [pytorch/tutorials#278]
As far as I can tell, C++ extensions using ATen functions do get automatic differentiation now. So

> At this time, PyTorch’s C++ interface does not support automatic differentiation. This is something the PyTorch team is working on, but it is not available yet. 

seems outdated.

Also the speed comparison between C++ and Python seems to be combining two effects: That of moving from C++ to Python, and that from moving from traced autograd to a custom backward.
Not properly QA'd, but just replacing the call to rnn with the call to the C++ forward (i.e. relying on traced autograd which now works in C++) seems to give a 10% speedup in the forward and running the Python version with torch.no_grad() (as an approximation of C++ forward without the tracing) makes the forward 20% faster.

**Comment by apaszke** [comment]
I think the tutorial might just mean that there's no way to add custom `autograd.Function`s in C++.
