### ISSUE TITLE
NN tutorial - picture and code are confusing at first glance

### ISSUE THREAD

**Issue by intel-hm** [pytorch/tutorials#2788]
### 🚀 Descirbe the improvement or the new tutorial

Link to tutorial: https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html  

Trying to learn and understand PyTorch I was utterly confused when comparing the picture and the corresponding code

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

where are the subsampling layers? I first thought you simply dropped them and used an outdated picture. Only much later I saw that they are included in the forward function. Maybe something like this would be better:

     def __init__(self):
        # input channel 32x32 pixel
        super(Net, self).__init__()
        # convolution layer C1: 1 input image channel, 6 output channels, 5x5 square convolution => 28x28 pixel
        self.conv1 = nn.Conv2d(1, 6, 5)
        # subsampling layer S2: 2x2 grid, purely functional, does not keep any parameter => 14x14 pixel
        # convolution layer C3: 6 input channels, 16 output channels,  5x5 square convolution => 10x10 pixel
        self.conv2 = nn.Conv2d(6, 16, 5)
        # subsampling layer S4: 2x2 grid, purely functional, does not keep any parameter => 5x5 pixel
        # flatten operation: purely functional, 2D picture => 1D array
        # fully connected layer F4: 160 inputs, 120 outputs, uses RELU activation function
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension
        # fully connected layer F5: 120 inputs, 84 outputs, uses RELU activation function
        self.fc2 = nn.Linear(120, 84)
        # gaussian layer F6: 84 inputs, 10 outputs
        self.fc3 = nn.Linear(84, 10)

**Comment by jmarintur** [comment]
Dear @intel-hm, rather than populating the `init`, perhaps another simple way to connect picture and code could consist in something like this:

```
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, input):
        c1 = F.relu(self.conv1(input))
        # Max pooling over a (2, 2) window
        s2 = F.max_pool2d(c1, (2, 2))
        c3 = F.relu(self.conv2(s2))
        # If the size is a square, you can specify with a single number
        s4 = F.max_pool2d(c3, 2)
        # flatten all s4 dimensions except the batch dimension, before applying fc1
        s4 = torch.flatten(s4, 1)
        f5 = F.relu(self.fc1(s4)) 
        f6 = F.relu(self.fc2(f5))
        output = self.fc3(f6)
        return output

net = Net()
net
```
Wdyt?

**Comment by intel-hm** [comment]
I just think that each layer mentioned in the picture should have an corresponding comment in the code. Some of the layers are represented by variables, some are not. Things are further complicated by different names in picture and the private variables of class Net. For someone just starting out this is extremely confusing.

Best regards
Michael

**Comment by jmarintur** [comment]
We could include the comments you added in your suggestion to the renaming I did within the `forward`.

**Comment by intel-hm** [comment]
Please do!
Thanks
Michael

**Comment by jmarintur** [comment]
Hi @intel-hm, I've just created a PR, I added you as a co-author. I slightly modify the original one.

**Comment by intel-hm** [comment]
Thank you!
