### ISSUE TITLE
[BUG] - intermediate_source/torch_export_tutorial.py fails against 2.3 RC binaries

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2805]
### Add Link

[intermediate_source/torch_export_tutorial.py](https://pytorch.org/tutorials/intermediate/torch_export_tutorial.html)

### Describe the bug

The [intermediate_source/torch_export_tutorial.py](https://github.com/pytorch/tutorials/blob/main/intermediate_source/torch_export_tutorial.py) is failing with the following error message:
```
Unexpected failing examples:
/var/lib/jenkins/workspace/intermediate_source/torch_export_tutorial.py failed leaving traceback:
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/intermediate_source/torch_export_tutorial.py", line 74, in <module>
    print(exported_mod(torch.randn(8, 100), torch.randn(8, 100)))
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/export/exported_program.py", line 347, in __call__
    raise RuntimeError(
RuntimeError: Unable to call ExportedProgram directly. You should use `exported_program.module()` instead.
```
[link to build](https://github.com/pytorch/tutorials/actions/runs/8351129628/job/22858918743?pr=2804#step:8:5475)

### Describe your environment

- Pytorch version 2.3
- CUDA 12
- CI

**Comment by svekars** [comment]
@williamwen42 @angelayi @zhxchen17

**Comment by angelayi** [comment]
i can send a fix
