### ISSUE TITLE
[BUG] - torchvision_tutorial.py fails with a RuntimeError

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2843]
### Add Link

https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html

### Describe the bug

Fails in CI and locally on MacOS with:
```
disable due to RuntimeError: DataLoader worker (pid(s) 20092) exited unexpectedly
```
The tutorial was disabled in: https://github.com/pytorch/tutorials/pull/2842 - can be enabled after the issue is resolved.

### Describe your environment

* macOS and CI
* Pytorch 2.3 

cc @datumbox @nairbv @fmassa @NicolasHug @YosuaMichael @sekyondaMeta @kit1980

**Comment by alperenunlu** [comment]
@svekars Should I just describe the bug or also solve it.

**Comment by svekars** [comment]
@alperenunlu the task here is to solve the issue and enable the tutorial.

**Comment by alperenunlu** [comment]
So the main problem is `torch.utils.data` uses different behavior on different platforms

In MacOS and Windows it uses `spawn()` on Unix it uses `fork()` for multiprocessing.

So if we were running a script we should wrap our main script in a `if __name__ == "__main__":` that will solve the problem but in Jupyter notebooks this also doesn't work so if we want to create a solution for both notebooks and script the best thing come to my mind is checking the platform and setting the num_workers according to that.

@NicolasHug
