### ISSUE TITLE
Better specify `torch.compile behaviour` on nested function/module

### ISSUE THREAD

**Issue by bhack** [pytorch/tutorials#2858]
### 📚 The doc issue

Can we better specify the behavior and eventually the best practices when decorating a function or compiling a module and the effect on the nested modules and nested function call?

https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html

cc @sekyondaMeta @svekars @kit1980 @williamwen42 @msaroufim @ezyang @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by ignaciobartol** [comment]
@awayzjj Are you still working on this issue? If not I would like to help. Thanks! 

cc @sekyondaMeta

**Comment by awayzjj** [comment]
I removed the assighment! You can take it! @ignaciobartol

**Comment by ignaciobartol** [comment]
I assigned myself to another issue yesterday and still I'm working on it, I apologize for the confusion if you still wanted to work on it. I will check back later today after submitting a PR to see if this one is still available. But thanks!! @awayzjj

**Comment by ezyang** [comment]
Not sure what you're looking for here. If you torch.compile a function, we will try to recursively inline/compile every function call inside it. If there's a graph break, we will try again for inner frames. There are some other functions to disable this process if needed.

**Comment by bhack** [comment]
Yes I think currently this is not explicitly specified in the doc right?
Other then this if there is some general hint to help to reporting bugs.. e.g. try to compile leaf `def`in the graph before reporting a ticket in the recursive case or something similar it could help in that documentation section (then we could link to a section of your WIP doc when ready).

**Comment by ezyang** [comment]
OK, send a doc patch for this @ignaciobartol, thanks

**Comment by ignaciobartol** [comment]
@ezyang Yes, sorry I got caught up with other work yesterday. I will work on it later today and submit a PR
