### ISSUE TITLE
blitz Tutorial has wrong output.

### ISSUE THREAD

**Issue by nikhil-seth** [pytorch/tutorials#287]
Blitz Tutorial has following command 
`x = torch.empty(5, 3)
print(x)`
whose Output is shown as
`tensor([[-5.0254e+18,  4.5609e-41, -5.0254e+18],
        [ 4.5609e-41,  1.6395e-43,  1.3873e-43],
        [ 1.4574e-43,  4.4842e-44,  1.4293e-43],
        [ 1.4714e-43,  1.5134e-43,  1.4153e-43],
        [ 4.4842e-44,  1.5554e-43,  1.5975e-43]])`

but when running code on machine, getting
` tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])`
[Link to Error in Docs.](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)
[Link to Sphinx File related to it](https://github.com/pytorch/tutorials/blob/master/beginner_source/blitz/tensor_tutorial.py)

**Comment by Zhaoyi-Yan** [comment]
It is not wrong.  It should return values of a tensor filled with uninitialized data. Usually very small or big values.

**Comment by nikhil-seth** [comment]
I got it. 
Thanks for helping.  :)
