### ISSUE TITLE
Test the Reinforcement Learning (DQN) tutorial

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2897]
Test the following tutorial:
 https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html
 **Follow these steps:**
1. Fork the pytorch/tutorials repo.
2. Switch to a new branch.
3. Run the tutorial as a python script:
```
python3 <path-to-tutorial>
```
4. Save the output into a .txt file. Did you see any errors? Add them to the output.
5. Run the tutorial in the Google Colab and save the outputs into a .txt file. Did you see any issues? Take screenshots of the issues.
6. Did the tutorial make sense? Can you suggest any improvements? Past all the outputs, screenshots, and suggestions for improvements in the issue and ping one of the reviewers. If your suggestion is approved, please submit a PR with the fix.

cc @vmoens @nairbv @svekars @kit1980 @brycebortree

**Comment by alperenunlu** [comment]
MacOS output:
> Complete
![Figure_1](https://github.com/pytorch/tutorials/assets/97191996/06e982f2-d9fe-436d-a9bc-d7b0a08228c8)

Colab output:
> Complete
![Unknown](https://github.com/pytorch/tutorials/assets/97191996/060612cc-1010-41e5-8e56-1fbb29bf3b55)

Suggestions:
- The tutorial can check also for `METAL` backend for `MacOS`
- The tutorial can cite the DQN Paper [Playing Atari with Deep Reinforcement Learning](https://arxiv.org/abs/1312.5602)

**Comment by svekars** [comment]
@vmoens - can you comment on whether these suggestions make sense?

**Comment by vmoens** [comment]
This is what you get if you run it for longer (from the tuto)
![image](https://github.com/pytorch/tutorials/assets/25529882/4d03ce33-31bb-45d9-b7c9-a753a43b97a0)
So I'm not worried by these learning curves.

We usually run into issues when using MPS but if it works I'm open to have that option in the tuto!

We should definitely cite the paper!
