### ISSUE TITLE
Test the Tensors tutorial

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2899]
Test the following tutorial:
 https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html
 **Follow these steps:**
1. Fork the pytorch/tutorials repo.
2. Switch to a new branch.
3. Run the tutorial as a python script:
```
python3 <path-to-tutorial>
```
4. Save the output into a .txt file. Did you see any errors? Add them to the output.
5. Run the tutorial in the Google Colab and save the outputs into a .txt file. Did you see any issues? Take screenshots of the issues.
6. Did the tutorial make sense? Can you suggest any improvements? Past all the outputs, screenshots, and suggestions for improvements in the issue and ping one of the reviewers. If your suggestion is approved, please submit a PR with the fix.

cc @svekars @kit1980

**Comment by svekars** [comment]
This issues does not necessarily requires a PR to be closed. Can you please report your findings:
* Did the tutorials run successfully in Colab? - addd outputs.
* Did it run successfully locally as a script? - add outputs.
We'll give full credit for these checks. Thanks!

**Comment by akhil-maker** [comment]
[tensor_tutorial_colab.pdf](https://github.com/user-attachments/files/15810555/tensor_tutorial_colab.pdf)
@svekars 
Attached is the output in colab 
The tensor tutorial is running fine in colab and locally as a script. 
Tested properly.

**Comment by svekars** [comment]
Great! Thank you!
