### ISSUE TITLE
AttributeError: 'TimeLimit' object has no attribute 'x_threshold'

### ISSUE THREAD

**Issue by ShowLang** [pytorch/tutorials#29]
I have a problem when I run the code in PyTorch DQN tutorial,the code and error are :

```
resize = T.Compose([T.ToPILImage(), T.Scale(40, interpolation=Image.CUBIC), T.ToTensor()])

# This is based on the code from gym.
screen_width = 600
def get_cart_location():
    world_width = env.x_threshold * 2
    scale = screen_width / world_width
    return int(env.state[0] * scale + screen_width / 2.0) # MIDDLE OF CART
    
    
def get_screen():
    screen = env.render(mode='rgb_array').transpose((2, 0, 1)) # transpose into torch order (CHW)
    # Strip off the top and bottom of the screen
    screen = screen[:, 160:320]
    view_width = 320
    cart_location = get_cart_location()
    if cart_location < view_width // 2:
        slice_range = slice(view_width)
    elif cart_location > (screen_width - view_width // 2):
        slice_range = slice(-view_width,None)
    else:
        slice_range = slice(cart_location - view_width // 2, cart_location + view_width // 2)
    # Strip off the edges, so that we have a square image centered on a cart
    screen = screen[:, :, slice_range]
    # Convert to float, rescare, convert to torch tensor (this doesn't require a copy)
    screen = np.ascontiguousarray(screen, dtype=np.float32) / 255
    screen = torch.from_numpy(screen)
    # Resize, and add a batch dimension (BCHW)
    return resize(screen).unsqueeze(0)

env.reset()
plt.imshow(get_screen().squeeze(0).permute(1, 2, 0).numpy(), interpolation='none')
plt.show()
```

```
AttributeError                            Traceback (most recent call last)
<ipython-input-5-0076b471379d> in <module>()
     30 
     31 env.reset()
---> 32 plt.imshow(get_screen().squeeze(0).permute(1, 2, 0).numpy(), interpolation='none')
     33 plt.show()

<ipython-input-5-0076b471379d> in get_screen()
     14     screen = screen[:, 160:320]
     15     view_width = 320
---> 16     cart_location = get_cart_location()
     17     if cart_location < view_width // 2:
     18         slice_range = slice(view_width)

<ipython-input-5-0076b471379d> in get_cart_location()
      4 screen_width = 600
      5 def get_cart_location():
----> 6     world_width = env.x_threshold * 2
      7     scale = screen_width / world_width
      8     return int(env.state[0] * scale + screen_width / 2.0) # MIDDLE OF CART

AttributeError: 'TimeLimit' object has no attribute 'x_threshold'
```

I don't know how this happened,since I had installed the gym,and run the demo in gym successfully,any advice of you would be appreciated

**Comment by eeckee** [comment]
I experienced the same problem...bump

**Comment by apaszke** [comment]
I can't reproduce it. Did you try updating `gym`?

**Comment by ShowLang** [comment]
I reinstalled gym as what open ai website said,but the problem is still unsolved.
`git clone https://github.com/openai/gym
cd gym
pip install -e . `
and run 
`pip install -e .[all]'
 for a full install 

I have also  tested the gym 
`import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break`
and the results are below
`[2017-02-14 10:59:02,327] Making new env: CartPole-v0
[ 0.0456196   0.009135    0.04553682 -0.03245288]
[ 0.0458023  -0.18660939  0.04488776  0.27424253]
[ 0.04207012  0.00784431  0.05037261 -0.00395165]
[ 0.042227    0.20220901  0.05029358 -0.28032561]
[ 0.04627118  0.00640706  0.04468707  0.02778603]
[ 0.04639932  0.20086062  0.04524279 -0.25046951]
[ 0.05041654  0.39530827  0.0402334  -0.52854568]
[ 0.0583227   0.58984178  0.02966248 -0.80828437]
[ 0.07011954  0.78454495  0.0134968  -1.09149116]
[ 0.08581044  0.97948645 -0.00833303 -1.37990883]
[ 0.10540017  1.17471143 -0.0359312  -1.67518602]
[ 0.12889439  1.37023143 -0.06943492 -1.97883822]
[ 0.15629902  1.17590547 -0.10901169 -1.70844914]
[ 0.17981713  0.98219251 -0.14318067 -1.45159049]
[ 0.19946098  1.17875376 -0.17221248 -1.78536672]
[ 0.22303606  0.98593445 -0.20791982 -1.5507966 ]
Episode finished after 16 timesteps
[-0.03044536  0.04494224 -0.04249268 -0.04497625]
[-0.02954651 -0.14954544 -0.0433922   0.23400285]
[-0.03253742 -0.34402141 -0.03871214  0.5126889 ]
[-0.03941785 -0.53857732 -0.02845837  0.7929256 ]
[-0.05018939 -0.34307649 -0.01259985  0.49142747]
[-0.05705092 -0.53801847 -0.0027713   0.78011296]
[-0.06781129 -0.34285853  0.01283095  0.48655941]
[-0.07466846 -0.14791996  0.02256214  0.19794782]
[-0.07762686 -0.34335723  0.0265211   0.49766183]
[-0.08449401 -0.53884289  0.03647434  0.79858349]
[-0.09527087 -0.34423982  0.05244601  0.5175941 ]
[-0.10215566 -0.14989402  0.06279789  0.24188829]
[-0.10515354  0.04427731  0.06763565 -0.03034415]
[-0.104268    0.23836742  0.06702877 -0.30094392]
[-0.09950065  0.04235731  0.06100989  0.0121027 ]
[-0.0986535   0.23655365  0.06125195 -0.26072405]
[-0.09392243  0.04061323  0.05603746  0.05063221]
[-0.09311016  0.23488875  0.05705011 -0.22385725]
[-0.08841239  0.03899978  0.05257296  0.0862618 ]
[-0.08763239  0.23333027  0.0542982  -0.18938185]
[-0.08296579  0.42763505  0.05051056 -0.46445366]
[-0.07441309  0.23183708  0.04122149 -0.15628749]
[-0.06977635  0.42634534  0.03809574 -0.43568634]
[-0.06124944  0.62090787  0.02938201 -0.71612096]
[-0.04883128  0.42539183  0.01505959 -0.4143364 ]
[-0.04032344  0.2300597   0.00677287 -0.11694408]
[-0.03572225  0.42508396  0.00443398 -0.40748255]
[-0.02722057  0.22989941 -0.00371567 -0.11340503]
[-0.02262258  0.42507441 -0.00598377 -0.4072579 ]
[-0.01412109  0.62028069 -0.01412893 -0.7018213 ]
[-0.00171548  0.81559561 -0.02816535 -0.9989182 ]
[ 0.01459643  1.01108252 -0.04814372 -1.30031178]
[ 0.03481808  1.2067813  -0.07414995 -1.60766861]
[ 0.05895371  1.01261005 -0.10630332 -1.33899218]
[ 0.07920591  1.2088978  -0.13308317 -1.66295612]
[ 0.10338386  1.01555309 -0.16634229 -1.41451459]
[ 0.12369493  1.21229898 -0.19463258 -1.75423932]
Episode finished after 37 timesteps
[ 0.04681315  0.04696543 -0.03717238 -0.00532002]
[ 0.04775246  0.24260023 -0.03727878 -0.30949566]
[ 0.05260446  0.43823295 -0.04346869 -0.61369828]
[ 0.06136912  0.24374452 -0.05574266 -0.33501699]
[ 0.06624401  0.43961366 -0.062443   -0.64474422]
[ 0.07503628  0.24541493 -0.07533788 -0.37236016]
[ 0.07994458  0.05143958 -0.08278509 -0.10435085]
[ 0.08097337  0.24764433 -0.0848721  -0.42196108]
[ 0.08592626  0.44385974 -0.09331133 -0.74014723]
[ 0.09480345  0.25014151 -0.10811427 -0.47822775]
[ 0.09980628  0.44661047 -0.11767882 -0.80293422]
[ 0.10873849  0.25328182 -0.13373751 -0.54946466]
[ 0.11380413  0.45000378 -0.1447268  -0.88111436]
[ 0.12280421  0.25711289 -0.16234909 -0.63720424]
[ 0.12794646  0.0645826  -0.17509317 -0.39972761]
[ 0.12923812 -0.12767953 -0.18308773 -0.16695863]
[ 0.12668453 -0.31977305 -0.1864269   0.06283817]
[ 0.12028906 -0.51180089 -0.18517014  0.2913964 ]
[ 0.11005305 -0.31458803 -0.17934221 -0.0534953 ]
[ 0.10376129 -0.11740844 -0.18041211 -0.39696533]
[ 0.10141312 -0.30957366 -0.18835142 -0.1661497 ]
[ 0.09522164 -0.50157033 -0.19167441  0.06170342]
[ 0.08519024 -0.69350127 -0.19044035  0.28831962]
[ 0.07132021 -0.4962462  -0.18467395 -0.05786537]
[ 0.06139529 -0.29902275 -0.18583126 -0.40265626]
[ 0.05541483 -0.49109001 -0.19388439 -0.17383609]
[ 0.04559303 -0.29379821 -0.19736111 -0.52087442]
[ 0.03971707 -0.48567474 -0.2077786  -0.29629506]
...
...
[-0.00162973  0.14711404  0.02325979 -0.29232772]
[ 0.00131256  0.34189676  0.01741324 -0.57758501]
[ 0.00815049  0.14653513  0.00586154 -0.27946776]
[  1.10811933e-02   3.41572979e-01   2.72180295e-04  -5.70296219e-01]
[ 0.01791265  0.14644721 -0.01113374 -0.27752756]
[ 0.0208416  -0.04851415 -0.0166843   0.0116231 ]
[ 0.01987131  0.14684306 -0.01645183 -0.28627687]
[ 0.02280818  0.34219572 -0.02217737 -0.58410284]
[ 0.02965209  0.53762121 -0.03385943 -0.8836886 ]
[ 0.04040451  0.34297502 -0.0515332  -0.60183943]
[ 0.04726401  0.5387785  -0.06356999 -0.91029881]
[ 0.05803958  0.73470048 -0.08177596 -1.22226515]
[ 0.07273359  0.54072174 -0.10622127 -0.95628474]
[ 0.08354803  0.73709952 -0.12534696 -1.28036154]
[ 0.09829002  0.5437776  -0.15095419 -1.02940935]
[ 0.10916557  0.74055064 -0.17154238 -1.36542454]
[ 0.12397658  0.93735467 -0.19885087 -1.70648422]
Episode finished after 18 timesteps`
The gym seems work well,but when run the tutorials ,the problem recurred.

**Comment by ShowLang** [comment]
The problem has been solved,and the latest version works well,thanks!@yzli
