### ISSUE TITLE
Test the Running the Tutorial Code tutorial

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2901]
Test the following tutorial:
 https://pytorch.org/tutorials/beginner/introyt.html
 **Follow these steps:**
1. Fork the pytorch/tutorials repo.
2. Switch to a new branch.
3. Run the tutorial as a python script:
```
python3 <path-to-tutorial>
```
4. Save the output into a .txt file. Did you see any errors? Add them to the output.
5. Run the tutorial in the Google Colab and save the outputs into a .txt file. Did you see any issues? Take screenshots of the issues.
6. Did the tutorial make sense? Can you suggest any improvements? Past all the outputs, screenshots, and suggestions for improvements in the issue and ping one of the reviewers. If your suggestion is approved, please submit a PR with the fix.

cc @albanD @svekars @kit1980 @brycebortree

**Comment by sekyondaMeta** [comment]
@abhi2596 Do you have an update on this? If you are not able to work on this, we can re-assign someone to it.

**Comment by abhi2596** [comment]
I will give an update by end of today

**Comment by hippocookie** [comment]
@svekars 
Hello, I found in the pytorch dtype doc(link in below) is ``torch.bfloat16``, but in tutorial is``torch.bfloat`` , this might be mislead user to created ``dtype=torch.bfloat`` and get an error, might be better to make improvements:

- change tutorial consistent with doc, both ``dtype=torch.bfloat16``
- and also suggest to add a link reference to dtype doc, which make users easier to find the specific explanation of dtype. 
<img width="1239" alt="image" src="https://github.com/pytorch/tutorials/assets/54812088/637cac9f-3f2f-47cf-90eb-ffbf1fb11a62">

If these changes looks good, I would like to submit a PR, thanks! 😆 


tutorial link: https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html
doc link: https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype

**tutorial is ``torch.bfloat``**
<img width="1487" alt="image" src="https://github.com/pytorch/tutorials/assets/54812088/46a34a01-9805-46c9-9775-488476c2e108">

**Got error when try to create**
![image](https://github.com/pytorch/tutorials/assets/54812088/9f7cd735-4b7b-47c9-8b0a-cb46ca39a198)

**Should be ``dtype=torch.bfloat16``**
![image](https://github.com/pytorch/tutorials/assets/54812088/bf06bf88-553a-4760-be40-1b8136101e50)

**Comment by abhi2596** [comment]
Hi @svekars,That wasn't my idea; it was @hippocookie's idea. I think he has a PR, so I unassigned myself from the task.

**Comment by hippocookie** [comment]
@abhi2596 Thanks 😆
