### ISSUE TITLE
Test the Text classification with the torchtext library tutorial

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2904]
Test the following tutorial:
 https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html
 **Follow these steps:**
1. Fork the pytorch/tutorials repo.
2. Switch to a new branch.
3. Run the tutorial as a python script:
```
python3 <path-to-tutorial>
```
4. Save the output into a .txt file. Did you see any errors? Add them to the output.
5. Run the tutorial in the Google Colab and save the outputs into a .txt file. Did you see any issues? Take screenshots of the issues.
6. Did the tutorial make sense? Can you suggest any improvements? Past all the outputs, screenshots, and suggestions for improvements in the issue and ping one of the reviewers. If your suggestion is approved, please submit a PR with the fix.

cc @svekars @kit1980

**Comment by ignaciobartol** [comment]
Hello, is someone working on this issue so far?

**Comment by ahoblitz** [comment]
@ignaciobartol I was going to knock this out tomorrow AM, I unassigned myself so you can grab it

**Comment by ignaciobartol** [comment]
@ahoblitz sure? I was also planning working on this tomorrow AM, so I don’t mind if you still want it. Otherwise I’ll take it, thanks!

**Comment by ignaciobartol** [comment]
\assigntome

**Comment by brycebortree** [comment]
Hi, @julurisaichandu do you have an update for testing this tutorial? We can always reassign the issue. Thanks!
