### ISSUE TITLE
Test the Loading data in PyTorch tutorial

### ISSUE THREAD

**Issue by sekyondaMeta** [pytorch/tutorials#2905]
Test the following tutorial:
 https://pytorch.org/tutorials/recipes/recipes/loading_data_recipe.html
 **Follow these steps:**
1. Fork the pytorch/tutorials repo.
2. Switch to a new branch.
3. Run the tutorial as a python script:
```
python3 <path-to-tutorial>
```
4. Save the output into a .txt file. Did you see any errors? Add them to the output.
5. Run the tutorial in the Google Colab and save the outputs into a .txt file. Did you see any issues? Take screenshots of the issues.
6. Did the tutorial make sense? Can you suggest any improvements? Past all the outputs, screenshots, and suggestions for improvements in the issue and ping one of the reviewers. If your suggestion is approved, please submit a PR with the fix.

cc @svekars @kit1980

**Comment by svekars** [comment]
This recipe specifically is quite outdated and likely does not answer what a user is trying to learn. There is a better tutorial on this topic: https://pytorch.org/tutorials/beginner/basics/data_tutorial.html - we could consider deprecating and creating a redirect from this tutorial to the data_tutorial.html.
