### ISSUE TITLE
[BUG] - is torch.compile necessary to use user defined triton kernel 

### ISSUE THREAD

**Issue by felixdae** [pytorch/tutorials#2939]
### Add Link

https://pytorch.org/tutorials/recipes/torch_compile_user_defined_triton_kernel_tutorial.html

### Describe the bug

i think we can call triton kernel with torch.compile
what we get when call triton kernel through torch.compile?

### Describe your environment

none

cc @williamwen42 @msaroufim

**Comment by svekars** [comment]
cc: @oulgen

**Comment by oulgen** [comment]
Yes, user defined triton kernels work without torch.compile but the tutorial you linked above is about how they work with torch.compile.
