### ISSUE TITLE
[BUG] - missing file - tp_tutorial.py

### ISSUE THREAD

**Issue by SeungjunNah** [pytorch/tutorials#2956]
### Add Link

https://github.com/pytorch/tutorials/blob/main/intermediate_source/TP_tutorial.rst#how-to-apply-tensor-parallel

### Describe the bug

Hi, in this tutorial, there is an example command suggested to run the tutorial code. However, as of today, `tp_tutorial.py` file does not exist in this repo. It looks like the file was accidentally not pushed. It would be great if it could be added.
```bash
# run this via torchrun: torchrun --standalone --nproc_per_node=8 ./tp_tutorial.py
```

### Describe your environment

Linux - Ubuntu.

**Comment by svekars** [comment]
cc: @wanchaol @tianyu-l

**Comment by tianyu-l** [comment]
Sorry this comment was not intended to be put here.

I've updated the tutorial to remove this comment https://github.com/pytorch/tutorials/pull/2998

To see/run the end-to-end code example, please follow the link in the tutorial to [Tensor Parallel examples](https://github.com/pytorch/examples/blob/main/distributed/tensor_parallelism/fsdp_tp_example.py) in the `pytorch/examples` repository
