### ISSUE TITLE
[Reinforcement Learning] - help on cartpull tutorial

### ISSUE THREAD

**Issue by Misticfury** [pytorch/tutorials#2994]
hello im completely new to machine learning and just trying to learn. im getting this warning an none of the figure are showing up (libEGL warning: DRI2: failed to authenticate) does anyone know what i could be missing or what might be the cause? im running this in unraid on a VM with a graphics card passed thru with its drivers installed. using Ubuntu 24.04 LTS fresh install, plz help thanks.

cc @vmoens @nairbv

**Comment by Misticfury** [comment]
if helpful this is my pip list
Package                  Version
------------------------ --------------
asttokens                2.4.1
attrs                    23.2.0
Babel                    2.10.3
bcc                      0.29.1
blinker                  1.7.0
Brlapi                   0.8.5
certifi                  2023.11.17
chardet                  5.2.0
click                    8.1.6
cloud-init               24.1.3
cloudpickle              3.0.0
colorama                 0.4.6
command-not-found        0.3
configobj                5.0.8
contourpy                1.2.1
cryptography             41.0.7
cupshelpers              1.0
cycler                   0.12.1
dbus-python              1.3.2
decorator                5.1.1
defer                    1.0.6
distro                   1.9.0
distro-info              1.7+build1
executing                2.0.1
Farama-Notifications     0.0.4
filelock                 3.15.4
fonttools                4.53.1
fsspec                   2024.6.1
gymnasium                0.29.1
httplib2                 0.20.4
idna                     3.6
ipython                  8.26.0
jedi                     0.19.1
Jinja2                   3.1.2
jsonpatch                1.32
jsonpointer              2.0
jsonschema               4.10.3
kiwisolver               1.4.5
language-selector        0.1
launchpadlib             1.11.0
lazr.restfulclient       0.14.6
lazr.uri                 1.0.6
louis                    3.29.0
markdown-it-py           3.0.0
MarkupSafe               2.1.5
matplotlib               3.9.1.post1
matplotlib-inline        0.1.7
mdurl                    0.1.2
mpmath                   1.3.0
netaddr                  0.8.0
netifaces                0.11.0
networkx                 3.3
numpy                    2.0.1
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.20
nvidia-nvtx-cu12         12.1.105
oauthlib                 3.2.2
olefile                  0.46
packaging                24.1
parso                    0.8.4
pexpect                  4.9.0
pillow                   10.2.0
pip                      24.0
prompt_toolkit           3.0.47
ptyprocess               0.7.0
pure_eval                0.2.3
pycairo                  1.25.1
pycups                   2.0.1
pygame                   2.6.0
Pygments                 2.17.2
PyGObject                3.48.2
PyJWT                    2.7.0
pyparsing                3.1.1
pyrsistent               0.20.0
pyserial                 3.5
python-apt               2.7.7+ubuntu1
python-dateutil          2.8.2
python-debian            0.1.49+ubuntu2
pytz                     2024.1
pyxdg                    0.28
PyYAML                   6.0.1
requests                 2.31.0
rich                     13.7.1
screen-resolution-extra  0.0.0
setuptools               68.1.2
six                      1.16.0
stack-data               0.6.3
sympy                    1.13.1
systemd-python           235
torch                    2.4.0
torchaudio               2.4.0
torchvision              0.19.0
traitlets                5.14.3
triton                   3.0.0
typing_extensions        4.10.0
ubuntu-drivers-common    0.0.0
ubuntu-pro-client        8001
ufw                      0.36.2
unattended-upgrades      0.1
urllib3                  2.0.7
wadllib                  1.3.6
wcwidth                  0.2.13
wheel                    0.42.0
xdg                      5
xkit                     0.0.0

**Comment by vmoens** [comment]
Can you share a bit more info, like the trace / the entire warning or a screenshot of it?
Does it stop you from running the tutorial?

**Comment by Misticfury** [comment]
i doesn't look like it crashes i tried install pyqt but not only did that not worked its crashes i then uninstalled pyqt like i had before and i still get the same warning.

![image](https://github.com/user-attachments/assets/3939492b-8100-477a-8aa1-0a42f70dd24e)

in the picture i first tried to run it with pyqt installed it just quickly crashed i then uninstalled pyqt like i had before and thats the warning i get. it seems like the script is running but i don't see anything i then just ctrl-c to end it.

**Comment by Misticfury** [comment]
i found the issue i needed to have pyqt installed and apt install libxcb-cursor0 thats what i was missing.
