### ISSUE TITLE
pytorch profiler failed to record execution events

### ISSUE THREAD

**Issue by cfangplus** [pytorch/tutorials#2996]
### 🚀 Describe the improvement or the new tutorial

I copy this python file here https://github.com/pytorch/tutorials/blob/main/intermediate_source/tensorboard_profiler_tutorial.py and run on my conda environment, however, it seems failed to record execution events because the log folder only create a json file and the tensorboard also failed to show the result.
btw there is no error or exception thrown and my pytorch and torchvision version is ok.

cc @aaronenyeshi @chaekit @jcarreiro

**Comment by venkatram-dev** [comment]
Please install torch_tb_profiler

`pip install torch_tb_profiler`

https://github.com/pytorch/tutorials/blob/main/intermediate_source/tensorboard_profiler_tutorial.py#L170C7-L170C36

**Comment by cfangplus** [comment]
Of course I followed the instructions and install tb. After step into the code, now I know the event file is actually json file, but the browser in my window environment still failed to show the result but browser in mac environment is successful.
