### ISSUE TITLE
💡 [REQUEST] - Tutorial on out-of-tree extension autoloading mechanism

### ISSUE THREAD

**Issue by shink** [pytorch/tutorials#3039]
### 🚀 Describe the improvement or the new tutorial

This tutorial will help the third party extension writers better to improve seamless integration within PyTorch.

### Existing tutorials on this topic

None

**Comment by svekars** [comment]
Approved. Related [PR](https://github.com/pytorch/tutorials/pull/3037). Please follow the guidelines in the [comment](https://github.com/pytorch/tutorials/pull/3037#pullrequestreview-2284055369).
