### ISSUE TITLE
[BUG] ONNX Tutorials are failing against 2.6 binaries

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#3191]
### Add Link

[beginner/onnx/export_simple_model_to_onnx_tutorial.html](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
[beginner/onnx/onnx_registry_tutorial.html](https://pytorch.org/tutorials/beginner/onnx/onnx_registry_tutorial.html)

### Describe the bug

Errors:
```WARNING: /var/lib/workspace/beginner_source/onnx/export_simple_model_to_onnx_tutorial.py failed to execute correctly: Traceback (most recent call last):
  File "/var/lib/workspace/beginner_source/onnx/export_simple_model_to_onnx_tutorial.py", line 158, in <module>
    onnx_input = onnx_program.adapt_torch_inputs_to_onnx(torch_input)
AttributeError: 'ONNXProgram' object has no attribute 'adapt_torch_inputs_to_onnx'
```
[build log](https://github.com/pytorch/tutorials/actions/runs/12399019083/job/34613043785?pr=3185#step:9:5152)

```
WARNING: /var/lib/workspace/beginner_source/onnx/onnx_registry_tutorial.py failed to execute correctly: Traceback (most recent call last):
  File "/var/lib/workspace/beginner_source/onnx/onnx_registry_tutorial.py", line 127, in <module>
    assert onnx_program.model_proto.graph.node[0].domain == "custom.aten"
AssertionError
```
[build log](https://github.com/pytorch/tutorials/actions/runs/12399019083/job/34613044327?pr=3185#step:9:2057)

Until 2.6 is stable, submit fixes against the 2.6-RC-TEST branch.

### Describe your environment

* Pytorch 2.6
* 

cc @xadupre @thiagocrepaldi @titaiwangms

**Comment by titaiwangms** [comment]
cc @justinchuby
