### ISSUE TITLE
Problem running Data Loading Tutorial on Windows / pytorch-cpu 0.4.1

### ISSUE THREAD

**Issue by MattWenham** [pytorch/tutorials#326]
I am getting the following error when trying to run the [Data Loading Tutorial](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html) on Windows 10 / Anaconda / pytorch-cpu 0.4.1:

	---------------------------------------------------------------------------
	BrokenPipeError                           Traceback (most recent call last)
	<ipython-input-12-07d529c513cd> in <module>()
		 20         plt.title('Batch from dataloader')
		 21 
	---> 22 for i_batch, sample_batched in enumerate(dataloader):
		 23     print(i_batch, sample_batched['image'].size(),
		 24           sample_batched['landmarks'].size())

	~\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
		499 
		500     def __iter__(self):
	--> 501         return _DataLoaderIter(self)
		502 
		503     def __len__(self):

	~\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
		287             for w in self.workers:
		288                 w.daemon = True  # ensure that the worker exits on process exit
	--> 289                 w.start()
		290 
		291             _update_worker_pids(id(self), tuple(w.pid for w in self.workers))

	~\Anaconda3\envs\pytorch\lib\multiprocessing\process.py in start(self)
		103                'daemonic processes are not allowed to have children'
		104         _cleanup()
	--> 105         self._popen = self._Popen(self)
		106         self._sentinel = self._popen.sentinel
		107         # Avoid a refcycle if the target function holds an indirect

	~\Anaconda3\envs\pytorch\lib\multiprocessing\context.py in _Popen(process_obj)
		221     @staticmethod
		222     def _Popen(process_obj):
	--> 223         return _default_context.get_context().Process._Popen(process_obj)
		224 
		225 class DefaultContext(BaseContext):

	~\Anaconda3\envs\pytorch\lib\multiprocessing\context.py in _Popen(process_obj)
		320         def _Popen(process_obj):
		321             from .popen_spawn_win32 import Popen
	--> 322             return Popen(process_obj)
		323 
		324     class SpawnContext(BaseContext):

	~\Anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
		 63             try:
		 64                 reduction.dump(prep_data, to_child)
	---> 65                 reduction.dump(process_obj, to_child)
		 66             finally:
		 67                 set_spawning_popen(None)

	~\Anaconda3\envs\pytorch\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
		 58 def dump(obj, file, protocol=None):
		 59     '''Replacement for pickle.dump() using ForkingPickler.'''
	---> 60     ForkingPickler(file, protocol).dump(obj)
		 61 
		 62 #

	BrokenPipeError: [Errno 32] Broken pipe

The rest of my environment is as follows:

	packages in environment at C:\Users\User\Anaconda3\envs\pytorch:
	
	Name                    Version                   Build  Channel
	appdirs                   1.4.3            py36h28b3542_0    anaconda
	asn1crypto                0.24.0                   py36_0    anaconda
	attrs                     18.2.0           py36h28b3542_0    anaconda
	automat                   0.7.0                    py36_0    anaconda
	backcall                  0.1.0                    py36_0    anaconda
	blas                      1.0                         mkl    anaconda
	bleach                    2.1.4                    py36_0    anaconda
	ca-certificates           2018.03.07                    0    anaconda
	certifi                   2018.8.24                py36_1    anaconda
	cffi                      1.11.5           py36h74b6da3_1    anaconda
	cloudpickle               0.5.5                    py36_0    anaconda
	colorama                  0.3.9            py36h029ae33_0    anaconda
	constantly                15.1.0           py36h28b3542_0    anaconda
	cryptography              2.3.1            py36h74b6da3_0    anaconda
	cycler                    0.10.0           py36h009560c_0    anaconda
	cython                    0.28.5           py36h6538335_0    anaconda
	dask-core                 0.19.1                   py36_0    anaconda
	decorator                 4.3.0                    py36_0    anaconda
	entrypoints               0.2.3                    py36_2    anaconda
	freetype                  2.9.1                ha9979f8_1    anaconda
	html5lib                  1.0.1                    py36_0    anaconda
	hyperlink                 18.0.0                   py36_0    anaconda
	icc_rt                    2017.0.4             h97af966_0    anaconda
	icu                       58.2                 ha66f8fd_1    anaconda
	idna                      2.7                      py36_0    anaconda
	imageio                   2.4.1                    py36_0    anaconda
	incremental               17.5.0                   py36_0    anaconda
	intel-openmp              2019.0                      118    anaconda
	ipykernel                 4.9.0                    py36_1    anaconda
	ipython                   6.5.0                    py36_0    anaconda
	ipython_genutils          0.2.0            py36h3c5d0ee_0    anaconda
	ipywidgets                7.4.1                    py36_0    anaconda
	jedi                      0.12.1                   py36_0    anaconda
	jinja2                    2.10                     py36_0    anaconda
	jpeg                      9c                hfa6e2cd_1001    conda-forge
	jsonschema                2.6.0            py36h7636477_0    anaconda
	jupyter                   1.0.0                    py36_7    anaconda
	jupyter_client            5.2.3                    py36_0    anaconda
	jupyter_console           5.2.0                    py36_1    anaconda
	jupyter_core              4.4.0                    py36_0    anaconda
	kiwisolver                1.0.1            py36h6538335_0    anaconda
	libpng                    1.6.34               h79bbb47_0    anaconda
	libsodium                 1.0.16               h9d3ae62_0    anaconda
	libtiff                   4.0.9                h36446d0_2    anaconda
	m2w64-gcc-libgfortran     5.3.0                         6
	m2w64-gcc-libs            5.3.0                         7
	m2w64-gcc-libs-core       5.3.0                         7
	m2w64-gmp                 6.1.0                         2
	m2w64-libwinpthread-git   5.0.0.4634.697f757               2
	markupsafe                1.0              py36hfa6e2cd_1    anaconda
	matplotlib                2.2.3            py36hd159220_0    anaconda
	mistune                   0.8.3            py36hfa6e2cd_1    anaconda
	mkl                       2019.0                      118    anaconda
	mkl_fft                   1.0.4            py36h1e22a9b_1    anaconda
	mkl_random                1.0.1            py36h77b88f5_1    anaconda
	msys2-conda-epoch         20160418                      1
	nbconvert                 5.3.1                    py36_0    anaconda
	nbformat                  4.4.0            py36h3a5bc1b_0    anaconda
	networkx                  2.1                      py36_0    anaconda
	notebook                  5.6.0                    py36_0    anaconda
	numpy                     1.15.1           py36ha559c80_0    anaconda
	numpy-base                1.15.1           py36h8128ebf_0    anaconda
	olefile                   0.46                     py36_0    anaconda
	openssl                   1.0.2p               hfa6e2cd_0    anaconda
	pandas                    0.23.4           py36h830ac7b_0    anaconda
	pandoc                    2.2.3.2                       0    anaconda
	pandocfilters             1.4.2                    py36_1    anaconda
	parso                     0.3.1                    py36_0    anaconda
	pickleshare               0.7.4            py36h9de030f_0    anaconda
	Pillow                    5.2.0                     <pip>
	pillow                    5.2.0            py36h08bbbbd_0    anaconda
	pip                       10.0.1                   py36_0    anaconda
	prometheus_client         0.3.1            py36h28b3542_0    anaconda
	prompt_toolkit            1.0.15           py36h60b8f86_0    anaconda
	pyasn1                    0.4.4            py36h28b3542_0    anaconda
	pyasn1-modules            0.2.2                    py36_0    anaconda
	pycparser                 2.18                     py36_1    anaconda
	pygments                  2.2.0            py36hb010967_0    anaconda
	pyopenssl                 18.0.0                   py36_0    anaconda
	pyparsing                 2.2.0                    py36_1    anaconda
	pyqt                      5.9.2            py36ha878b3d_0    anaconda
	python                    3.6.6                hea74fb7_0    anaconda
	python-dateutil           2.7.3                    py36_0    anaconda
	pytorch-cpu               0.4.1           py36_cpuhe774522_1    pytorch
	pytz                      2018.5                   py36_0    anaconda
	pywavelets                1.0.0            py36h452e1ab_0    anaconda
	pywin32                   223              py36hfa6e2cd_1    anaconda
	pywinpty                  0.5.4                    py36_0    anaconda
	pyzmq                     17.1.2           py36hfa6e2cd_0    anaconda
	qt                        5.9.6            vc14h1e9a669_2
	qtconsole                 4.3.1            py36h99a29a9_0    anaconda
	scikit-image              0.14.0           py36h6538335_1    anaconda
	scipy                     1.1.0            py36h4f6bf74_1    anaconda
	send2trash                1.5.0                    py36_0    anaconda
	service_identity          17.0.0           py36h28b3542_0    anaconda
	setuptools                40.2.0                   py36_0    anaconda
	simplegeneric             0.8.1                    py36_2    anaconda
	sip                       4.19.12          py36h6538335_0    anaconda
	six                       1.11.0                   py36_1    anaconda
	six                       1.11.0                    <pip>
	sqlite                    3.24.0               h7602738_0    anaconda
	terminado                 0.8.1                    py36_1    anaconda
	testpath                  0.3.1            py36h2698cfe_0    anaconda
	tk                        8.6.8                hfa6e2cd_0    anaconda
	toolz                     0.9.0                    py36_0    anaconda
	torchvision               0.2.1                     <pip>
	tornado                   5.1              py36hfa6e2cd_0    anaconda
	traitlets                 4.3.2            py36h096827d_0    anaconda
	twisted                   18.7.0           py36hfa6e2cd_1    anaconda
	vc                        14.1                 h21ff451_3    anaconda
	vs2015_runtime            15.5.2                        3    anaconda
	wcwidth                   0.1.7            py36h3d5aa90_0    anaconda
	webencodings              0.5.1                    py36_1    anaconda
	wheel                     0.31.1                   py36_0    anaconda
	widgetsnbextension        3.4.1                    py36_0    anaconda
	wincertstore              0.2              py36h7fe50ca_0    anaconda
	winpty                    0.4.3                         4    anaconda
	zeromq                    4.2.5                he025d50_1    anaconda
	zlib                      1.2.11               h8395fce_2    anaconda
	zope                      1.0                      py36_1    anaconda
	zope.interface            4.5.0            py36hfa6e2cd_0    anaconda

**Comment by MattWenham** [comment]
Apologies, I didn't check the main repo issues closely enough. Setting `num_workers=0` in the dataloader has fixed it.

**Comment by vedanthpadigelwar** [comment]
the update is not updated on the tutorials page of the PyTorch can someone update it, please.
