### ISSUE TITLE
Improve Torchscript tutorial

### ISSUE THREAD

**Issue by bhack** [pytorch/tutorials#352]
I think that it is better to track some tutorial improvements in https://github.com/pytorch/pytorch/issues/13245#issuecomment-435165566 here.
It could also be useful to know if there is any multiprocess/dataparallel for python jit load use case.

**Comment by bhack** [comment]
https://github.com/pytorch/pytorch/issues/13898#issuecomment-438657077

**Comment by bhack** [comment]
Users are looking for also how to free the GPU cache in c++. See https://discuss.pytorch.org/t/how-to-free-gpu-memory-of-at-tensor-in-aten-c/18408

**Comment by bhack** [comment]
@goldsborough I've tried to extend the Torchscript tutorial with a model on GPU using a loop for `output= module->forward(inputs).toTensor();` and then moving the output tensor back to CPU with a `Tensor.to(..)`. 
With the Nvidia profiler I'am seeing that this loop cannot overlap kernel computation and device to host memory transfer (.to operator).  Is there a suggested way with Aten to overlap forward and moving the output tensor back to CPU? From the profiling seems that the internals are using a single cuda stream.

**Comment by goldsborough** [comment]
There is a `non_blocking` argument on `to(...)`. Please file issues on the main repo for these things.

**Comment by bhack** [comment]
@goldsborough Done at https://github.com/pytorch/pytorch/issues/15006. But I still think that some basic operation need to be documented here in the tuorial so that we will have less "noise" or false positive issue in the main repo.

**Comment by goldsborough** [comment]
I think the tutorial should be kept simple. Maybe the https://pytorch.org/cppdocs/notes/faq.html is a good place for this (FAQ -> reduce noise of frequently asked questions).

**Comment by bhack** [comment]
Yes but this are very standard use cases like starting from CPU input, inference on GPU, and consume the output back on CPU. I don't see anything more standard this kind of loop for inference.

**Comment by holly1238** [comment]
New intro to torchscript tutorial can be found here: https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html
