### ISSUE TITLE
Theme issues

### ISSUE THREAD

**Issue by chsasank** [pytorch/tutorials#371]
1. Sidebar is scrolling along with the image
2. labels of sphinx gallery boxes are not working as expected
3. tooltips are not being shown

These issues were not present when I checked 1/2 weeks back.

![screenshot 2018-12-05 at 15 41 27](https://user-images.githubusercontent.com/9305875/49506538-53db3500-f8a4-11e8-9c3e-0e43cfd81a41.png)

4. Please show complete TOC on right instead of only the current page. 

How it used to look like:
![screenshot 2018-12-05 at 16 05 11](https://user-images.githubusercontent.com/9305875/49507989-a538f380-f8a7-11e8-972b-26965710ce20.png)

How it looks like now:
![screenshot 2018-12-05 at 16 05 25](https://user-images.githubusercontent.com/9305875/49507987-a4a05d00-f8a7-11e8-8a4e-ffc1068c36fd.png)

New TOC is not very intuitive for beginners.

I see that this might be being worked on already: 
https://github.com/pytorch/tutorials/commit/dee72231601f31a4dc1822adef54530608127b92

**Comment by brianjo** [comment]
Thanks for the feedback Sasank. The label issue you see has to do with a mis-sized graphic and should be fixed as soon as we can land the next build. I'll pass the other issues on to the team.

**Comment by JoelMarcey** [comment]
The theme has been fixed and updated. Thank you for raising this. Let us know if you see any more issues.
