### ISSUE TITLE
'torchaudio' module is missing

### ISSUE THREAD

**Issue by 9bow** [pytorch/tutorials#409]
An `ImportError` occurs while building tutorials.
```
  ImportError: No module named 'torchaudio'
```

I thinks `torchaudio` should be included in the `requirements.txt` but only exist in [jenkins build script](https://github.com/pytorch/tutorials/blob/8a9f9576d1ec737489dfd973f62c83df002c8b61/.jenkins/build.sh#L49)

How about add `torchaudio` in `requirements.txt`?

**Comment by 9bow** [comment]
`pip install git+https://github.com/pytorch/audio` works well, but need to install `sox` dependency.
So should install `libsox-dev` for ubuntu, and maybe `sox` and `sox-devel` for macOS and CentOS/RHEL respectively. (not tested).

How about add `git+https://github.com/pytorch/audio` in the `requirements.txt` and list those dependencies in the `README.md`?

**Comment by ericnakagawa** [comment]
Hi 9bow, I'd like to resolve this issue. How exactly are you building tutorials?

**Comment by 9bow** [comment]
Hello, @ericnakagawa 
I just ran `make docs` after git clone. (w/ ubuntu 16.04 + python 3.6)
I solved this issue quite simple way (mentioned above), but wonder how the committers thought about this issue. Could you review if I PR this issue?

**Comment by jlin27** [comment]
`torchaudio` has now been added to requirements.txt
We were waiting on a stable version before adding :)
