### ISSUE TITLE
Numerically unstable initialized values for uninitialized tensors?

### ISSUE THREAD

**Issue by madcarrot** [pytorch/tutorials#41]
I was trying to follow the tutorial when I noticed that if I just create an "uninitialized matrix", its values are not numerically stable. I guess since we will have to initialize the matrix later, it doesn't really matter, but I'm just wondering if this is intentional.

I'm running pyTorch with anaconda python 3.6, CUDA v8 on Linux.

```python
from __future__ import print_function
import torch
```

```python
x = torch.Tensor(5, 3)
```

```python
x = torch.rand(5, 3)
```

```python
x
```

    
    -1.6775e+31  4.5895e-41  4.0929e-37
     0.0000e+00  0.0000e+00  0.0000e+00
     0.0000e+00  0.0000e+00  0.0000e+00
     0.0000e+00  0.0000e+00  0.0000e+00
     0.0000e+00  0.0000e+00  0.0000e+00
    [torch.FloatTensor of size 5x3]

```python
y = torch.Tensor(5, 3); y
```

    
    -1.6775e+31  4.5895e-41  4.2770e-37
     0.0000e+00  0.0000e+00  0.0000e+00
     0.0000e+00  0.0000e+00  0.0000e+00
     0.0000e+00  0.0000e+00  0.0000e+00
     0.0000e+00  0.0000e+00  0.0000e+00
    [torch.FloatTensor of size 5x3]

```python
x * y
```

    
    inf   0   0
      0   0   0
      0   0   0
      0   0   0
      0   0   0
    [torch.FloatTensor of size 5x3]

**Comment by soumith** [comment]
`y = torch.Tensor(5, 3)` will create a Tensor with uninitialized memory. The memory can contain any garbage, as it is uninitialized. This is intentional. If you want zeroed Tensors, you can use `torch.zeros(5, 3)`
