### ISSUE TITLE
TypeError : filename should be a str in beginner/nn_tutorial.py

### ISSUE THREAD

**Issue by 9bow** [pytorch/tutorials#410]
I got a `TypeError` error in `beginner_source/nn_tutorial.py` while building tutorials with Python 3.5 on Ubuntu 16.04.

It seems like the type of parameter passed in `gzip.open()` in ["beginner_source/nn_tutorial.py(L64)"](https://github.com/pytorch/tutorials/blob/master/beginner_source/nn_tutorial.py#L64) should be converted.

The error message is like below:
```
WARNING: /home/ubuntu/tutorials/beginner_source/nn_tutorial.py failed to execute correctly: Traceback (most recent call last):
 File "/home/ubuntu/tutorials/beginner_source/nn_tutorial.py", line 64, in <module>
   with gzip.open(PATH / FILENAME, "rb") as f:
 File "/usr/lib/python3.5/gzip.py", line 57, in open
   raise TypeError("filename must be a str or bytes object, or a file")
TypeError: filename must be a str or bytes object, or a file
```

I think using `(PATH / FILENAME).as_posix()` more suitable.

If this error is visible to everyone, can I fix it?

**Comment by soumith** [comment]
cc: @brianjo
