### ISSUE TITLE
ValueError low>=high in RandomCrop

### ISSUE THREAD

**Issue by Demfier** [pytorch/tutorials#411]
Hello everyone,

First off, thanks for such detailed PyTorch tutorials! Recently, I was going through the data loading and processing tutorial [here](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html). Maybe there's some misunderstanding from my side but in `beginner_source/data_loading_tutorial.py`, for class `RandomCrop`, when the value of `output_size` is greater than original image size, it throws a `ValueError: low >= high` as `h < new_h` and `w < new_w`.

So, can I get a confirmation as to whether or not this is a bug? If yes, I would be happy to fix it. 

(**Note**: To reproduce the error try changing value of `crop` [here](https://github.com/pytorch/tutorials/blob/master/beginner_source/data_loading_tutorial.py#L304) to something greater such as `crop = RandomCrop(224)`)

Ping @chsasank 

Thanks,
Gaurav

**Comment by chsasank** [comment]
This is not a bug, you should not be extract a crop larger than the image itself.
