### ISSUE TITLE
'BrokenPipeError: [Errno 32] Broken pipe' in 'cifar10_tutorial.py' if running on Windows.

### ISSUE THREAD

**Issue by gaojxx** [pytorch/tutorials#412]
There may be an error in 'cifar10_tutorial.py' if running on Windows, which is 'BrokenPipeError: [Errno 32] Broken pipe'.

Setting the parameter ‘new_workers’ of torch.utils.data.DataLoader() to zero, could solve the problem temporarily.

**Comment by SylvainChague** [comment]
Same issue trying to run the 'cifar10_tutorial.py' on Windows 10. @gaojxx 's fix works fine.

**Comment by jlin27** [comment]
Added a note in this PR: https://github.com/pytorch/tutorials/pull/646
