### ISSUE TITLE
Question in lstm hidden layer init

### ISSUE THREAD

**Issue by shboy** [pytorch/tutorials#416]
below is one snippet from pytorch totorial
https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html#sphx-glr-beginner-nlp-sequence-models-tutorial-py
![image](https://user-images.githubusercontent.com/24290262/51179602-06210600-1901-11e9-96a5-36343d7a895e.png)

Could anyone tell me why the hidden layer here is initialized to have two " randn(1, 1, 3)" ?  I suppose it should be one by the way...

**Comment by soumith** [comment]
one of them is h0 and the other is c0.
See https://pytorch.org/docs/stable/nn.html?highlight=nn%20lstm#torch.nn.LSTM for what h0 and c0 are, in the "inputs" section
