### ISSUE TITLE
Error in "Classifying Names with a Character-Level RNN" code

### ISSUE THREAD

**Issue by TrigonaMinima** [pytorch/tutorials#421]
There's an error when you run the code section just before [this linked header](https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html#training). The relevant code part is

```
input = lineToTensor('Albert')
hidden = torch.zeros(1, n_hidden)

output, next_hidden = rnn(input[0], hidden)
print(output)
```

In this, the error is in 4th line where, ```input[0]``` should be reshaped to the ```(1, n_letters)```. What works for me is-

```
input = letter2tensor('Albert')
hidden = torch.zeros(1, n_hidden)

output, next_hidden = rnn(input[0].view(1, n_letters), hidden)
print(output)
```

My torch version is ```1.0.0```.

**Comment by jlin27** [comment]
Hi @TrigonaMinima - Thanks for reaching out. Can you send us a snippet of the error are you getting?

**Comment by TrigonaMinima** [comment]
@jlin27 it's been long. I think error was shape mismatch.
