### ISSUE TITLE
Formulas are tiny!

### ISSUE THREAD

**Issue by danaugrs** [pytorch/tutorials#425]
All formulas are tiny and and unreadable from a normal distance (in both Chrome and Firefox). See the excerpt below:

![image](https://user-images.githubusercontent.com/5261448/51801444-f79ded00-2224-11e9-94b5-9d70f2ad1841.png)

**Comment by ericnakagawa** [comment]
I believe we fixed this font issue. Please re-open if the issue persists.

**Comment by AndrewPaulChester** [comment]
I'm still seeing the same issue on Chrome (Version 74.0.3729.131 (Official Build) (64-bit)) on Ubuntu 18.04. It's working fine for me in Firefox (66.0.4). 

Let me know if there's any other details I can provide.
