### ISSUE TITLE
Where is Variable?

### ISSUE THREAD

**Issue by yiyuezhuo** [pytorch/tutorials#44]
In `Reinforcement (Q-)Learning with PyTorch2`, the section  `Training hyperparameters and utilities`  claim the cell providing `Variable` which is "a simple wrapper around torch.autograd". But I can't found it in the cell. Then I encounter `NameError: name 'Variable' is not defined`, anyway I import Variable from `torch.autograd` instead. So where is Variable? Or how can I implement it by scratch?

**Comment by soumith** [comment]
it's right in the first Cell!

`from torch.autograd import Variable`

<img width="944" alt="screen shot 2017-03-06 at 12 31 03 am" src="https://cloud.githubusercontent.com/assets/1310570/23597820/339a9652-0204-11e7-980c-7705251d502c.png">

**Comment by SizheWei** [comment]
> it's right in the first Cell!
> 
> `from torch.autograd import Variable`
> 
> <img alt="screen shot 2017-03-06 at 12 31 03 am" width="944" src="https://cloud.githubusercontent.com/assets/1310570/23597820/339a9652-0204-11e7-980c-7705251d502c.png">

However, after adding this line, I got another error:

TypeError: 'type' object is not subscriptable

How can I solve it?

**Comment by rupjyotiBaruah** [comment]
thanks
