### ISSUE TITLE
Add 'Open in Colab' Button to Tutorial Code 

### ISSUE THREAD

**Issue by pynchmeister** [pytorch/tutorials#441]
Is it possible to edit the downloadable Jupyter notebooks at the bottom of each 60-minute blitz section? In a utopian scenario there would be a button at the top of each file, allowing the user to 'Open in Colab'. If this button was present the user would fix the code so that each cell was ran with the output visible.

Here is an example with Keras, to explicate what I mean. There are some uploaded PyTorch Jupyter Notebook files in the same repository (along with the Keras Jupyter Notebooks) to gain a more comprehensive perspective.

https://github.com/PhillySchoolofAI/DL-Libraries/blob/master/KerasFunctionalAPI.ipynb

**Comment by brianjo** [comment]
Hey Harris, we've been working on this for a while and it's live today. Take a look and let us know how it works for you. Cheers!

**Comment by pynchmeister** [comment]
Hey @brianjo , you are the best! How did you manage to do that?
