### ISSUE TITLE
Typo in beginner tutorial figure

### ISSUE THREAD

**Issue by SophiaGoldberg** [pytorch/tutorials#447]
There is a typo in the figure of the network architecture at the top of https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#define-the-network. 

Where the figure says `C5: layer 120` it should say `F5: layer 120`. This should be corrected in the link https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#define-the-network and should be referenced in` tutorials/beginner_source/blitz/` in the `neural_networks_tutorial.py` script and the corresponding `.ipynb` notebook both of which are downloadable from
https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#define-the-network.

**Comment by soumith** [comment]
thanks for reporting, yes you are right. Modifying the figure is a bit painful though, we dont have the vectorized source.

**Comment by SophiaGoldberg** [comment]
No problem! Alternatively I suppose you could add a footnote comment to the figure.

**Comment by jlin27** [comment]
Thanks for pointing that out @SophiaGoldberg. Corrected the label in this PR: https://github.com/pytorch/tutorials/pull/637
