### ISSUE TITLE
THFloatTensor_add(tensor,tensor,float)

### ISSUE THREAD

**Issue by cojocchen** [pytorch/tutorials#45]
I tried the code in the c code tutorial. It seems the definition of THFloatTensor_add is different in the version of pytorch I used. The input2 should be a single float number in the version I installed using conda. I modified the my_lib.c and my_lib.h as following to pass the compile.

my_lib.h:
`
int my_lib_add_forward(THFloatTensor *input1, float input2, THFloatTensor *output);
`

my_lib.c:
`
int my_lib_add_forward(THFloatTensor *input1, float input2, THFloatTensor *output)
{
    THFloatTensor_resizeAs(output, input1);
    THFloatTensor_add(output, input1, input2);
    return 1;
}
`

**Comment by apaszke** [comment]
Yes, it would work if it was `cadd` instead of `add`. It's a typo.

**Comment by cojocchen** [comment]
Thanks for the reply.

Directly replace add with cadd will not work. This is what I found for cadd:
`TH_API void THTensor_(cadd)(THTensor *r_, THTensor *t, real value, THTensor *src);`

I cannot find the source code for this function, but I guess cadd is weighted sum and the 3rd variable is the weight. Following code works for me:
`THFloatTensor_cadd(output, input1, 1, input2);`

I also noticed some typo in the main.py. But should be easy to fix:
`import torch`
...
`         super(MyNetwork, self).__init__()`
`         self.add=MyAddModule()`

**Comment by apaszke** [comment]
Yes, you're right. I forgot about the additional scale argument :)

Can you please send a PR?

**Comment by soumith** [comment]
this is now fixed.

**Comment by bdotgradb** [comment]
@soumith, did you mean that the tutorial webpage had been updated or an underlying change made so that it would work as presented? I just ran into this issue following the tutorial with a fresh pytorch and cffi install (cuda 8.0, python 2.7, ubuntu 16.04).

**Comment by soumith** [comment]
hey @bdotgradb , i actually meant that i modified https://github.com/pytorch/extension-ffi/blob/master/script/src/my_lib.c

I didn't realize that I didn't update the tutorial, updating the code in the tutorial block now.
