### ISSUE TITLE
Broken Pipe in data_loading_tutorial

### ISSUE THREAD

**Issue by dpthayer** [pytorch/tutorials#457]
Running on Windows 10 using rtx 2060  cuda 10.1  
Running your data_loading_tutorial in Jupyter notebook and in the last executable codeblock I am getting 

BrokenPipeError: [Errno 32] Broken pipe
thrown from Line 60 in fastai\lib\multiprocessing\reduction.py
function def dump. line 60 call to ForkingPickle(file,protocol).dump(obj)

**Comment by KuleleHu** [comment]
Yeah, I also encounter this. To avoid this error, comment parameter num_workers in DataLoader initialization, like below: 
dataloader = DataLoader(transformed_dataset, batch_size=4,  shuffle=True) # num_workers=4

**Comment by jlin27** [comment]
Hi @dpthayer  - Are you still getting this issue on the current version?

**Comment by AntonDemchenko** [comment]
I have the same problem.

Windows 8.1
Pytorch 1.4.0+cpu
