### ISSUE TITLE
how can i remove the layers in model.

### ISSUE THREAD

**Issue by wangjue-wzq** [pytorch/tutorials#458]
I want to use the googlenet model to do finetuing, remove the fc layer, and then add other layers.

**Comment by jlin27** [comment]
Hi @422301949 - Thanks for reaching out! Are you referring to a specific tutorial or are you asking just in general how to do this? If this is a general question, I'd highly suggest posting on the PyTorch Discussion Form (https://discuss.pytorch.org/) where our highly active community can provide more insight. This repo is specifically for issues related to the PyTorch tutorials.
