### ISSUE TITLE
Inappropriate example code of vector-Jacobian product in  (AUTOGRAD: AUTOMATIC DIFFERENTIATION) 

### ISSUE THREAD

**Issue by guixianjin** [pytorch/tutorials#459]
I want to check the vector-Jacobian product. But in the example code the x is randomly generated and the the function relation between x and y is not clear.  So how can I check if I correctly understand the vector-Jacobian product ?  Can you improve it ?

**Comment by wangliangster** [comment]
Confused me also

**Comment by holly1238** [comment]
See new autograd tutorial as part of the Learn the Basics series (https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html)
