### ISSUE TITLE
The GRU model in pytorch can deal with sequential inputs, why feed one word at a time instead of passing a sentence altogether

### ISSUE THREAD

**Issue by CSUN1997** [pytorch/tutorials#464]
I noticed that in the documentation of pytorch GRU, the input shape should be (seq_len, batch, input_size), thus the input ought to be a sequence and the model will deal with the sequence inside itself. But in this notebook, the author passes a tensor only of length one in each iteration in function `train`. I mean if the model can deal with sequential inputs, why not just feed a sequence of sentence to it?

This is my first time to start an issue on github, please forgive me if there is anything wrong.

**Comment by jlin27** [comment]
Hi @AllenIverSunn - Thanks for reaching out. Can you please link to the specific tutorial you're referencing?
