### ISSUE TITLE
Small error in comment in DQN tutorial code

### ISSUE THREAD

**Issue by RaviTej310** [pytorch/tutorials#466]
In line 484 in this tutorial: https://github.com/pytorch/tutorials/blob/master/intermediate_source/reinforcement_q_learning.py, it says `# Perform one step of the optimization (on the target network)`, but I think it should be `# Perform one step of the optimization (on the policy network)`, since `optimize_model()` calls `optimizer` which is defined as `
optimizer = optim.RMSprop(policy_net.parameters())` on line 335. Please correct me if I am wrong.

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1286
