### ISSUE TITLE
<torch/torch.h> should be <torch/extension.h> in cpp extensions

### ISSUE THREAD

**Issue by ezyang** [pytorch/tutorials#473]
https://pytorch.org/tutorials/advanced/cpp_extension.html still uses the old include which will emit a warning.

Forwarded from: https://github.com/pytorch/pytorch/issues/18718

cc @SPark9625

**Comment by jlin27** [comment]
Looks like it's been cleaned up in this PR: https://github.com/pytorch/tutorials/pull/483/files
Feel free to close if not. Thanks!
