### ISSUE TITLE
Example with torch.empty in What is PyTorch? is misleading

### ISSUE THREAD

**Issue by alexchapeaux** [pytorch/tutorials#476]
In this [example](https://github.com/pytorch/tutorials/blob/master/beginner_source/blitz/tensor_tutorial.py) the output of a `torch.empty` call looks the same result I would obtain with `torch.zeros`, while it should be filled with garbage values.

This might be misleading to beginners.

**Comment by jlin27** [comment]
Hi @alexchapeaux - `torch.empty` actually initializes a tensor with "uninitialized" values. An uninitialized matrix will have _some_ value, but not predictable ones. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.
