### ISSUE TITLE
dcgan_faces_tutorial.py: RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by li0128** [pytorch/tutorials#477]
dcgan_faces_tutorial.py: RuntimeError: CUDA error: out of memory
ssh://anaconda3/bin/python3.7 -u /dcgan_faces_tutorial.py
Random Seed:  999
Traceback (most recent call last):
  File "/dcgan_faces_tutorial.py", line 268, in <module>
    plt.imshow(np.transpose(vutils.make_grid(real_batch[0].to(device)[:64], padding=2, normalize=True).cpu(),(1,2,0)))
RuntimeError: CUDA error: out of memory

Process finished with exit code 1

**Comment by jlin27** [comment]
Hi @li0128 - Can you double-check that your computer has the right pytorch version for you CUDA version? There as a similar CUDA out of memory issue discussed here: https://github.com/pytorch/pytorch/issues/18999#issuecomment-502845412

If not, could you please share more info about your setup and what steps it takes to replicate your error? Thank you!
