### ISSUE TITLE
different results

### ISSUE THREAD

**Issue by taylerpauls** [pytorch/tutorials#484]
HI, i copied to code exactly and and ran with all the appropriate downloads and im not achieving the resutls stated with 40 epochs. the loss stays at around 2.2 with test accuracy of 100/837 .. around 11%.. 

is there something i need to change to get over 50% accuracy ?

**Comment by jlin27** [comment]
Hi @taylerpauls  - Thanks for reaching you! Can you please link us to which tutorial and section you are referencing? Additionally, for tutorial concept questions I'd suggest posting on the Python Discussion Forum (https://discuss.pytorch.org/) where our Python developer community can get back to you with a quicker turnaround. This github issue tracker is primarily to report any bugs or change suggestions.
