### ISSUE TITLE
Initialize with t7 files?

### ISSUE THREAD

**Issue by Yuliang-Zou** [pytorch/tutorials#5]
If I trained a model with Torch and stored the weights using t7 format. Is it possible to use this as initialization in pytorch? Thank you.

**Comment by soumith** [comment]
we have a `load_lua` as part of `torch.serialization` that can load any t7 files with Tensors and some neural networks.

Follow the `load_lua` variable for an example here:
https://github.com/pytorch/pytorch/blob/master/test/test_utils.py#L18

**Comment by Yuliang-Zou** [comment]
Thanks!
