### ISSUE TITLE
why did the 60-minute tutorial disappear？

### ISSUE THREAD

**Issue by flyingmoth** [pytorch/tutorials#50]

**Comment by soumith** [comment]
should be back up in a few minutes. sorry about that.

**Comment by chsasank** [comment]
Please use https://chsasank.github.io/pytorch-tutorials/beginner/deep_learning_60min_blitz.html meanwhile

**Comment by flyingmoth** [comment]
thank you very much!

**Comment by soumith** [comment]
fixed now
