### ISSUE TITLE
%%%%%%INVISIBLE_CODE_BLOCK%%%%%% shows up in rendered docs

### ISSUE THREAD

**Issue by ezyang** [pytorch/tutorials#505]
Example: https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py

**Comment by jlin27** [comment]
Notes: 

Code block added in this PR: https://github.com/pytorch/tutorials/pull/366
I'm assuming it's related to this issue: https://github.com/pytorch/pytorch/issues/6548
Reached out to Will Feng to see if it's still an issue/can be removed from the .py

**Comment by yf225** [comment]
If we change this line https://github.com/pytorch/tutorials/blob/master/.jenkins/remove_invisible_code_block_from_html.py#L11 from `highlight-python` to `highlight-default` the invisible code block should disappear.

**Comment by jlin27** [comment]
Fixed in this PR: https://github.com/pytorch/tutorials/pull/525
Thanks @yf225!
