### ISSUE TITLE
Broken Simple Tutorial Example

### ISSUE THREAD

**Issue by sbodenstein** [pytorch/tutorials#51]
I have just installed PyTorch, and this example doesn't work: http://pytorch.org/tutorials/beginner/pytorch_with_examples.html#pytorch-variables-and-autograd

Running the example returns:
```
0 26220132.0
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-44-6cc21ebb6010> in <module>()
     36 
     37   # Manually zero the gradients before running the backward pass
---> 38   w1.grad.data.zero_()
     39   w2.grad.data.zero_()
     40 

AttributeError: 'NoneType' object has no attribute 'data'
```
as `w1.grad.data` doesn't seem to be defined.

**Comment by chsasank** [comment]
Weirdly enough, it runs fine for me. 
How did you run the example?

May be update pytorch and retry?

**Comment by spro** [comment]
You're probably running into the same problem as https://github.com/jcjohnson/pytorch-examples/pull/3/commits/c7e345e30ea09b8800a11f22c16742c07a6a73dd

**Comment by chsasank** [comment]
#52 fixes the issue.
