### ISSUE TITLE
Korean Wikipedia

### ISSUE THREAD

**Issue by EggCookies** [pytorch/tutorials#510]
Hello. We are Student team from Kwangwoon University.
We want to let you know that we have translated a new wiki document about 'PyTorch' for the school assignment.

And not just translating, but also we add some more information to Korean Wikipedia documents.

You can find it in this link.

[English Wiki PyTorch](https://en.wikipedia.org/wiki/PyTorch)
[Korean Wiki PyTorch](https://ko.wikipedia.org/wiki/PyTorch)

Thanks for the reading and have a nice day.

PS: we are gonna make new document for 'namu Wiki' (well-known korean wiki).

**Comment by soumith** [comment]
thank you very much!
