### ISSUE TITLE
[FR] data download script is needed for jupyter notebook and google colab

### ISSUE THREAD

**Issue by sakaia** [pytorch/tutorials#516]
When CI process runs for the tutorials, the data sets are downloaded by download section of Makefile. 
But it does not supplied for jupyter notebook and Google Colab.
It is better to add data download script.

Ref. 
  https://github.com/pytorch/tutorials/blob/master/Makefile#L27

**Comment by 9bow** [comment]
Hello, I am the one who suggested the Download section in the Makefile. (#384)

At the time of that issue, Colab or Notebook did not exist, and the primary goal was to reduce waste (of time and traffic) from getting downloads every time while building tutorials.

I think Colab or Notebook run locally, so it looks like we need to download the data files through a separate Python script (as a Jupyter Notebook) that take charge of the Download section of the Makefile.

Did you mean this? If that's true and someone else does not have a plan on this issue, let me think about how.

**Comment by jlin27** [comment]
Hi @sakaia  and @9bow - Thank you for the suggestions and insights into improvements on the download experience. We're working on cleaning up our open issues and have made note of this suggestion. If you have any further recommendations, please feel free to re-open the issue. Thanks!
