### ISSUE TITLE
The pipelined example of model_parallel_tutorial.py got worse performance

### ISSUE THREAD

**Issue by cofiiwu** [pytorch/tutorials#517]
I download the example model_parallel_tutorial.py and execute it on my server. However the results don't match the results in the tutorial. I make sure the two GPUs are dedicate to the example. Is there any missed condition?
Note. The two GPUs are Telsa P100 connected with NVLINK.

![mp_vs_rn](https://user-images.githubusercontent.com/40190145/58627105-fc74c980-8308-11e9-8a8c-24175a0509ae.png)
![split_size_tradeoff](https://user-images.githubusercontent.com/40190145/58627107-fc74c980-8308-11e9-9e72-cf56f612f978.png)
![mp_vs_rn_vs_pp](https://user-images.githubusercontent.com/40190145/58627108-fd0d6000-8308-11e9-8abf-f72908050cb2.png)
@mrshenli

**Comment by cofiiwu** [comment]
I found the cause is the unsuitable split_size. The performance is improved after setting the split size to 40.
Thanks.
![mp_vs_rn_vs_pp](https://user-images.githubusercontent.com/40190145/58629909-588f1c00-8310-11e9-8ba3-edea36f1764b.png)
![split_size_tradeoff](https://user-images.githubusercontent.com/40190145/58629913-59c04900-8310-11e9-8023-b20ca7ab910a.png)

**Comment by mrshenli** [comment]
The performance numbers heavily depend on your environment. Using the curve to find the best split size is the right approach. :)

Let me update the post to highlight that.
