### ISSUE TITLE
Enhancement: cannot run downloaded tutorial scripts

### ISSUE THREAD

**Issue by antran89** [pytorch/tutorials#53]
Hi,
After downloading tutorial scripts, I cannot run the Python scripts such as `autograd_tutorial.py`. They have the following error:
```
SyntaxError: Non-ASCII character '\xe2' in file /home/tranlaman/Desktop/pytorch-workspace/tutorials/pytorch-60mins/autograd_tutorial.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details.
```

**Comment by chsasank** [comment]
Can you please check if [autograd_tutorial.txt](https://github.com/pytorch/tutorials/files/900019/autograd_tutorial.txt) gives the error?

**Comment by antran89** [comment]
@chsasank Thanks, it does not matter to me. Just report a problem. I run the Python notebook already.
I really enjoy your tutorials on PyTorch Deep Learning for NLP.

**Comment by chsasank** [comment]
Thanks. I just want you to confirm that there is no error when you run that
file in your environment. If that is the case, I'll push the fixes.

**Comment by antran89** [comment]
@chsasank Yes, it can run!

**Comment by chsasank** [comment]
Thanks for reporting the issue. It's been fixed.
