### ISSUE TITLE
wrong kernel_size in tutorial

### ISSUE THREAD

**Issue by edueva** [pytorch/tutorials#531]
Convolution kernel sizes in ['Define the network' section of tutorial](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#sphx-glr-beginner-blitz-neural-networks-tutorial-py) differ from ones at colab page and must be 5:
self.conv1 = nn.Conv2d(1, 6, 5)
self.conv2 = nn.Conv2d(6, 16, 5),
as image size is shrunk from 32 * 32 to 28 * 28.

**Comment by brianjo** [comment]
Thanks, I made an edit and posted a PR. I'll merge this when it passes tests.

**Comment by pandysong** [comment]
Image size is shrunk from 32 * 32 to 28 * 28 with Kernel Size 5
It becomes 14 * 14 after pooling.
Image size is shrunk from 14 * 14 to 12 * 12 with Kernel Size 3
Then it becomes 6 * 6 after pooling.

Hence the first Kernel size is 5 and second kernel size is 3.

**Comment by edueva** [comment]
> Thanks, I made an edit and posted a PR. I'll merge this when it passes tests.

The kernel sizes are still wrong in example code at tutorial web-page here: https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#sphx-glr-beginner-blitz-neural-networks-tutorial-py
This is what you have at image (kernel size 5 for both convolutions):
![image](https://user-images.githubusercontent.com/44193159/60892671-328e5d00-a268-11e9-88df-6a9aa802cb24.png)
And this is what you have in example code:
![image](https://user-images.githubusercontent.com/44193159/60892292-9b290a00-a267-11e9-88bc-376550cd4d54.png)
