### ISSUE TITLE
Tutorial for distributed hyperparameter tuning with Ray Tune

### ISSUE THREAD

**Issue by richardliaw** [pytorch/tutorials#538]
Hi, would you be willing to accept a tutorial for distributed hyperparameter tuning with [Tune](https://ray.readthedocs.io/en/latest/tune.html)?

Tune is a library for scalable hyperparameter tuning and integrates with libraries such as [Ax](https://ray.readthedocs.io/en/latest/tune-searchalg.html#ax-search) and [HyperOpt](https://ray.readthedocs.io/en/latest/tune-searchalg.html#hyperopt-search-tree-structured-parzen-estimators) and also provides state-of-the-art algorithms out of the box such as [Population-based Training](https://ray.readthedocs.io/en/latest/tune-schedulers.html#population-based-training-pbt) and [Asynchronous Successive Halving](https://ray.readthedocs.io/en/latest/tune-schedulers.html#asynchronous-hyperband).

I could make a PR if maintainers are willing to review/accept!

**Comment by brianjo** [comment]
Thanks Richard. Responded in e-mail.
