### ISSUE TITLE
small fix needed to make the dataset compatible with random_split

### ISSUE THREAD

**Issue by barthelemymp** [pytorch/tutorials#540]
Hello,

the __getitem__ of the custom dataset in this tutorial uses idx as int or list. However if we want to use the function random_split in order to get to train and test dataset will not work. Indeed it will feed the __getitem__ with a tensor.
adding :

```
    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()
```
solve this problem. 

regards b

**Comment by vincentqb** [comment]
Which tutorial?

**Comment by barthelemymp** [comment]
this tutorial:
https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

**Comment by jlin27** [comment]
Thanks @barthelemymp  and @vincentqb !
