### ISSUE TITLE
Sphinx error (builder name data not registered)

### ISSUE THREAD

**Issue by olegmikul** [pytorch/tutorials#541]
Notebooks for beginner and intermediate tutorials have been generated fine. When building advanced tutorial I have problems: 1) need to install torchaudio in a hard way  (no easy way, need to compile from sources and hack some command to be completed, but checked - python can import torchaudio); 2) when running "make data" I am getting Sphinx error:
make data
Running Sphinx v2.1.2

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/registry.py", line 145, in preload_builder
    entry_point = next(entry_points)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 238, in __init__
    self.preload_builder(buildername)
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 315, in preload_builder
    self.registry.preload_builder(self, name)
  File "/usr/lib/python3.7/site-packages/sphinx/registry.py", line 148, in preload_builder
    ' through entry point') % name)
sphinx.errors.SphinxError: Builder name data not registered or available through entry point

**Comment by 9bow** [comment]
What did you intend to do with `make data`?

As I know, there're three options in [Makefile](https://github.com/pytorch/tutorials/blob/master/Makefile) - `download`, `docs`, `html-noplot` (and one more, `clean-cache`, but will not mention it)
`make download` is for downloading training data, `make docs` build every document with galleries (every python codes ran and drop result), and `make html-noplot` also builds every document but without galleries.

There're also many default options for sphinx, but also no such option like `data`.
```
% make help                                                                                                                                                                                                                                <master>
Sphinx v2.1.2
Please use `make target' where target is one of
  html        to make standalone HTML files
  dirhtml     to make HTML files named index.html in directories
  singlehtml  to make a single large HTML file
  pickle      to make pickle files
  json        to make JSON files
  htmlhelp    to make HTML files and an HTML help project
  qthelp      to make HTML files and a qthelp project
  devhelp     to make HTML files and a Devhelp project
  epub        to make an epub
  latex       to make LaTeX files, you can set PAPER=a4 or PAPER=letter
  latexpdf    to make LaTeX and PDF files (default pdflatex)
  latexpdfja  to make LaTeX files and run them through platex/dvipdfmx
  text        to make text files
  man         to make manual pages
  texinfo     to make Texinfo files
  info        to make Texinfo files and run them through makeinfo
  gettext     to make PO message catalogs
  changes     to make an overview of all changed/added/deprecated items
  xml         to make Docutils-native XML files
  pseudoxml   to make pseudoxml-XML files for display purposes
  linkcheck   to check all external links for integrity
  doctest     to run all doctests embedded in the documentation (if enabled)
  coverage    to run coverage check of the documentation (if enabled)
```

Please let me know if I were wrong.
And if you tell me exactly what you want, it will help. :D
Thanks.

**Comment by jlin27** [comment]
Hi @olegmikul - Happy to help. (1) We've added torchaudio to be installed from binaries in requirements.txt to help with your first issue. (2) And as @9bow mentioned, can you please confirm if instead of `make data` perhaps it was `make docs` you were after instead?
