### ISSUE TITLE
seq2seq with attention GRU inputs

### ISSUE THREAD

**Issue by kushalj001** [pytorch/tutorials#542]
The tutorial on seq2seq translation with attention has the following code for the encoder part.
Here, the GRU takes in two parameters and both are given as hidden_size.
However, in the documentation, the GRU inputs (or more specifically the parameters) are (input_size,hidden_size).
Kindly let me know if this is a valid error or I am going wrong somewhere.
Thanks.
![image](https://user-images.githubusercontent.com/32245327/59960489-8b2ecd80-94e6-11e9-882a-094c078de923.png)

**Comment by dhavalmj007** [comment]
Here the output of Embedding layer is hidden_size and output of GRU is also hidden_size which is 256.
