### ISSUE TITLE
Size error in convolution layer and pooling layer！

### ISSUE THREAD

**Issue by matrix-yang** [pytorch/tutorials#544]
![image](https://user-images.githubusercontent.com/30305908/60065724-6ed59f80-9737-11e9-8325-1032377bd4af.png)
Size error in convolution layer and pooling layer! The last row and last column of the convolution layer2 are not pooled and are simply discarded.

**Comment by holly1238** [comment]
This issue is fixed and merged in https://github.com/pytorch/tutorials/pull/1257
