### ISSUE TITLE
Typo in Data loading and Preprocessing Tutorial code

### ISSUE THREAD

**Issue by chinmaySinghal** [pytorch/tutorials#547]
In the Rescale(object) class, the resize transformation line is written as img = transform.resize(image, (new_h, new_w)), while it should actually be tranforms.Resize(image, (new_h, new_w)).

**Comment by chsasank** [comment]
Please note the imports at the top of the tutorial: 

`from skimage import io, transform`

transform is therefore a module from scikit-image and not torchvision. The tutorial didn't use torchvision transforms to make it explicit how transforms are implemented.
