### ISSUE TITLE
how to set two inputs for caffe2

### ISSUE THREAD

**Issue by mmmmayi** [pytorch/tutorials#548]
when I try to run the model on mobile devices by ONNX, I read the code in official turorials as follow:

`import onnx`
`import caffe2.python.onnx.backend as onnx_caffe2_backend`
`model = onnx.load("super_resolution.onnx")`
`prepared_backend = onnx_caffe2_backend.prepare(model)`
`W = {model.graph.input[0].name: x.data.numpy()}`
`c2_out = prepared_backend.run(W)[0]`

the input in this demo is x, but what should i do if i want to set two inputs?
thanks for you attention!

**Comment by jspisak** [comment]
Hi @mmmmayi - thanks for dropping in this issue. A few updates and suggestions:

- We really dont recommend using the PT+ONNX+C2 path as there isnt active development on the C2 frontend

- You can learn about multiple inputs in PyTorch here: https://discuss.pytorch.org/t/nn-module-with-multiple-inputs/237

- The MSFT team has taken a pass and updated the onnx tutorial to support onnx runtime and do a lot of cleanup. You can find it here. https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

If this helps, please also close out this issue.. :)
