### ISSUE TITLE
does the attention need do mask on the encoder_outputs?

### ISSUE THREAD

**Issue by chuanhuayang** [pytorch/tutorials#593]
attn_weights = self.attn(rnn_output, encoder_outputs)
this is the attn_weights,  the number of output vector in a batch is different because the input length is different,  and the number of output vector is padded align max_seq_len in the batch.
but when compute attn_weights,  there is no mask operation on the padding output vec，is this right ?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
