### ISSUE TITLE
Tight layout for figures in torchaudio tutorial

### ISSUE THREAD

**Issue by vincentqb** [pytorch/tutorials#600]
Some figures in [the torchaudio tutorial](https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html) have a wide aspect ratio, but are displayed with a lot of white space above and below them as if they were square.

* When downloading an image from the rendered HTML, the white is part of it.
* `plt.tight_layout()` does not address that.

CC @fbbradheintz

**Comment by vincentqb** [comment]
@cpuhrsch @jamarshon

**Comment by carljparker** [comment]
Looks as though this is fixed by Update audio preprocessing tutorial #797
