### ISSUE TITLE
Running .backward() without a CUDA-capable device

### ISSUE THREAD

**Issue by pietromarchesi** [pytorch/tutorials#64]
Should it be possible to run Variable.backwards() without having a CUDA-enabled GPU? I was trying to run the code from the [autograd tutorial ](http://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html). I didn't find it mentioned that one must have a CUDA GPU to run the source/notebooks.

**Comment by chsasank** [comment]
Indeed you don't need a gpu to do `backward()`. Pytorch works fine on CPU just slower. Did you get any error running the autograd tutorial.

**Comment by pietromarchesi** [comment]
Right, exactly. I get the following error running the tutorial code:
` cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/autograd/engine.cpp:359`

**Comment by chsasank** [comment]
Please download the python file from the end of the tutorial and run it as `$ python autograd_tutorial.py` and post the complete stack trace of error.

**Comment by pietromarchesi** [comment]
`THCudaCheck FAIL file=torch/csrc/autograd/engine.cpp line=359 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "autograd_tutorial.py", line 80, in <module>
    out.backward()
  File "/home/pietro/Envs/basic3/lib/python3.5/site-packages/torch/autograd/variable.py", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at torch/csrc/autograd/engine.cpp:359
`

**Comment by pietromarchesi** [comment]
Apologies for the formatting, I'll try to fix it.

**Comment by chsasank** [comment]
Did you install cuda drivers (despite not having gpu) by any chance? Try uninstall and reinstall pytorch via conda.

Check this out: https://github.com/pytorch/pytorch/issues/1154

**Comment by pietromarchesi** [comment]
I had CUDA drivers installed in fact, but now I have uninstalled them and made a fresh install of pytorch in a new virtual environment, and I still get the same issue. Thanks for the link to the other discussion, I will check it out.

**Comment by pietromarchesi** [comment]
Solved, thank you @chsasank!

**Comment by pietromarchesi** [comment]
For future reference: I uninstalled all the Nvidia drivers (see this [post](http://askubuntu.com/questions/530043/removing-nvidia-cuda-toolkit-and-installing-new-one)), made a new virtual environment in which a reinstalled pytorch using pip. After rebooting, everything worked.

**Comment by soumith** [comment]
@pietromarchesi this issues is fixed in master (where you have drivers but no GPU) and the patch will be present in the next binary release.
