### ISSUE TITLE
grammar issue

### ISSUE THREAD

**Issue by jJayyyyyyy** [pytorch/tutorials#641]
The first paragraph is like
> Central to all neural networks in PyTorch is the autograd package. Let’s first briefly visit this, and we will then `go to training` our first neural network.

Is it supposed to be `go training` or `go to train` instead?

**Comment by urandu** [comment]
In my opinion, I think the grammar is fine `go to training` is valid because it means going going to the next step which is training

**Comment by MadhuSaini22** [comment]
from my point of view, there is no grammatical  error here and the sentence is perfect!
