### ISSUE TITLE
Kernel crashing in running Transfer Learning ipynb and py scripts

### ISSUE THREAD

**Issue by clived2** [pytorch/tutorials#642]
I am running these two scripts on a Ubuntu 18.04 LTS desktop kernel 5.2.11. I run a lot of scripts on both Spyder and Jupyter notebook using the PyTorch framework . The Data Loading Tutorial ran fine but in the Transfer Loading scripts, the kernel crashed while running the Finetuning the convnet section: 

visualize_model(model_ft)
Epoch 0/24
----------

Kernel died, restarting

I am just passing this onto you, asking for any suggestions as to resolving this

Thanl you

**Comment by holly1238** [comment]
Closing this as it is almost 2 years old. If you are still having trouble, feel free to reopen this or open a new issue.
