### ISSUE TITLE
No non-linearity after the Linear layers!!

### ISSUE THREAD

**Issue by shang-vikas** [pytorch/tutorials#647]
https://github.com/pytorch/tutorials/blob/ffecdf7e278a3008a7f99efb2fb3cdc7060c8f11/intermediate_source/char_rnn_generation_tutorial.py#L164
https://github.com/pytorch/tutorials/blob/ffecdf7e278a3008a7f99efb2fb3cdc7060c8f11/intermediate_source/char_rnn_generation_tutorial.py#L165
https://github.com/pytorch/tutorials/blob/ffecdf7e278a3008a7f99efb2fb3cdc7060c8f11/intermediate_source/char_rnn_generation_tutorial.py#L167

Hi,
I was following through the tutorial and found out that there is no non-linearity applied in the tutorials after the hidden layer, hence was not getting the expected results. @spro could you please tell if this is by mistake?

**Comment by holly1238** [comment]
Closing this as it is almost 2 years old. If you are still having trouble, feel free to reopen this or open a new issue. You can also post your question in our PyTorch discussion forum where you'll get a quick response from our skilled community members (https://discuss.pytorch.org/).
