### ISSUE TITLE
ImportError: No module named pyglet in RL tutorial

### ISSUE THREAD

**Issue by NataliaDiaz** [pytorch/tutorials#65]
Hi! Running the reinforcement_q_learning.ipynb tutorial however, may fail with the error:
 `File "/home/gym/gym/envs/classic_control/rendering.py", line 18, in <module>
    import pyglet
gym.utils.reraise.ReraisedException: The original exception was:
exceptions.ImportError: No module named pyglet
`

I fixed it, after installing the full version of GYM in Ubuntu by doing also:
pip install -e .[all]

Shouldn't  the following command on Ubuntu 14.04 install all dependencies?

apt-get install -y python-numpy python-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python-opengl libboost-all-dev libsdl2-dev swig

**Comment by soumith** [comment]
> Shouldn't the following command on Ubuntu 14.04 install all dependencies?

that command doesn't install gym, i dont see it there...

**Comment by chsasank** [comment]
`sudo pip install gym` should work. I recommend using anaconda python if that doesn't work.
