### ISSUE TITLE
AttributeError: 'builtin_function_or_method' object has no attribute 'clamp'

### ISSUE THREAD

**Issue by isalirezag** [pytorch/tutorials#661]
running [this example](https://github.com/pytorch/tutorials/blob/master/beginner_source/examples_autograd/two_layer_net_custom_function.py) gives me error : `AttributeError: 'builtin_function_or_method' object has no attribute 'clamp'`

and if we change it to `return torch.clamp(input, min=Th)` it will say:
`TypeError: clamp(): argument 'input' (position 1) must be Tensor, not builtin_function_or_method`

**Comment by isalirezag** [comment]
My bad, it works fine!

**Comment by kimbo** [comment]
@isalirezag How did you fix this?

**Comment by kimbo** [comment]
Nvmnd lol. I was missing some parentheses somewhere
