### ISSUE TITLE
cartpole example not working

### ISSUE THREAD

**Issue by poedator** [pytorch/tutorials#683]
I am unable to make the cartpole example working. It fails to learn even after 2000 iterations. Please check what may be wrong.  My notebook with test is here, fully based on your notebook: https://github.com/poedator/otus_data_science/blob/master/project/reinforcement_q_learning_torch_example_tested.ipynb

**Comment by cnalty** [comment]
I have the same issue
![Figure](https://user-images.githubusercontent.com/37752899/80039782-910a8c00-84c6-11ea-81fb-cc02a37c52ea.png)

**Comment by adam-dziedzic** [comment]
I have the same issue - this example doesn't work at all! I ran many episodes and the average episode length is about 23 only. It starts with roughly 23 and never learns how to increase the episode length! Any ideas on how we could tackle the problem?

episode;max duration;episode duration;avg. duration
0;17;17;17.0
1;17;11;14.0
2;22;22;16.666666666666668
3;22;17;16.75
4;23;23;18.0
5;23;23;18.833333333333332
....
21858;144;16;23.315293471796515
21859;144;20;23.315141811527905
21860;144;15;23.31476144732629
21861;144;35;23.315295947305827
21862;144;65;23.317202579700865
21863;144;21;23.317096597145994
21864;144;15;23.316716213126

**Comment by holly1238** [comment]
Closing this as it is more than a year old. If you are still having trouble, feel free to reopen this or open a new issue. You can also post your question in our PyTorch discussion forum where you'll get a quick response from our skilled community members (https://discuss.pytorch.org/).

**Comment by ss32** [comment]
This example is still seemingly broken.  It functions, but never learns, even after 10k episodes.

![image](https://user-images.githubusercontent.com/4565287/144772980-f5ecfb34-2e58-48e3-9510-6dfda317b03e.png)
