### ISSUE TITLE
About transformer_tutorial.py

### ISSUE THREAD

**Issue by ruidongtd** [pytorch/tutorials#701]
Run transformer_tutorial.py, I did not get an ideal result. The final loss is about 5.0 on the valid set. But in your result, the final loss is about 0.89. Why? I hope that you can check your results.

**Comment by SpringRi** [comment]
> Run transformer_tutorial.py, I did not get an ideal result. The final loss is about 5.0 on the valid set. But in your result, the final loss is about 0.89. Why? I hope that you can check your results.

I met the same situation as you. Is there any problem with the code?

This is my training log
```
| epoch   3 |   200/ 2981 batches | lr 4.51 | ms/batch 25.17 | loss  5.54 | ppl   253.56
| epoch   3 |   400/ 2981 batches | lr 4.51 | ms/batch 26.47 | loss  5.54 | ppl   254.59
| epoch   3 |   600/ 2981 batches | lr 4.51 | ms/batch 24.45 | loss  5.35 | ppl   210.14
| epoch   3 |   800/ 2981 batches | lr 4.51 | ms/batch 26.21 | loss  5.41 | ppl   222.62
| epoch   3 |  1000/ 2981 batches | lr 4.51 | ms/batch 24.26 | loss  5.36 | ppl   212.22
| epoch   3 |  1200/ 2981 batches | lr 4.51 | ms/batch 24.76 | loss  5.40 | ppl   221.48
| epoch   3 |  1400/ 2981 batches | lr 4.51 | ms/batch 24.21 | loss  5.43 | ppl   227.56
| epoch   3 |  1600/ 2981 batches | lr 4.51 | ms/batch 24.43 | loss  5.47 | ppl   236.56
| epoch   3 |  1800/ 2981 batches | lr 4.51 | ms/batch 24.66 | loss  5.40 | ppl   220.73
| epoch   3 |  2000/ 2981 batches | lr 4.51 | ms/batch 25.12 | loss  5.44 | ppl   229.62
| epoch   3 |  2200/ 2981 batches | lr 4.51 | ms/batch 25.13 | loss  5.32 | ppl   203.47
| epoch   3 |  2400/ 2981 batches | lr 4.51 | ms/batch 24.88 | loss  5.39 | ppl   218.85
| epoch   3 |  2600/ 2981 batches | lr 4.51 | ms/batch 24.26 | loss  5.40 | ppl   220.91
| epoch   3 |  2800/ 2981 batches | lr 4.51 | ms/batch 24.18 | loss  5.34 | ppl   207.78
-----------------------------------------------------------------------------------------
| end of epoch   3 | time: 76.65s | valid loss  5.55 | valid ppl   257.81
-----------------------------------------------------------------------------------------
=========================================================================================
| End of training | test loss  5.46 | test ppl   234.59
=========================================================================================
```

**Comment by ruidongtd** [comment]
> > Run transformer_tutorial.py, I did not get an ideal result. The final loss is about 5.0 on the valid set. But in your result, the final loss is about 0.89. Why? I hope that you can check your results.
> 
> I met the same situation as you. Is there any problem with the code?
> 
> This is my training log
> 
> ```
> | epoch   3 |   200/ 2981 batches | lr 4.51 | ms/batch 25.17 | loss  5.54 | ppl   253.56
> | epoch   3 |   400/ 2981 batches | lr 4.51 | ms/batch 26.47 | loss  5.54 | ppl   254.59
> | epoch   3 |   600/ 2981 batches | lr 4.51 | ms/batch 24.45 | loss  5.35 | ppl   210.14
> | epoch   3 |   800/ 2981 batches | lr 4.51 | ms/batch 26.21 | loss  5.41 | ppl   222.62
> | epoch   3 |  1000/ 2981 batches | lr 4.51 | ms/batch 24.26 | loss  5.36 | ppl   212.22
> | epoch   3 |  1200/ 2981 batches | lr 4.51 | ms/batch 24.76 | loss  5.40 | ppl   221.48
> | epoch   3 |  1400/ 2981 batches | lr 4.51 | ms/batch 24.21 | loss  5.43 | ppl   227.56
> | epoch   3 |  1600/ 2981 batches | lr 4.51 | ms/batch 24.43 | loss  5.47 | ppl   236.56
> | epoch   3 |  1800/ 2981 batches | lr 4.51 | ms/batch 24.66 | loss  5.40 | ppl   220.73
> | epoch   3 |  2000/ 2981 batches | lr 4.51 | ms/batch 25.12 | loss  5.44 | ppl   229.62
> | epoch   3 |  2200/ 2981 batches | lr 4.51 | ms/batch 25.13 | loss  5.32 | ppl   203.47
> | epoch   3 |  2400/ 2981 batches | lr 4.51 | ms/batch 24.88 | loss  5.39 | ppl   218.85
> | epoch   3 |  2600/ 2981 batches | lr 4.51 | ms/batch 24.26 | loss  5.40 | ppl   220.91
> | epoch   3 |  2800/ 2981 batches | lr 4.51 | ms/batch 24.18 | loss  5.34 | ppl   207.78
> -----------------------------------------------------------------------------------------
> | end of epoch   3 | time: 76.65s | valid loss  5.55 | valid ppl   257.81
> -----------------------------------------------------------------------------------------
> =========================================================================================
> | End of training | test loss  5.46 | test ppl   234.59
> =========================================================================================
> ```

I got the same result as you.

**Comment by zhangguanheng66** [comment]
duplicate issue (https://github.com/pytorch/examples/issues/642). Please check some ongoing discussions there.

The masked_fill func in pytorch v1.3 show different results as v1.2. I have open an issue here (https://github.com/pytorch/pytorch/issues/28508)

**Comment by zhangguanheng66** [comment]
The type promotion PR has been merged. @brianjo @SethHWeidman please close this issue.
