### ISSUE TITLE
Where is the demo dataset and model files in (EXPERIMENTAL) STATIC QUANTIZATION WITH EAGER MODE IN PYTORCH 

### ISSUE THREAD

**Issue by Aspirinkb** [pytorch/tutorials#705]
I'm trying to run the codes in [(EXPERIMENTAL) STATIC QUANTIZATION WITH EAGER MODE IN PYTORCH](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html#experimental-static-quantization-with-eager-mode-in-pytorch), but there are no dataset and model files available, such as **imagenet_1k, mobilenet_quantization.pth** and so on.    
So anyone can provide the address of the necessary files and dataset in this tutorial?

**Comment by MeiHuanshan** [comment]
maybe you can find here
https://github.com/pytorch/tutorials/blob/20f59a1a13e8834c32b78387bd2b9e01b4a9cece/Makefile

**Comment by lpuglia** [comment]
this is not ok, I think the tutorials should be self contained:

```
wget -N https://s3.amazonaws.com/pytorch-tutorial-assets/imagenet_1k.zip
unzip -q -o imagenet_1k.zip -d data
```

**Comment by MeiHuanshan** [comment]
copy link to browser and download it , It work to me

**Comment by Aspirinkb** [comment]
> this is not ok, I think the tutorials (all of them) should be self contained:
> 
> ```
> wget -N https://s3.amazonaws.com/pytorch-tutorial-assets/imagenet_1k.zip
> unzip -q -o imagenet_1k.zip -d data
> ```

I agree with you. The tutorials in the official page is better be self contained.    
For now, my issue is solved by your answers. Thanks, So I close it.

**Comment by lpuglia** [comment]
I think it is better to keep it open to make it visible, my answer is not the solution to the issue, the solution to the issue is to fix the tutorial in the repository, I can make a Pull Request but for this small change it's an overkill.
