### ISSUE TITLE
a bug in torchtext\utils.py

### ISSUE THREAD

**Issue by pakdaman** [pytorch/tutorials#706]
def unicode_csv_reader(unicode_csv_data, **kwargs):
    r"""Since the standard csv library does not handle unicode in Python 2, we need a wrapper.
    Borrowed and slightly modified from the Python docs:
    https://docs.python.org/2/library/csv.html#csv-examples

    Arguments:
        unicode_csv_data: unicode csv data (see example below)

    Examples:
        >>> from torchtext.utils import unicode_csv_reader
        >>> import io
        >>> with io.open(data_path, encoding="utf8") as f:
        >>>     reader = unicode_csv_reader(f)

    """

    # Fix field larger than field limit error
    maxInt = sys.maxsize
    while True:
        # decrease the maxInt value by factor 10
        # as long as the OverflowError occurs.
        try:
            csv.field_size_limit(maxInt)
            break
        except OverflowError:
            maxInt = int(maxInt / 10)

    csv.field_size_limit(sys.maxsize)

The last line should be csv.field_size_limit(maxInt). this bug raise to the following error in windows operating system:

OverflowError: Python int too large to convert to C long

**Comment by funkindy** [comment]
I can confirm the bug in torchtext==0.4.0, py37, win10
