### ISSUE TITLE
Using pytorch1.3.0 for quantification with error: didn't find engine for operation quantized......

### ISSUE THREAD

**Issue by YanZhiyuan0918** [pytorch/tutorials#717]
Hi,
I'm using pytorch1.3.0 to run the demo in the website “https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html”. There comes some error when running:
`torch.quantization.convert(myModel, inplace=True)`

`Runtimeerror: didn’t find engine for operation quantized: conv_prepack NoQEngine (Operator () at .. /aten/src/ATen/native/quantized/cpu/qconv_prepack.cpp:264)(no backtrace avaliable)`

The dependency:
win7 64bit Intel(R) Core(TM) i7-4790 CPU
python3.5
torch==1.3.0+cpu 
torchvision==0.4.1+cpu

Can you help me to solve this problem? Thanks a lot!!

**Comment by huangsx95** [comment]
@YanZhiyuan0918 I have the same problem. Do you have any idea?

**Comment by huangsx95** [comment]
@I run this code on Ubuntu 16.04 and it works. There may be some bug on Windows.

**Comment by huangsx95** [comment]
@YanZhiyuan0918 I run this code on Ubuntu 16.04 and it works. There may be some bug on Windows

**Comment by YanZhiyuan0918** [comment]
@huangsx95  Yes, it does work on Ubuntu. Thank you.

**Comment by YanZhiyuan0918** [comment]
@huangsx95  Hi, sorry to bother you again. Do you try to do quantization for your own code? I try to do this on my own shufflenet_v2 model, but I meet some error:
`RuntimeError: didn't find kernel to dispatch to for operator 'quantized:: conv2d'. Tried to look up kernel for dispatch key 'CPUTensorId'. Registered dispatch keys are [quantizedCPUTensorId](look up_at /pytorch/aten/src/ATen/core/dispatch/DispatchTable.h:249)`

**Comment by iamrishab** [comment]
@YanZhiyuan0918 
Can you try adding the following line to your code:
`torch.backends.quantized.engine = 'qnnpack'`
You can find the reference [here](https://github.com/pytorch/pytorch/issues/28945) and [here](https://github.com/pytorch/pytorch/issues/29327)
