### ISSUE TITLE
Hello, any idea for creating a new article with the same meaning according to the given article

### ISSUE THREAD

**Issue by jobsfan** [pytorch/tutorials#718]
input: several news with the same topic, maybe the same event reported by different media company.

output: a brand-new news article with the same meaning.

I got an idea and don't know whether it works or not:
for the tutorial https://pytorch.org/tutorials/beginner/torchtext_translation_tutorial.html.
It translates Germany to English. If I change it from Chinese to Chinese. The input language and the output language are the same.  Will it work as I expected?

**Comment by holly1238** [comment]
Closing this as it is almost 2 years old. If you still need assistance, feel free to reopen this or open a new issue. You can also post your question in our PyTorch discussion forum where you'll get a quick response from our skilled community members (https://discuss.pytorch.org/).
