### ISSUE TITLE
Dynamic Net and weight sharing

### ISSUE THREAD

**Issue by gll89** [pytorch/tutorials#723]
Hello,

two questions about the tutorial of CONTROL FLOW + WEIGHT SHARING [https://pytorch.org/tutorials/beginner/examples_nn/dynamic_net.html](url).

1. When the model is being created, the number of hidden layers is uncertain. However, when the model is being trained, the model is determined. Am I right?
2. I can not get the point of parameter sharing. Could you explain where the codes realize weight sharing?

Thanks in advance.

**Comment by holly1238** [comment]
Closing this as it is almost 2 years old. If you are still having trouble, feel free to reopen this or open a new issue. You can also post your question in our PyTorch discussion forum where you'll get a quick response from our skilled community members (https://discuss.pytorch.org/).
