### ISSUE TITLE
typo in code

### ISSUE THREAD

**Issue by yu-yuxuan** [pytorch/tutorials#724]
In tutorials/beginner_source/blitz/neural_networks_tutorial.py 
The figure of the network that classifies digit images shows 16@5x5 in S4
So it should be self.fc1 = nn.Linear(16 * 5 * 5, 120) in line 15.

**Comment by holly1238** [comment]
Kernel size is 5x5. This was fixed in the tutorial in https://github.com/pytorch/tutorials/pull/1257.
