### ISSUE TITLE
code does'nt match its image in neural_networks_tutorial

### ISSUE THREAD

**Issue by nipeone** [pytorch/tutorials#727]
conv1 kernel size in the code is 3x3,but feature map size after conv1 is 28x28 in the above image,it should be 30x30,or change the kernel size to 5x5.

**Comment by aimuch** [comment]
I also find `self.conv1 = nn.Conv2d(1, 6, 3)` should ` self.conv1 = nn.Conv2d(1, 6, 5)` and         self.conv2 has the same problem.

**Comment by aimuch** [comment]
> I also find `self.conv1 = nn.Conv2d(1, 6, 3)` should ` self.conv1 = nn.Conv2d(1, 6, 5)` and self.conv2 has the same problem.

Official has fix this problem:
```python
x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
```

**Comment by holly1238** [comment]
Kernel size is 5x5. This was fixed in the tutorial in https://github.com/pytorch/tutorials/pull/1257.
