### ISSUE TITLE
Adding explanation for parameter to backward in autograd tutorial

### ISSUE THREAD

**Issue by vincentqb** [pytorch/tutorials#729]
In a workshop on pytorch, there were questions about [the parameter passed to backward](https://github.com/pytorch/tutorials/blob/master/beginner_source/blitz/autograd_tutorial.py#L170) in the autograd tutorial. It would be nice to add an explanation such as [this one](https://discuss.pytorch.org/t/what-does-tensor-backward-do-mathematically/27953/2).

**Comment by holly1238** [comment]
Refactoring of autograd tutorial with additional explanation was done in https://github.com/pytorch/tutorials/pull/1185
