### ISSUE TITLE
input variable name should be avoided in the tutorials 

### ISSUE THREAD

**Issue by DanielMarchand** [pytorch/tutorials#738]
the tutorials often use 'input' as a variable name. [This should probably be avoided.](https://stackoverflow.com/questions/59123783/why-is-the-variable-input-often-marked-special-in-python-syntax-markers/59123808?noredirect=1#comment104479047_59123808)

**Comment by carljparker** [comment]
Looks like this was fixed in:

https://github.com/pytorch/tutorials/pull/754
