### ISSUE TITLE
Netlify build script fails

### ISSUE THREAD

**Issue by stante** [pytorch/tutorials#741]
Seems like there is a problem with the build system, see: https://app.netlify.com/sites/pytorch-tutorials-preview/deploys/5de57d110f5c240007acb199

```
10:08:47 PM: Installing dependencies
10:08:47 PM: /usr/local/bin/run-build-functions.sh: line 170: /opt/buildhome/python3.6/bin/activate: No such file or directory
10:08:47 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
10:08:47 PM: Error setting python version from runtime.txt
```

**Comment by brianjo** [comment]
Thanks Alexander. 
@JoelMarcey do you know who owns that preview build? I don't seem to have access to it from my account.

**Comment by JoelMarcey** [comment]
Possibly @ailzhang? But I just gave you access, @brianjo.

**Comment by brianjo** [comment]
Thanks Joel! I’ll try to debug.

**Comment by brianjo** [comment]
This should work now on PRs that are based on our current master. We had a unicode bug merged in that seems to have broken a few things and I fixed that a couple of days ago. I just rebased a PR and it successfully completed on Netflify. https://deploy-preview-730--pytorch-tutorials-preview.netlify.com/
