### ISSUE TITLE
Dataset problem in tutorial

### ISSUE THREAD

**Issue by gchanan** [pytorch/tutorials#759]
Taken from https://github.com/pytorch/pytorch/issues/30868:

in Tutorials > TorchVision Object Detection Finetuning Tutorial
official:
class PennFudanDataset(object):
wrong! sholud be:
class PennFudanDataset(torch.utils.data.Dataset):

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/1585
