### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Ala770** [pytorch/tutorials#761]
I'm trying to run the code below:

_if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!_

but I always get the error:
**y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
 RuntimeError: CUDA error: out of memory**

I'm running this on CUDA version 10.1.243 and torch version 1.3.1 .
Anyone knows what is the problem?!

the source of the code: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#cuda-tensors

**Comment by jytug** [comment]
What is the tensor `x` in your code? What is your gpu? Please post the output of `nvidia-smi`

**Comment by Ala770** [comment]
> What is the tensor `x` in your code? What is your gpu? Please post the output of `nvidia-smi`

the tensor x is just as in the example mentioned in this tutorial:
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#cuda-tensors

and my nvidia-smi output is:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P0    N/A /  N/A |    471MiB /  4042MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1647      G   /usr/lib/xorg/Xorg                           256MiB |
|    0      1803      G   /usr/bin/gnome-shell                          98MiB |
|    0      2526      G   ...quest-channel-token=9135879204672356436   116MiB |
+-----------------------------------------------------------------------------+

**Comment by holly1238** [comment]
Closing this as it is more than a year old and the current version of the tutorial no longer has the code printed in the issue. If you are still having trouble, you can post your question in our PyTorch discussion forum where you'll get a quick response from our skilled community members (https://discuss.pytorch.org/).
