### ISSUE TITLE
'tensorflow_core._api.v2.io.gfile' has no attribute 'get_filesystem'

### ISSUE THREAD

**Issue by develooper1994** [pytorch/tutorials#762]
## 🐛 Bug

Python == '3.7.5'
torch.__version__ == '1.4.0.dev20191208'
torchvision.__version__ == '0.5.0.dev20191209'
tensorflow.__version__ == '2.0.0'
tensorboard.__version__ == '2.0.2'
https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html
VISUALIZING MODELS, DATA, AND TRAINING WITH TENSORBOARD (CELL 7)
writer.add_embedding(features,
                    metadata=class_labels,
                    label_img=images.unsqueeze(1))
===> label_img=images.unsqueeze(1) # [error happens here]

Traceback:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-39c22274501e> in <module>
     19 writer.add_embedding(features,
     20                     metadata=class_labels,
---> 21                     label_img=images.unsqueeze(1))
     22 writer.close()

~\Anaconda3\lib\site-packages\torch\utils\tensorboard\writer.py in add_embedding(self, mat, metadata, label_img, global_step, tag, metadata_header)
    779         save_path = os.path.join(self._get_file_writer().get_logdir(), subdir)
    780 
--> 781         fs = tf.io.gfile.get_filesystem(save_path)
    782         if fs.exists(save_path):
    783             if fs.isdir(save_path):

AttributeError: module 'tensorflow_core._api.v2.io.gfile' has no attribute 'get_filesystem'

**Comment by korakot** [comment]
Temporary solution

```python
import tensorflow as tf
import tensorboard as tb
tf.io.gfile = tb.compat.tensorflow_stub.io.gfile
```

**Comment by holly1238** [comment]
More details about the fix here: https://github.com/pytorch/pytorch/issues/30966
