### ISSUE TITLE
Slowdown in DQN RL Tutorial

### ISSUE THREAD

**Issue by lbollar** [pytorch/tutorials#77]
After about 5 episodes on latest master build of Pytorch, the time to execute each step t in the main loop slows way down. I tried a pip install of Pytorch as well to test if it was just my version and same thing. I am on OSX with no cuda. Is slowdown normal? I don't see anything in the optimization step that should really slow this down over time. Didn't know if this could be gym related as well. 

If this isn't normal I will try to dig in some more and see what is causing this for me.

Thanks

**Comment by apaszke** [comment]
It's not normal
