### ISSUE TITLE
Using CUDA for deep learning

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/tutorials#771]
For the deep learning [tutorial](https://pytorch.org/tutorials/beginner/nlp/deep_learning_tutorial.html), I have added the device command at the top to offload the work on GPU.

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.device("cuda:0")
```
However, no process will go to the GPU. I see only CPU usage. 
How can I fix that?

**Comment by holly1238** [comment]
Closing this as it is more than a year old. If you are still having trouble, feel free to reopen this or open a new issue. You can also post your question in our PyTorch discussion forum where you'll get a quick response from our skilled community members (https://discuss.pytorch.org/).
