### ISSUE TITLE
Reinforcement learning example with no x11 server

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/tutorials#773]
For the reinforcement learning tutorial, there are some problem with gym and ssh with x11 forwarding. Many people have reported such a bug.

I tried to modify the DQN in order to not open any window. But I wasn't successful. Any idea? is that possible to silently run the DQN?

**Comment by holly1238** [comment]
Closing this as it is more than a year old. If you are still having trouble, feel free to reopen this or open a new issue. You can also post your question in our PyTorch discussion forum where you'll get a quicker response from our skilled community members (https://discuss.pytorch.org/).
