### ISSUE TITLE
Clarify why there are 6 output channels

### ISSUE THREAD

**Issue by jlin27** [pytorch/tutorials#790]
In the [Define the network section of the Neural Network tutorial](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#sphx-glr-beginner-blitz-neural-networks-tutorial-py), clarify why is it 6 outputs? Is it bias? 

![image](https://user-images.githubusercontent.com/8042156/70950107-730eb580-2014-11ea-8cc2-21b28ed3e15b.png)

**Comment by JonathanSum** [comment]
I don't think it is biased. The key is you need to keep increasing the number of channel after doing the CONV to extract the feature.

**Comment by JonathanSum** [comment]
Right, I remember what I was taught in deeplearn.ai's video on coursera. that 6 output is not the bias. When we are doing on CNN, like VGG for example, we have to decrease the size of the image and increase the size of the channel to extract the feature.  VGG model uses these all the time. I hope we have more technical people come here to explain if I am wrong. However, if you want to see that video, I can post the link of it.

**Comment by parmarsuraj99** [comment]
6 output channels are the numbers of filters or kernels which will be applied to the input image (of Height x Width x 1 dimensions), So We want out model to learn some different local relations between pixels (let's say in a region of 3x3) that are not obvious for us. So we want to increase the channels (filters/ kernels) and by applying 3x3 kernels, we decrease the Height and Width of further layers. That's what convolution layers do. 
We can expect that model might have learned enough local relations between the layers and after some layers these local (spatial) relation will be given to a bigger channel (i.e. 16 `nn.Conv2d(6, 16, 3)`) that can represent entire picture in a spatially squeezed but with more channels. Then Flattening and FullyConnectedNet or GlobalAveragePooling layers can be applied. 
This is a way of encoding image into a more learnable extracted format to do operations on it

Checkout these resources
https://brohrer.github.io/how_convolutional_neural_networks_work.html

For Visualization
https://www.cs.ryerson.ca/~aharley/vis/conv/flat.html
![image](https://user-images.githubusercontent.com/9317265/73481313-95407500-43c1-11ea-91b8-9eb4a4763ff2.png)

**Comment by boulabiar** [comment]
https://github.com/pytorch/tutorials/pull/859

**Comment by jlin27** [comment]
Addressed in recipe
