### ISSUE TITLE
cuda issue

### ISSUE THREAD

**Issue by brad0taylor** [pytorch/tutorials#8]
When i run this code

> a = torch.Tensor(5, 3)  # construct a 5x3 matrix, uninitialized
> b = torch.Tensor(5, 3)  # construct a 5x3 matrix, uninitialized
> if torch.cuda.is_available():
>     aa= a.cuda()
>     bb = b.cuda()
>     aa + bb  

I get the following error message
`RuntimeError: cuda runtime error (8) : invalid device function at /data/users/soumith/miniconda2/conda-bld/pytorch-0.1.6_1484802121799/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:246
`

**Comment by soumith** [comment]
hey Brad. What GPU are you using?

**Comment by brad0taylor** [comment]
Hi - I'm using a Geforce GTX950M. The GPU install works ok with Tensorflow and Theano. Also I have Cudnn installed. I'm fairly new to this, so if you can point me to any diags,  I'd be happy to run them. Also the errror message is from the last line of code.

**Comment by soumith** [comment]
@ngimel I compile the binaries with 5.2+PTX, in that case it should work on 5.0 via JITting right? or is PTX only generated forward (like 5.2+PTX only generates for 5.2+ archs)?

**Comment by ngimel** [comment]
Jitting works only forward, so probably you should add compilation for 5.0.

**Comment by soumith** [comment]
oh ok good to know. I'll add 5.0 to the list as well.

@brad0taylor it's a screw up on my end. I'll fix it with issuing new binaries by tomorrow so that you can reinstall and it'll work. If you want to try things right away, please install via source: https://github.com/pytorch/pytorch/blob/master/README.md#from-source

**Comment by brad0taylor** [comment]
@sousmith thanks very much. I'll try again tomorrow

**Comment by soumith** [comment]
has been fixed
