### ISSUE TITLE
Code in Adversarial examples tutorial needs to be vectorized and it is too slow. 

### ISSUE THREAD

**Issue by AmrKhalifa** [pytorch/tutorials#810]
The code can be vectorized to work on a batch of examples instead of 1 example at a time. 
I modified it in my implementation, and I also added code for different attacks, 
please check the following code to see my implementation. 

https://github.com/AmrKhalifa/Utilizing-Variational-Auto-Encoder-Representations-to-Enhance-Neural-Networks-Adversarial-Robustness/blob/master/Code/vae_classifier_attacks.py

check the function :
test_attack()

 @inkawhich

**Comment by mikebrow** [comment]
/assigntome

finished the other assigned ready for the next one :)
