### ISSUE TITLE
PyTorch static quantization tutorial refers to incorrect Makefile lines

### ISSUE THREAD

**Issue by jjohnson-arm** [pytorch/tutorials#813]
### Summary
Minor issue.
Makefile link is out of date in static quantization tutorial.
Maybe use version link instead?

### Details
In https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html, in section 3 under the "ImageNet Data" heading, there is a link to a Makefile which is out of date/incorrect as it doesn't point to the ImageNet data lines in the Makefile anymore:
https://github.com/pytorch/tutorials/blob/master/Makefile#L97-L98

PyTorch github links: 
* https://github.com/pytorch/tutorials/blob/master/advanced_source/static_quantization_tutorial.py#L334
* revision: https://github.com/pytorch/tutorials/blob/0fea3417af0c3ebaba94b8d5408b12d41cd608a9/advanced_source/static_quantization_tutorial.py#L334

Unfortunately the master of PyTorch tutorials Makefile has moved on, and I think the author was expecting something like:
https://github.com/pytorch/tutorials/blob/3c6390fdce1aa77a543810ea2cc7bf50557f6e27/Makefile#L97-L98

Or for the current version:
https://github.com/pytorch/tutorials/blob/1d11de0814c6c3b429499c1b84af39253dd88f3e/Makefile#L100-L101

**Comment by holly1238** [comment]
Current version of the code no longer has a link to this Makefile.
