### ISSUE TITLE
bug in named_tensor_tutorial

### ISSUE THREAD

**Issue by stas00** [pytorch/tutorials#821]
In https://pytorch.org/tutorials/intermediate/named_tensor_tutorial.html I think there is a bug:

```
dot_prod = q.div_(scale).matmul(k.align_to(..., 'D_head', 'T_key'))
[...]
attn_weights = self.attn_dropout(F.softmax(dot_prod / scale,
                                                   dim='T_key'))
```
the scaling is done twice, and I think it should be done only once.

Thanks.

**Comment by arunppsg** [comment]
I think the tutorial has been removed in #1952 since namedtensor has been deprecated.

**Comment by stas00** [comment]
Thank you for discovering that, @arunppsg - I guess I should close it then.
