### ISSUE TITLE
Pytorch tensor tutorial view method

### ISSUE THREAD

**Issue by panpan2** [pytorch/tutorials#829]
https://github.com/pytorch/tutorials/blob/8244bffa52641fab0c37d35c6843faa1beaba06b/beginner_source/blitz/tensor_tutorial.py#L116

As far as I understand the view method is not part of ``torch`` but part of ``torch.Tensor``. Should this be changed to:
Resizing: If you want to resize/reshape tensor, you can use ``torch.Tensor.view``:

**Comment by robertoschiavone** [comment]
I'm just leaving a link to the docs to clear any doubt
https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view
