### ISSUE TITLE
Image of the example convnet is not consistent with the implementation

### ISSUE THREAD

**Issue by hagoston** [pytorch/tutorials#839]
In the tutorial of [neural networks](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#), the image of the example convnet is not the same as the code below it.

Based on the image conv layers should have 5x5 square kernels:
`self.conv1 = nn.Conv2d(1, 6, 5)`
`self.conv2 = nn.Conv2d(6, 16, 5)`
`self.fc1 = nn.Linear(16 * 5 * 5, 120)`
`self.fc2 = nn.Linear(120, 84)`
`self.fc3 = nn.Linear(84, 10)`

**Comment by itstartstosnow** [comment]
Yes, I encountered this problem too while going through the tutorial. It is a minor issue but it did take me a while to search the documentation and try to understand the output shape of conv2d ....

**Comment by holly1238** [comment]
Kernel size is 5x5. This was fixed in the tutorial in https://github.com/pytorch/tutorials/pull/1257.
