### ISSUE TITLE
Removed method used in data_loading_tutorial

### ISSUE THREAD

**Issue by stefan-1992** [pytorch/tutorials#846]
Method DataFrame.as_matrix() was deprecated in Pandas 0.23 and removed in 1.0.0. DataFrame.values should be used instead.

Line 70 in data_loading_tutorial.py should be changed from:
landmarks = landmarks_frame.iloc[n, 1:].as_matrix()
to
landmarks = landmarks_frame.iloc[n, 1:].values

**Comment by holly1238** [comment]
this issue has been fixed
