### ISSUE TITLE
Why is the pytorch sphinx theme included as a submodule?

### ISSUE THREAD

**Issue by wAuner** [pytorch/tutorials#850]
I'm not an expert in sphinx, but after a lot of testing and headache while trying to improve a tutorial I really wonder why the sphinx theme under `./src` is included at all (as a submodule on github).
If you clone the repo with `git clone ...` it doesn't get downloaded.
The theme gets downloaded with `pip install -e git+git://github.com/pytorch/pytorch_sphinx_theme.git#egg=pytorch_sphinx_theme` as it is defined in the `requirements.txt`. If the dir `src/pytorch-sphinx-theme` already exists you get ask if you want to wipe it, no matter if it is empty or not.
And if you cloned the repo with `--recurse-submodules` you'd download an old version of the theme. 
So why not drop the submodule and just include an empty `src` dir where the theme will be installed w/o error messages during installation from `requirements.txt`?

**Comment by svekars** [comment]
https://github.com/pytorch/tutorials/pull/3038 - removed
