### ISSUE TITLE
quantization-aware training (weight isn't updated)

### ISSUE THREAD

**Issue by georgetseng1128** [pytorch/tutorials#855]
Hi, we have try quantization aware training sample of following link:
[https://github.com/pytorch/tutorials/blob/master/advanced_source/static_quantization_tutorial.py](url)

We will check the value of weight before entering "train_one_epoch()", but value of weight not update, each epoch is the same.

The weight I observe is such as "qat_model.features[18][0].weight", is it shouldn't  be updated? Or the new weight stored elsewhere?

**Comment by holly1238** [comment]
Closing this as it is more than a year old. If you are still having trouble, feel free to reopen this or open a new issue. You can also post your question in our PyTorch discussion forum where you'll get a quick response from our skilled community members (https://discuss.pytorch.org/).
