### ISSUE TITLE
TorchScript tutorial claiming to show difference between trace and script shows no difference 

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/tutorials#860]
Out:

The TorchScript intro tutorial aims to explain the difference between traced and scripted graph generation, but the example does not highlight the difference because the example shows the code for MyCell.forward which is the same in both cases, but not for MyDecisionGate.forward where the actual difference is:

> def forward(self,
>    x: Tensor,
>    h: Tensor) -> Tuple[Tensor, Tensor]:
>  _0 = (self.dg).forward((self.linear).forward(x, ), )
>  new_h = torch.tanh(torch.add(_0, h, alpha=1))
>  return (new_h, new_h)
>Hooray! We’ve now faithfully captured the behavior of our program in TorchScript. 

There's no difference in that code piece from the prior supposedly broken code sample.

**Comment by giovanni-epsolutions** [comment]
I agree.. the two outputs presented in the [Introduction to TorchScript](https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html#using-scripting-to-convert-modules) looks the same

**Comment by holly1238** [comment]
This issue was fixed and merged in https://github.com/pytorch/tutorials/pull/866
