### ISSUE TITLE
attention weights calculation in seq2seq_translation_tutorial

### ISSUE THREAD

**Issue by WeiFoo** [pytorch/tutorials#87]
When I was walking through the [seq2seq tutorial](http://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html#loading-data-files), It seems to me that  the attention weights calculation is different from the original method in [Bahdanau et al. paper ](https://arxiv.org/abs/1409.0473).

In the paper, the attention energies are calculated based on __hidden states__  of the decoder and __annotations h_i__, which is a concatenated forward and backward states of the encoder(see s3.2 in the paper).

However, in the [tutorial](https://github.com/pytorch/tutorials/blob/master/intermediate_source/seq2seq_translation_tutorial.py#L473-L474), it seems that  attention energies are calculated based on __inputs__ and __hidden states__ of the decoder.

```python
attn_weights = F.softmax(
            self.attn(torch.cat((embedded[0], hidden[0]), 1)))
```

I'm confused here. Did I miss something?

**Comment by spro** [comment]
[The source tutorial](https://github.com/spro/practical-pytorch/blob/master/seq2seq-translation/seq2seq-translation.ipynb) was recently updated to address this, accurately implementing the Bahdanau attention mechanism. The old implementation was closer to a lesser-used "location-based" strategy from [Luong et al](https://arxiv.org/abs/1508.04025). I'll make a pull request to get this up to date.

**Comment by WeiFoo** [comment]
that's cool, thanks!

**Comment by tangzk** [comment]
Hi, @spro , did you miss some detail about the definition of `GeneralAttn` in `BahdanauAttnDecoderRNN` class.

**Comment by ChuyuHsu** [comment]
`GeneralAttn` is missing

**Comment by soloice** [comment]
@WeiFoo @spro Please change the seq2seq machine translation link in PyTorch tutorial.
Currently the link is [seq2seq_translation_tutorial](https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html), in which the calculation of Attention is wrong.
Please change it to [this one](https://github.com/spro/practical-pytorch/blob/master/seq2seq-translation/seq2seq-translation.ipynb) or replace the source file with this correct one.
