### ISSUE TITLE
Missing last row and column of image in result of RandomCrop in data_loading_tutorial

### ISSUE THREAD

**Issue by AntonDemchenko** [pytorch/tutorials#876]
Result of cropping never contains last column and last row of image pixels.

Method np.random.randint(low, high) returns value from low (inclusive) and to high(exclusive) (See [documentation](https://numpy.org/doc/1.18/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy.random.randint))
Therefore variable `top` takes value from `0` to `h - new_h - 1` inclusive. 
Maximal bottom equals `(h - new_h - 1) + new_h - 1 = h - 2` but not `h - 1`. 
Row indexed `h - 1` never gets into result.
Similarly, column indexed `w - 1`.

**Comment by arunppsg** [comment]
\assigntome
