### ISSUE TITLE
is the grad value wrong in beginner_source/blitz/autograd_tutorial.py line 92?

### ISSUE THREAD

**Issue by ningzhou** [pytorch/tutorials#89]
in line 92: `z_i = 3(x_i+2)^2` and `z_i\bigr\rvert_{x_i=1} = 27`.

I think `z_i\bigr\rvert_{x_i=1} = 6(x_i+2)\rvert_{x_i=1} = 6*(1+2) = 18`, please correct me if I am wrong, otherwise i will submit a pull request.

**Comment by chsasank** [comment]
Yep, you're right. Please submit PR.

**Comment by ningzhou** [comment]
I have submitted a PR.
