### ISSUE TITLE
prune: model sparity increase,but inference time doesn't cut down

### ISSUE THREAD

**Issue by misslibra** [pytorch/tutorials#905]
`prune.l1_unstructured(conv_module, name='weight', amount=0.8)<br>prune.remove(conv_module, 'weight')`

with these two function, I process all module with convolution,and their sparsity become 80%.
but the model inference time incease. Is it expected ?
and another question is that after prune,I save model with:

`torch.save(model.state_dict(), 'new_model.pth')`
and then ,load the save model,it's module sparsity go back to 0 , How to save pruned model correctly ?
Thank you !

**Comment by mickypaganini** [comment]
The inference time is supposed to remain approximately the same as that of an unpruned model, as the number of operations hasn't changed (unless you are running the operations above inside the inference loop?). The inference time is not expected to go down for now -- unless you use some custom sparse matrix algebra library to power the sparse computation (PyTorch does not support that out of the box yet, so consider pytorch pruning as an experimental module with no direct inference-time advantages for now).

What do you mean by "its module sparsity go back to 0"? How are you computing sparsity? The 0s that you inserted in the `weight` tensors should still be there after reloading.
