### ISSUE TITLE
Code doesn't run correctly for object detection tutorial

### ISSUE THREAD

**Issue by souravs17031999** [pytorch/tutorials#912]
There is a error in the colab version of the code at the end of training of the model in the object detection tutorial :
https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html

But nevertheless the code that follows it runs smoothly.
Check the error here : 
![error](https://user-images.githubusercontent.com/33771969/77840728-33756f00-71a8-11ea-8dd5-8de7fd3612bb.JPG)

**Comment by DarioHett** [comment]
I get the same error.
The error comes from the evaluate() function in engine.py but I could not trace the error anyfurther in colab.

**Comment by holly1238** [comment]
Just checked the latest version of the tutorial and can run it in colab without issue
