### ISSUE TITLE
Update the Copyright Notice to 2020

### ISSUE THREAD

**Issue by CT83** [pytorch/tutorials#941]
https://github.com/pytorch/tutorials/blob/cd4953d503eaf7194092a9f8945e54f6b30a909a/LICENSE#L3

https://github.com/pytorch/tutorials/blob/23af056a74f00b80265795a2252e9ae1f02aa735/conf.py#L100

![image](https://user-images.githubusercontent.com/17134097/78856416-5f181500-7a44-11ea-8ecb-5717b3cd7e57.png)

**Comment by CT83** [comment]
@ptrblck

**Comment by malfet** [comment]
This has been update to 2021, but probably need to be extended to 2022 now, thank you very much for reporting.
