### ISSUE TITLE
Load and batch data : "basic_english" tokenizer is giving ValueError

### ISSUE THREAD

**Issue by IshantWankhede** [pytorch/tutorials#947]
Hi,

New to pytorch. I am trying to walk through tutorial 'SEQUENCE-TO-SEQUENCE MODELING WITH NN.TRANSFORMER AND TORCHTEXT' 

In the section 'Load and batch data', when I 
`TEXT = torchtext.data.Field(tokenize=get_tokenizer("basic_english"),init_token='<sos>',eos_token='<eos>', lower=True)`
 Facing
`ValueError: Requested tokenizer basic_english, valid choices are a callable that takes a single string as input, "revtok" for the revtok reversible tokenizer, "subword" for the revtok caps-aware tokenizer, "spacy" for the SpaCy English tokenizer, or "moses" for the NLTK port of the Moses tokenization script.`

**Comment by bentrevett** [comment]
Are you using the latest version of TorchText?

**Comment by ShadmanRohan** [comment]
@IshantWankhede you need to specify a tokenizer. Try changing the parameter to tokenize=get_tokenizer("spacy") or some other supported tokenizer of your choice

**Comment by onlyonewater** [comment]
Hi, @IshantWankhede I got the same error, did you solve it?

**Comment by rajan-blackboxes** [comment]
Installing **Spacy** solved the problem.
`pip install Spacy`

**Comment by GadirajuSanjayvarma** [comment]
install Spacy and replace basic_english and spacy
