### ISSUE TITLE
UnboundLocalError on tutorial "Classifying Names with a Character-Level RNN"

### ISSUE THREAD

**Issue by marvinstanley** [pytorch/tutorials#959]
Hi, I've been getting an error on the tutorial [Classifying Names with a Character-Level RNN](https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html) .

The error was given from the `train` method in the tutorial, which gives this message:
```
<ipython-input-193-32410f73efdc> in train(category_tensor, line_tensor)
      9         output, hidden = classifier(line_tensor[i], hidden)
     10 
---> 11     loss = criterion(output, category_tensor)
     12     loss.backward()
     13 

UnboundLocalError: local variable 'output' referenced before assignment
```

Out of desperation, I've tried putting `global output` in the train method which will make the loss value to be `nan`

I've also tried running the provided Google Colab Notebook in the tutorial, which also gives the same error message. Any solution for this particular problem?

**Comment by holly1238** [comment]
Closing this as it is more than a year old. I just ran the current version of the tutorial in google colab with no errors. If this is still a problem for you, feel free to reopen this or open a new issue, thanks!
