### ISSUE TITLE
Math error in description in autograd_tutorial.py

### ISSUE THREAD

**Issue by dojomouse** [pytorch/tutorials#970]
In autograd_tutorial.py the description of the printed gradients, and associated derivation, is incorrect (lines 101-108).

The Matrix which will actually result has gradients of 18 for each element.

This makes sense, as the partial derivative of
3*(x+2)^2
is not
3/2 * (x+2) (as is indicated in the tutorial (and which would result in gradient of 4.5 at x = 1))
but rather
6x + 12 (which results in gradient of 18 at x=1... as is the actual torch output).

Explanation and embedded output should be updated.

> ###############################################################
> # You should have got a matrix of ``4.5``. Let’s call the ``out``
> # *Tensor* “:math:`o`”.
> # We have that :math:`o = \frac{1}{4}\sum_i z_i`,
> # :math:`z_i = 3(x_i+2)^2` and :math:`z_i\bigr\rvert_{x_i=1} = 27`.
> # Therefore,
> # :math:`\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)`, hence
> # :math:`\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5`.

**Comment by Preet538-neitzen** [comment]
I would like to work on this issue
//claim

**Comment by Preet538-neitzen** [comment]
I would like to work on this issue.

**Comment by holly1238** [comment]
The current version of the tutorial (https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html) has been updated such that this is no longer an issue.
