### ISSUE TITLE
update beginner tutorial to most recent pytorch version?

### ISSUE THREAD

**Issue by erindb** [pytorch/tutorials#98]
This [beginner tutorial](http://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py) uses `y.grad_fn` where, from googling around it seems like it should now use `y.creator`. The image is updated, but the text/code isn't.

Regardless, the tutorial should probably say what version of PyTorch it's for and how to check, right?

I'm happy to make the modifications and do a pull request, but wasn't sure what kind of solution was desired.

**Comment by chsasank** [comment]
I've fixed this. We've had multiple issues on this specific problem. Eg, #97, #93.
I've created branch 'release' and website is being built from this branch until a new pytorch release.

Hope it helps.

**Comment by chsasank** [comment]
Sorry for the confusion.

**Comment by erindb** [comment]
Aaaah sorry about that. I should have realized there were already issues for this. Thank you for fixing the site to match release! Would it make sense to also say which version the tutorial is set up for in the tutorial? Like in the note for "have torch and torch vision installed", it could also say which version?
