### ISSUE TITLE
minor formatting issue in dynamic quantization 

### ISSUE THREAD

**Issue by gottbrath** [pytorch/tutorials#980]
https://pytorch.org/tutorials/recipes/recipes/dynamic_quantization.html

the blog link doesn't look right. 

<img width="903" alt="Screen Shot 2020-05-05 at 6 03 13 PM" src="https://user-images.githubusercontent.com/45861273/81129895-b8b41800-8efa-11ea-931f-00a1e446ec36.png">

**Comment by gottbrath** [comment]
you can probably assign this to me.

**Comment by holly1238** [comment]
The link formatting is fixed on the site.
